// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-openbao, generated — see fetch-specs.ts). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as T from "../traits.ts";
import {
  OpenBaoProtocol,
  type OpenBaoOpError,
  type OpenBaoOpContext,
} from "../protocol.ts";
import * as Retry from "../retry.ts";

export type { OpenBaoOpError, OpenBaoOpContext };

export interface DeleteRateLimitQuotasRequest {
  /** Name of the quota rule. */
  name: string;
}
export const DeleteRateLimitQuotasRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/sys/quotas/rate-limit/{name}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "DeleteRateLimitQuotasRequest",
}) as any as S.Schema<DeleteRateLimitQuotasRequest>;

export interface DeleteRateLimitQuotasResponse {}
export const DeleteRateLimitQuotasResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DeleteRateLimitQuotasResponse",
}) as any as S.Schema<DeleteRateLimitQuotasResponse>;

export type ListRateLimitQuotasRequestList = "true";
export const ListRateLimitQuotasRequestList = S.String;

export interface ListRateLimitQuotasRequest {
  /** Must be set to `true` */
  list: ListRateLimitQuotasRequestList | (string & {});
}
export const ListRateLimitQuotasRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    list: ListRateLimitQuotasRequestList.pipe(T.Query()),
  }).pipe(T.Http({ method: "GET", uri: "/sys/quotas/rate-limit", code: 200 })),
).annotate({
  identifier: "ListRateLimitQuotasRequest",
}) as any as S.Schema<ListRateLimitQuotasRequest>;

export type RateLimitQuotasListResponseKeysList = Array<string>;
export const RateLimitQuotasListResponseKeysList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<RateLimitQuotasListResponseKeysList>;

export interface RateLimitQuotasListResponse {
  keys?: RateLimitQuotasListResponseKeysList;
}
export const RateLimitQuotasListResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    keys: S.optional(RateLimitQuotasListResponseKeysList),
  }),
).annotate({
  identifier: "RateLimitQuotasListResponse",
}) as any as S.Schema<RateLimitQuotasListResponse>;

/** Specifies the list of exempt paths from all rate limit quotas. If empty no paths will be exempt. */
export type RateLimitQuotasConfigureRequestRateLimitExemptPathsList =
  Array<string>;
export const RateLimitQuotasConfigureRequestRateLimitExemptPathsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<RateLimitQuotasConfigureRequestRateLimitExemptPathsList>;

export interface RateLimitQuotasConfigureRequest {
  /** If set, starts audit logging of requests that get rejected due to rate limit quota rule violations. */
  enable_rate_limit_audit_logging?: boolean;
  /** If set, additional rate limit quota HTTP headers will be added to responses. */
  enable_rate_limit_response_headers?: boolean;
  /** Specifies the list of exempt paths from all rate limit quotas. If empty no paths will be exempt. */
  rate_limit_exempt_paths?: RateLimitQuotasConfigureRequestRateLimitExemptPathsList;
}
export const RateLimitQuotasConfigureRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    enable_rate_limit_audit_logging: S.optional(S.Boolean),
    enable_rate_limit_response_headers: S.optional(S.Boolean),
    rate_limit_exempt_paths: S.optional(
      RateLimitQuotasConfigureRequestRateLimitExemptPathsList,
    ),
  }).pipe(T.Http({ method: "POST", uri: "/sys/quotas/config", code: 200 })),
).annotate({
  identifier: "RateLimitQuotasConfigureRequest",
}) as any as S.Schema<RateLimitQuotasConfigureRequest>;

export interface RateLimitQuotasConfigureResponse {}
export const RateLimitQuotasConfigureResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "RateLimitQuotasConfigureResponse",
}) as any as S.Schema<RateLimitQuotasConfigureResponse>;

export interface RateLimitQuotasReadConfigurationRequest {}
export const RateLimitQuotasReadConfigurationRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({}).pipe(
      T.Http({ method: "GET", uri: "/sys/quotas/config", code: 200 }),
    ),
).annotate({
  identifier: "RateLimitQuotasReadConfigurationRequest",
}) as any as S.Schema<RateLimitQuotasReadConfigurationRequest>;

export type RateLimitQuotasReadConfigurationResponseRateLimitExemptPathsList =
  Array<string>;
export const RateLimitQuotasReadConfigurationResponseRateLimitExemptPathsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<RateLimitQuotasReadConfigurationResponseRateLimitExemptPathsList>;

export interface RateLimitQuotasReadConfigurationResponse {
  enable_rate_limit_audit_logging?: boolean;
  enable_rate_limit_response_headers?: boolean;
  rate_limit_exempt_paths?: RateLimitQuotasReadConfigurationResponseRateLimitExemptPathsList;
}
export const RateLimitQuotasReadConfigurationResponse = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      enable_rate_limit_audit_logging: S.optional(S.Boolean),
      enable_rate_limit_response_headers: S.optional(S.Boolean),
      rate_limit_exempt_paths: S.optional(
        RateLimitQuotasReadConfigurationResponseRateLimitExemptPathsList,
      ),
    }),
).annotate({
  identifier: "RateLimitQuotasReadConfigurationResponse",
}) as any as S.Schema<RateLimitQuotasReadConfigurationResponse>;

export interface RateLimitQuotasWriteRequest {
  /** Name of the quota rule. */
  name: string;
  /** If set, when a client reaches a rate limit threshold, the client will be prohibited from any further requests until after the 'block_interval' has elapsed. */
  block_interval?: number;
  /** If set to true, child namespaces will use this quota, unless another more specific quota exists. Can only be set on namespace quotas. A quota on the root namespace will by default be inheritable. */
  inheritable?: boolean;
  /** The duration to enforce rate limiting for (default '1s'). */
  interval?: number;
  /** Path of the mount or namespace to apply the quota. A blank path configures a global quota. For example namespace1/ adds a quota to a full namespace, namespace1/auth/userpass adds a quota to userpass in namespace1. */
  path?: string;
  /** The maximum number of requests in a given interval to be allowed by the quota rule. The 'rate' must be positive. */
  rate?: number;
  /** Login role to apply this quota to. Note that when set, path must be configured to a valid auth method with a concept of roles. */
  role?: string;
  /** Type of the quota rule. */
  type?: string;
}
export const RateLimitQuotasWriteRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.String.pipe(T.Label()),
    block_interval: S.optional(S.Number),
    inheritable: S.optional(S.Boolean),
    interval: S.optional(S.Number),
    path: S.optional(S.String),
    rate: S.optional(S.Number),
    role: S.optional(S.String),
    type: S.optional(S.String),
  }).pipe(
    T.Http({ method: "POST", uri: "/sys/quotas/rate-limit/{name}", code: 200 }),
  ),
).annotate({
  identifier: "RateLimitQuotasWriteRequest",
}) as any as S.Schema<RateLimitQuotasWriteRequest>;

export interface RateLimitQuotasWriteResponse {}
export const RateLimitQuotasWriteResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "RateLimitQuotasWriteResponse",
}) as any as S.Schema<RateLimitQuotasWriteResponse>;

export interface ReadRateLimitQuotasRequest {
  /** Name of the quota rule. */
  name: string;
}
export const ReadRateLimitQuotasRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({ method: "GET", uri: "/sys/quotas/rate-limit/{name}", code: 200 }),
  ),
).annotate({
  identifier: "ReadRateLimitQuotasRequest",
}) as any as S.Schema<ReadRateLimitQuotasRequest>;

export interface RateLimitQuotasReadResponse {
  block_interval?: number;
  inheritable?: boolean;
  interval?: number;
  name?: string;
  path?: string;
  rate?: number;
  role?: string;
  type?: string;
}
export const RateLimitQuotasReadResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    block_interval: S.optional(S.Number),
    inheritable: S.optional(S.Boolean),
    interval: S.optional(S.Number),
    name: S.optional(S.String),
    path: S.optional(S.String),
    rate: S.optional(S.Number),
    role: S.optional(S.String),
    type: S.optional(S.String),
  }),
).annotate({
  identifier: "RateLimitQuotasReadResponse",
}) as any as S.Schema<RateLimitQuotasReadResponse>;

export type DeleteRateLimitQuotasError = OpenBaoOpError;
export const deleteRateLimitQuotas: API.OperationMethod<
  DeleteRateLimitQuotasRequest,
  DeleteRateLimitQuotasResponse,
  DeleteRateLimitQuotasError,
  OpenBaoOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteRateLimitQuotasRequest,
  output: DeleteRateLimitQuotasResponse,
  errors: [],
  protocol: OpenBaoProtocol,
  retry: Retry.Retry,
}));

export type ListRateLimitQuotasError = OpenBaoOpError;
export const listRateLimitQuotas: API.OperationMethod<
  ListRateLimitQuotasRequest,
  RateLimitQuotasListResponse,
  ListRateLimitQuotasError,
  OpenBaoOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListRateLimitQuotasRequest,
  output: RateLimitQuotasListResponse,
  errors: [],
  protocol: OpenBaoProtocol,
  retry: Retry.Retry,
}));

export type RateLimitQuotasConfigureError = OpenBaoOpError;
export const rateLimitQuotasConfigure: API.OperationMethod<
  RateLimitQuotasConfigureRequest,
  RateLimitQuotasConfigureResponse,
  RateLimitQuotasConfigureError,
  OpenBaoOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: RateLimitQuotasConfigureRequest,
  output: RateLimitQuotasConfigureResponse,
  errors: [],
  protocol: OpenBaoProtocol,
  retry: Retry.Retry,
}));

export type RateLimitQuotasReadConfigurationError = OpenBaoOpError;
export const rateLimitQuotasReadConfiguration: API.OperationMethod<
  RateLimitQuotasReadConfigurationRequest,
  RateLimitQuotasReadConfigurationResponse,
  RateLimitQuotasReadConfigurationError,
  OpenBaoOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: RateLimitQuotasReadConfigurationRequest,
  output: RateLimitQuotasReadConfigurationResponse,
  errors: [],
  protocol: OpenBaoProtocol,
  retry: Retry.Retry,
}));

export type RateLimitQuotasWriteError = OpenBaoOpError;
export const rateLimitQuotasWrite: API.OperationMethod<
  RateLimitQuotasWriteRequest,
  RateLimitQuotasWriteResponse,
  RateLimitQuotasWriteError,
  OpenBaoOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: RateLimitQuotasWriteRequest,
  output: RateLimitQuotasWriteResponse,
  errors: [],
  protocol: OpenBaoProtocol,
  retry: Retry.Retry,
}));

export type ReadRateLimitQuotasError = OpenBaoOpError;
export const readRateLimitQuotas: API.OperationMethod<
  ReadRateLimitQuotasRequest,
  RateLimitQuotasReadResponse,
  ReadRateLimitQuotasError,
  OpenBaoOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ReadRateLimitQuotasRequest,
  output: RateLimitQuotasReadResponse,
  errors: [],
  protocol: OpenBaoProtocol,
  retry: Retry.Retry,
}));
