/**
 * `provisionBootstrap` — the provisioning baseline (provision-baseline.ts) as the one-time root
 * commands for a NEW cluster or node: a POSIX `sh` script, printed, never run from here.
 *
 *     bun -e "import { provisionBootstrap } from '@homeflare/alchemy/proxmox';
 *             process.stdout.write(provisionBootstrap())" | ssh root@<node> sh
 *
 * ⛔ WHY IT EXISTS: THE PROVISION LANE CANNOT CREATE ITSELF. Every resource in this package runs as a
 *   token OpenBao mints for the provision user, and a cluster without that user, its group and its
 *   grant has nothing to mint for — the plan that would create them cannot authenticate. So root
 *   makes them once, and the stack adopts and keeps them (provision-declare.ts). This is the only
 *   hand step, and it is generated from the same baseline the stack declares.
 * ⛔ NEVER A TOKEN, NEVER A PASSWORD. The users are created with neither: OpenBao mints short-lived
 *   tokens for them later, and an `@pve` user with no password cannot log in to the UI. Nothing
 *   secret is in the script, so it can be read, reviewed and pasted.
 * ★ CHECK, THEN CHANGE — IDEMPOTENT BY CONSTRUCTION. Each object is read first (`pvesh get … json`,
 *   parsed with Perl's core JSON::PP, which every PVE node has), compared with the baseline, and
 *   written only when it differs, naming what it does. A second run prints `ok` for everything and
 *   writes nothing. It also CONVERGES: a role with other privileges is set to exactly the baseline,
 *   as the stack's `Proxmox.Role` would set it (role.ts: a declaration replaces the set).
 * ★ ONE NODE PER CLUSTER. Users, groups, roles and ACLs live in `/etc/pve/user.cfg`, which pmxcfs
 *   shares across the cluster: a node joining a cluster that has the baseline needs nothing, and a
 *   run there is all `ok`. A new standalone node or a new cluster is where it creates.
 * ⚠️ NAMES ARE NOT QUOTED INTO SAFETY, THEY ARE REFUSED INTO IT: provision-baseline.ts admits only
 *   characters that need no quoting in `sh` or in a Perl `q{}`.
 */
import {
  type ProvisionBaseline,
  type ProvisionNames,
  provisionBaseline,
} from './provision-baseline.ts';

const HEADER = `#!/bin/sh
# Provisioning baseline bootstrap, generated by @homeflare/alchemy (provisionBootstrap).
# Run ONCE, as root, on one node of a NEW cluster (or a new standalone node). Every step reads
# first and writes only what differs; a second run changes nothing. No token, no password.
set -eu
[ "$(id -u)" -eq 0 ] || { echo 'bootstrap: run this as root' >&2; exit 1; }
command -v pvesh >/dev/null 2>&1 || { echo 'bootstrap: no pvesh; run this on a PVE node' >&2; exit 1; }
perl -MJSON::PP -e 1 || { echo 'bootstrap: perl cannot load JSON::PP' >&2; exit 1; }

# get <api-path> <perl>: print <perl> evaluated over the object at <api-path> (as $d).
# Fails, silently, when the object does not exist: the empty input is not JSON.
get() {
  pvesh get "$1" --output-format json 2>/dev/null | perl -MJSON::PP -0777 -ne "\\$d = decode_json(\\$_); $2" 2>/dev/null
}
`;

/** A Perl string literal with no interpolation — `@pve` in a double-quoted one is an array. */
const perlText = (text: string) => `q{${text}}`;

/** The user fields `Proxmox.User` compares, as one line both sides can produce. */
const USER_STATE =
  'my $g = $d->{groups} // []; $g = [split /,/, $g] unless ref $g; ' +
  'print join(";", "groups=" . join(",", sort @$g), "enable=" . (($d->{enable} // 1) ? 1 : 0), ' +
  '"expire=" . ($d->{expire} // 0), "email=" . ($d->{email} // ""), ' +
  '"firstname=" . ($d->{firstname} // ""), "lastname=" . ($d->{lastname} // ""), ' +
  '"comment=" . ($d->{comment} // ""))';

const roleStep = ({ role }: ProvisionBaseline): string => {
  const privs = [...role.privs].sort().join(',');
  return `
# Role ${role.roleid}: exactly the provision privileges, on no path yet.
want='${privs}'
if have=$(get /access/roles/${role.roleid} 'print join(",", sort grep { /\\./ } keys %$d)'); then
  if [ "$have" = "$want" ]; then echo 'role ${role.roleid}: ok'
  else echo 'role ${role.roleid}: setting the baseline privileges'; pveum role modify ${role.roleid} --privs "$want"; fi
else
  echo 'role ${role.roleid}: adding'; pveum role add ${role.roleid} --privs "$want"
fi
`;
};

const groupStep = ({ group }: ProvisionBaseline): string => `
# Group ${group.groupid}: OpenBao may mint only for its members.
if have=$(get /access/groups/${group.groupid} 'print $d->{comment} // ""'); then
  if [ "$have" = '${group.comment}' ]; then echo 'group ${group.groupid}: ok'
  else echo 'group ${group.groupid}: setting the comment'; pveum group modify ${group.groupid} --comment '${group.comment}'; fi
else
  echo 'group ${group.groupid}: adding'; pveum group add ${group.groupid} --comment '${group.comment}'
fi
`;

const userStep = (user: ProvisionBaseline['users'][number]): string => {
  const groups = [...user.groups].sort().join(',');
  const want = `groups=${groups};enable=1;expire=0;email=;firstname=;lastname=;comment=${user.comment}`;
  const fields = `--groups ${groups} --comment '${user.comment}'`;
  return `
# User ${user.userid} (the ${user.lane} lane): in ${groups}, enabled, no password.
if have=$(get /access/users/${user.userid} '${USER_STATE}'); then
  if [ "$have" = '${want}' ]; then echo 'user ${user.userid}: ok'
  else echo 'user ${user.userid}: setting groups, comment and account fields'
    pveum user modify ${user.userid} ${fields} --enable 1 --expire 0 --email '' --firstname '' --lastname ''; fi
else
  echo 'user ${user.userid}: adding'; pveum user add ${user.userid} ${fields}
fi
`;
};

const grantStep = (grant: ProvisionBaseline['grants'][number]): string => {
  const match =
    `print scalar grep { $_->{path} eq "/" && $_->{type} eq "user" && ` +
    `$_->{ugid} eq ${perlText(grant.userid)} && $_->{roleid} eq ${perlText(grant.roleid)} && ` +
    `($_->{propagate} // 1) } @$d`;
  return `
# Grant: ${grant.userid} holds ${grant.roleid} on /, propagated (the ${grant.lane} lane).
if [ "$(get /access/acl '${match}')" = 1 ]; then echo 'grant ${grant.userid} ${grant.roleid} /: ok'
else echo 'grant ${grant.userid} ${grant.roleid} /: adding'; pveum acl modify / --users ${grant.userid} --roles ${grant.roleid} --propagate 1; fi
`;
};

/** A role the baseline binds but does not own — the read lane's — must already exist. */
const requireRole = (roleid: string): string => `
get /access/roles/${roleid} 'print 1' >/dev/null || { echo 'bootstrap: role ${roleid} does not exist; create it, or name another readRole' >&2; exit 1; }
`;

/**
 * The script for `names` (defaults: `PROVISION_DEFAULTS`). Pure: it reads nothing and runs nothing.
 * Throws, like `provisionBaseline`, on a name the baseline refuses.
 */
export const provisionBootstrap = (names: ProvisionNames = {}): string => {
  const baseline = provisionBaseline(names);
  const borrowed = baseline.grants
    .map((grant) => grant.roleid)
    .filter((roleid) => roleid !== baseline.role.roleid);
  return [
    HEADER,
    ...[...new Set(borrowed)].map(requireRole),
    roleStep(baseline),
    groupStep(baseline),
    ...baseline.users.map(userStep),
    ...baseline.grants.map(grantStep),
    `\necho 'provision baseline: done. Next: point the OpenBao proxmox mount at these users, then deploy the stack that declares this baseline with --adopt.'\n`,
  ].join('');
};
