// AUTO-GENERATED by scripts/generate.ts from .generated-specs (pinned litellm-openapi @ 1.100.0 — see README). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
import * as T from "../traits.ts";
import {
  LitellmProtocol,
  type LitellmOpError,
  type LitellmOpContext,
} from "../protocol.ts";
import * as Retry from "../retry.ts";

export type { LitellmOpError, LitellmOpContext };

export class UnprocessableEntity
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<UnprocessableEntity>()("UnprocessableEntity", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 422 }],
  ) {}

export interface DeleteCohereProxyRouteCohereEndpointRequest {
  endpoint: string;
}
export const DeleteCohereProxyRouteCohereEndpointRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      endpoint: S.String.pipe(T.Label()),
    }).pipe(T.Http({ method: "DELETE", uri: "/cohere/{endpoint}", code: 200 })),
  ).annotate({
    identifier: "DeleteCohereProxyRouteCohereEndpointRequest",
  }) as any as S.Schema<DeleteCohereProxyRouteCohereEndpointRequest>;

export interface DeleteCohereProxyRouteCohereEndpointResponse {
  body: unknown;
}
export const DeleteCohereProxyRouteCohereEndpointResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "DeleteCohereProxyRouteCohereEndpointResponse",
  }) as any as S.Schema<DeleteCohereProxyRouteCohereEndpointResponse>;

export interface GetCohereProxyRouteCohereEndpointRequest {
  endpoint: string;
}
export const GetCohereProxyRouteCohereEndpointRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      endpoint: S.String.pipe(T.Label()),
    }).pipe(T.Http({ method: "GET", uri: "/cohere/{endpoint}", code: 200 })),
).annotate({
  identifier: "GetCohereProxyRouteCohereEndpointRequest",
}) as any as S.Schema<GetCohereProxyRouteCohereEndpointRequest>;

export interface GetCohereProxyRouteCohereEndpointResponse {
  body: unknown;
}
export const GetCohereProxyRouteCohereEndpointResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "GetCohereProxyRouteCohereEndpointResponse",
  }) as any as S.Schema<GetCohereProxyRouteCohereEndpointResponse>;

export interface PatchCohereProxyRouteCohereEndpointRequest {
  endpoint: string;
}
export const PatchCohereProxyRouteCohereEndpointRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      endpoint: S.String.pipe(T.Label()),
    }).pipe(T.Http({ method: "PATCH", uri: "/cohere/{endpoint}", code: 200 })),
  ).annotate({
    identifier: "PatchCohereProxyRouteCohereEndpointRequest",
  }) as any as S.Schema<PatchCohereProxyRouteCohereEndpointRequest>;

export interface PatchCohereProxyRouteCohereEndpointResponse {
  body: unknown;
}
export const PatchCohereProxyRouteCohereEndpointResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "PatchCohereProxyRouteCohereEndpointResponse",
  }) as any as S.Schema<PatchCohereProxyRouteCohereEndpointResponse>;

export interface PostCohereProxyRouteCohereEndpointRequest {
  endpoint: string;
}
export const PostCohereProxyRouteCohereEndpointRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      endpoint: S.String.pipe(T.Label()),
    }).pipe(T.Http({ method: "POST", uri: "/cohere/{endpoint}", code: 200 })),
  ).annotate({
    identifier: "PostCohereProxyRouteCohereEndpointRequest",
  }) as any as S.Schema<PostCohereProxyRouteCohereEndpointRequest>;

export interface PostCohereProxyRouteCohereEndpointResponse {
  body: unknown;
}
export const PostCohereProxyRouteCohereEndpointResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "PostCohereProxyRouteCohereEndpointResponse",
  }) as any as S.Schema<PostCohereProxyRouteCohereEndpointResponse>;

export interface PutCohereProxyRouteCohereEndpointRequest {
  endpoint: string;
}
export const PutCohereProxyRouteCohereEndpointRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      endpoint: S.String.pipe(T.Label()),
    }).pipe(T.Http({ method: "PUT", uri: "/cohere/{endpoint}", code: 200 })),
).annotate({
  identifier: "PutCohereProxyRouteCohereEndpointRequest",
}) as any as S.Schema<PutCohereProxyRouteCohereEndpointRequest>;

export interface PutCohereProxyRouteCohereEndpointResponse {
  body: unknown;
}
export const PutCohereProxyRouteCohereEndpointResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "PutCohereProxyRouteCohereEndpointResponse",
  }) as any as S.Schema<PutCohereProxyRouteCohereEndpointResponse>;

export type DeleteCohereProxyRouteCohereEndpointError =
  | UnprocessableEntity
  | LitellmOpError;
/** Cohere Proxy Route [Docs](https://docs.litellm.ai/docs/pass_through/cohere) */
export const deleteCohereProxyRouteCohereEndpoint: API.OperationMethod<
  DeleteCohereProxyRouteCohereEndpointRequest,
  DeleteCohereProxyRouteCohereEndpointResponse,
  DeleteCohereProxyRouteCohereEndpointError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteCohereProxyRouteCohereEndpointRequest,
  output: DeleteCohereProxyRouteCohereEndpointResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetCohereProxyRouteCohereEndpointError =
  | UnprocessableEntity
  | LitellmOpError;
/** Cohere Proxy Route [Docs](https://docs.litellm.ai/docs/pass_through/cohere) */
export const getCohereProxyRouteCohereEndpoint: API.OperationMethod<
  GetCohereProxyRouteCohereEndpointRequest,
  GetCohereProxyRouteCohereEndpointResponse,
  GetCohereProxyRouteCohereEndpointError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetCohereProxyRouteCohereEndpointRequest,
  output: GetCohereProxyRouteCohereEndpointResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type PatchCohereProxyRouteCohereEndpointError =
  | UnprocessableEntity
  | LitellmOpError;
/** Cohere Proxy Route [Docs](https://docs.litellm.ai/docs/pass_through/cohere) */
export const patchCohereProxyRouteCohereEndpoint: API.OperationMethod<
  PatchCohereProxyRouteCohereEndpointRequest,
  PatchCohereProxyRouteCohereEndpointResponse,
  PatchCohereProxyRouteCohereEndpointError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PatchCohereProxyRouteCohereEndpointRequest,
  output: PatchCohereProxyRouteCohereEndpointResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type PostCohereProxyRouteCohereEndpointError =
  | UnprocessableEntity
  | LitellmOpError;
/** Cohere Proxy Route [Docs](https://docs.litellm.ai/docs/pass_through/cohere) */
export const postCohereProxyRouteCohereEndpoint: API.OperationMethod<
  PostCohereProxyRouteCohereEndpointRequest,
  PostCohereProxyRouteCohereEndpointResponse,
  PostCohereProxyRouteCohereEndpointError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PostCohereProxyRouteCohereEndpointRequest,
  output: PostCohereProxyRouteCohereEndpointResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type PutCohereProxyRouteCohereEndpointError =
  | UnprocessableEntity
  | LitellmOpError;
/** Cohere Proxy Route [Docs](https://docs.litellm.ai/docs/pass_through/cohere) */
export const putCohereProxyRouteCohereEndpoint: API.OperationMethod<
  PutCohereProxyRouteCohereEndpointRequest,
  PutCohereProxyRouteCohereEndpointResponse,
  PutCohereProxyRouteCohereEndpointError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PutCohereProxyRouteCohereEndpointRequest,
  output: PutCohereProxyRouteCohereEndpointResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));
