// AUTO-GENERATED by scripts/generate.ts from .generated-specs (pinned litellm-openapi @ 1.100.0 — see README). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
import * as T from "../traits.ts";
import {
  LitellmProtocol,
  type LitellmOpError,
  type LitellmOpContext,
} from "../protocol.ts";
import * as Retry from "../retry.ts";

export type { LitellmOpError, LitellmOpContext };

export class UnprocessableEntity
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<UnprocessableEntity>()("UnprocessableEntity", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 422 }],
  ) {}

export type PostCheckEuAiActComplianceComplianceEuAiActRequestGuardrailInformationItemMap =
  { [key: string]: unknown | undefined };
export const PostCheckEuAiActComplianceComplianceEuAiActRequestGuardrailInformationItemMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.Unknown,
  ) as any as S.Schema<PostCheckEuAiActComplianceComplianceEuAiActRequestGuardrailInformationItemMap>;

export type PostCheckEuAiActComplianceComplianceEuAiActRequestGuardrailInformationList =
  Array<PostCheckEuAiActComplianceComplianceEuAiActRequestGuardrailInformationItemMap>;
export const PostCheckEuAiActComplianceComplianceEuAiActRequestGuardrailInformationList =
  /*@__PURE__*/ S.Array(
    PostCheckEuAiActComplianceComplianceEuAiActRequestGuardrailInformationItemMap,
  ) as any as S.Schema<PostCheckEuAiActComplianceComplianceEuAiActRequestGuardrailInformationList>;

export interface PostCheckEuAiActComplianceComplianceEuAiActRequest {
  guardrail_information?: PostCheckEuAiActComplianceComplianceEuAiActRequestGuardrailInformationList | null;
  model?: string | null;
  request_id: string;
  timestamp?: string | null;
  user_id?: string | null;
}
export const PostCheckEuAiActComplianceComplianceEuAiActRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      guardrail_information: S.optional(
        S.NullOr(
          PostCheckEuAiActComplianceComplianceEuAiActRequestGuardrailInformationList,
        ),
      ),
      model: S.optional(S.NullOr(S.String)),
      request_id: S.String,
      timestamp: S.optional(S.NullOr(S.String)),
      user_id: S.optional(S.NullOr(S.String)),
    }).pipe(
      T.Http({ method: "POST", uri: "/compliance/eu-ai-act", code: 200 }),
    ),
  ).annotate({
    identifier: "PostCheckEuAiActComplianceComplianceEuAiActRequest",
  }) as any as S.Schema<PostCheckEuAiActComplianceComplianceEuAiActRequest>;

/** Result of a single compliance check. */
export interface ComplianceCheckResult {
  article: string;
  check_name: string;
  detail: string;
  passed: boolean;
}
export const ComplianceCheckResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    article: S.String,
    check_name: S.String,
    detail: S.String,
    passed: S.Boolean,
  }),
).annotate({
  identifier: "ComplianceCheckResult",
}) as any as S.Schema<ComplianceCheckResult>;

export type ComplianceResponseChecksList = Array<ComplianceCheckResult>;
export const ComplianceResponseChecksList = /*@__PURE__*/ S.Array(
  ComplianceCheckResult,
) as any as S.Schema<ComplianceResponseChecksList>;

/** Response from a compliance check endpoint. */
export interface ComplianceResponse {
  checks: ComplianceResponseChecksList;
  compliant: boolean;
  regulation: string;
}
export const ComplianceResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    checks: ComplianceResponseChecksList,
    compliant: S.Boolean,
    regulation: S.String,
  }),
).annotate({
  identifier: "ComplianceResponse",
}) as any as S.Schema<ComplianceResponse>;

export type PostCheckGdprComplianceComplianceGdprRequestGuardrailInformationItemMap =
  { [key: string]: unknown | undefined };
export const PostCheckGdprComplianceComplianceGdprRequestGuardrailInformationItemMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.Unknown,
  ) as any as S.Schema<PostCheckGdprComplianceComplianceGdprRequestGuardrailInformationItemMap>;

export type PostCheckGdprComplianceComplianceGdprRequestGuardrailInformationList =
  Array<PostCheckGdprComplianceComplianceGdprRequestGuardrailInformationItemMap>;
export const PostCheckGdprComplianceComplianceGdprRequestGuardrailInformationList =
  /*@__PURE__*/ S.Array(
    PostCheckGdprComplianceComplianceGdprRequestGuardrailInformationItemMap,
  ) as any as S.Schema<PostCheckGdprComplianceComplianceGdprRequestGuardrailInformationList>;

export interface PostCheckGdprComplianceComplianceGdprRequest {
  guardrail_information?: PostCheckGdprComplianceComplianceGdprRequestGuardrailInformationList | null;
  model?: string | null;
  request_id: string;
  timestamp?: string | null;
  user_id?: string | null;
}
export const PostCheckGdprComplianceComplianceGdprRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      guardrail_information: S.optional(
        S.NullOr(
          PostCheckGdprComplianceComplianceGdprRequestGuardrailInformationList,
        ),
      ),
      model: S.optional(S.NullOr(S.String)),
      request_id: S.String,
      timestamp: S.optional(S.NullOr(S.String)),
      user_id: S.optional(S.NullOr(S.String)),
    }).pipe(T.Http({ method: "POST", uri: "/compliance/gdpr", code: 200 })),
  ).annotate({
    identifier: "PostCheckGdprComplianceComplianceGdprRequest",
  }) as any as S.Schema<PostCheckGdprComplianceComplianceGdprRequest>;

export type PostCheckEuAiActComplianceComplianceEuAiActError =
  | UnprocessableEntity
  | LitellmOpError;
/** Check Eu Ai Act Compliance Check EU AI Act compliance for a spend log entry. Checks: - Art. 9: Guardrails applied (any guardrail) - Art. 5: Content screened before LLM (pre-call guardrails) - Art. 12: Audit record complete (user_id, model, timestamp, guardrail_results) */
export const postCheckEuAiActComplianceComplianceEuAiAct: API.OperationMethod<
  PostCheckEuAiActComplianceComplianceEuAiActRequest,
  ComplianceResponse,
  PostCheckEuAiActComplianceComplianceEuAiActError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PostCheckEuAiActComplianceComplianceEuAiActRequest,
  output: ComplianceResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type PostCheckGdprComplianceComplianceGdprError =
  | UnprocessableEntity
  | LitellmOpError;
/** Check Gdpr Compliance Check GDPR compliance for a spend log entry. Checks: - Art. 32: Data protection applied (pre-call guardrails) - Art. 5(1)(c): Sensitive data protected (masked/blocked or no issues) - Art. 30: Audit record complete (user_id, model, timestamp, guardrail_results) */
export const postCheckGdprComplianceComplianceGdpr: API.OperationMethod<
  PostCheckGdprComplianceComplianceGdprRequest,
  ComplianceResponse,
  PostCheckGdprComplianceComplianceGdprError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PostCheckGdprComplianceComplianceGdprRequest,
  output: ComplianceResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));
