// AUTO-GENERATED by scripts/generate.ts from .generated-specs (pinned litellm-openapi @ 1.100.0 — see README). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
import * as T from "../traits.ts";
import {
  LitellmProtocol,
  type LitellmOpError,
  type LitellmOpContext,
} from "../protocol.ts";
import * as Retry from "../retry.ts";

export type { LitellmOpError, LitellmOpContext };

export class UnprocessableEntity
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<UnprocessableEntity>()("UnprocessableEntity", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 422 }],
  ) {}

export interface DeleteCallbackConfigCallbackDeletePostRequest {
  callback_name: string;
}
export const DeleteCallbackConfigCallbackDeletePostRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      callback_name: S.String,
    }).pipe(
      T.Http({ method: "POST", uri: "/config/callback/delete", code: 200 }),
    ),
  ).annotate({
    identifier: "DeleteCallbackConfigCallbackDeletePostRequest",
  }) as any as S.Schema<DeleteCallbackConfigCallbackDeletePostRequest>;

export interface DeleteCallbackConfigCallbackDeletePostResponse {
  body: unknown;
}
export const DeleteCallbackConfigCallbackDeletePostResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "DeleteCallbackConfigCallbackDeletePostResponse",
  }) as any as S.Schema<DeleteCallbackConfigCallbackDeletePostResponse>;

export interface DeleteConfigGeneralSettingsConfigFieldDeletePostRequest {
  config_type: string;
  field_name: string;
}
export const DeleteConfigGeneralSettingsConfigFieldDeletePostRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      config_type: S.String,
      field_name: S.String,
    }).pipe(T.Http({ method: "POST", uri: "/config/field/delete", code: 200 })),
  ).annotate({
    identifier: "DeleteConfigGeneralSettingsConfigFieldDeletePostRequest",
  }) as any as S.Schema<DeleteConfigGeneralSettingsConfigFieldDeletePostRequest>;

export interface DeleteConfigGeneralSettingsConfigFieldDeletePostResponse {
  body: unknown;
}
export const DeleteConfigGeneralSettingsConfigFieldDeletePostResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "DeleteConfigGeneralSettingsConfigFieldDeletePostResponse",
  }) as any as S.Schema<DeleteConfigGeneralSettingsConfigFieldDeletePostResponse>;

export interface GetConfigGeneralSettingsConfigFieldInfoGetRequest {
  field_name: string;
}
export const GetConfigGeneralSettingsConfigFieldInfoGetRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      field_name: S.String.pipe(T.Query()),
    }).pipe(T.Http({ method: "GET", uri: "/config/field/info", code: 200 })),
  ).annotate({
    identifier: "GetConfigGeneralSettingsConfigFieldInfoGetRequest",
  }) as any as S.Schema<GetConfigGeneralSettingsConfigFieldInfoGetRequest>;

export interface ConfigFieldInfo {
  field_name: string;
  field_value: unknown;
}
export const ConfigFieldInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    field_name: S.String,
    field_value: S.Unknown,
  }),
).annotate({
  identifier: "ConfigFieldInfo",
}) as any as S.Schema<ConfigFieldInfo>;

export interface GetConfigGetConfigCallbacksGetRequest {}
export const GetConfigGetConfigCallbacksGetRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({}).pipe(
      T.Http({ method: "GET", uri: "/get/config/callbacks", code: 200 }),
    ),
).annotate({
  identifier: "GetConfigGetConfigCallbacksGetRequest",
}) as any as S.Schema<GetConfigGetConfigCallbacksGetRequest>;

export interface GetConfigGetConfigCallbacksGetResponse {
  body: unknown;
}
export const GetConfigGetConfigCallbacksGetResponse = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      body: S.Unknown,
    }),
).annotate({
  identifier: "GetConfigGetConfigCallbacksGetResponse",
}) as any as S.Schema<GetConfigGetConfigCallbacksGetResponse>;

export interface GetConfigListConfigListGetRequest {
  config_type: string;
}
export const GetConfigListConfigListGetRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    config_type: S.String.pipe(T.Query()),
  }).pipe(T.Http({ method: "GET", uri: "/config/list", code: 200 })),
).annotate({
  identifier: "GetConfigListConfigListGetRequest",
}) as any as S.Schema<GetConfigListConfigListGetRequest>;

export type ConfigListFieldOptionsList = Array<string>;
export const ConfigListFieldOptionsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<ConfigListFieldOptionsList>;

export interface FieldDetail {
  field_default_value?: unknown;
  field_description: string;
  field_name: string;
  field_type: string;
  stored_in_db: boolean | null;
}
export const FieldDetail = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    field_default_value: S.optional(S.Unknown),
    field_description: S.String,
    field_name: S.String,
    field_type: S.String,
    stored_in_db: S.NullOr(S.Boolean),
  }),
).annotate({ identifier: "FieldDetail" }) as any as S.Schema<FieldDetail>;

export type ConfigListNestedFieldsList = Array<FieldDetail>;
export const ConfigListNestedFieldsList = /*@__PURE__*/ S.Array(
  FieldDetail,
) as any as S.Schema<ConfigListNestedFieldsList>;

export interface ConfigList {
  field_default_value: unknown;
  field_description: string;
  field_name: string;
  field_options?: ConfigListFieldOptionsList | null;
  field_tab?: string | null;
  field_type: string;
  field_value: unknown;
  nested_fields?: ConfigListNestedFieldsList | null;
  premium_field?: boolean;
  stored_in_db: boolean | null;
}
export const ConfigList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    field_default_value: S.Unknown,
    field_description: S.String,
    field_name: S.String,
    field_options: S.optional(S.NullOr(ConfigListFieldOptionsList)),
    field_tab: S.optional(S.NullOr(S.String)),
    field_type: S.String,
    field_value: S.Unknown,
    nested_fields: S.optional(S.NullOr(ConfigListNestedFieldsList)),
    premium_field: S.optional(S.Boolean),
    stored_in_db: S.NullOr(S.Boolean),
  }),
).annotate({ identifier: "ConfigList" }) as any as S.Schema<ConfigList>;

export type GetConfigListConfigListGetResponseBodyList = Array<ConfigList>;
export const GetConfigListConfigListGetResponseBodyList = /*@__PURE__*/ S.Array(
  ConfigList,
) as any as S.Schema<GetConfigListConfigListGetResponseBodyList>;

export interface GetConfigListConfigListGetResponse {
  body: GetConfigListConfigListGetResponseBodyList;
}
export const GetConfigListConfigListGetResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    body: GetConfigListConfigListGetResponseBodyList,
  }),
).annotate({
  identifier: "GetConfigListConfigListGetResponse",
}) as any as S.Schema<GetConfigListConfigListGetResponse>;

export type GetConfigYamlEndpointConfigYamlRequestEnvironmentVariablesMap = {
  [key: string]: unknown | undefined;
};
export const GetConfigYamlEndpointConfigYamlRequestEnvironmentVariablesMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.Unknown,
  ) as any as S.Schema<GetConfigYamlEndpointConfigYamlRequestEnvironmentVariablesMap>;

export type ConfigGeneralSettingsAlertToWebhookUrlMap = {
  [key: string]: unknown | undefined;
};
export const ConfigGeneralSettingsAlertToWebhookUrlMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<ConfigGeneralSettingsAlertToWebhookUrlMap>;

/** Enum for alert types and management event types */
export type AlertType =
  | "llm_exceptions"
  | "llm_too_slow"
  | "llm_requests_hanging"
  | "budget_alerts"
  | "spend_reports"
  | "failed_tracking_spend"
  | "db_exceptions"
  | "daily_reports"
  | "cooldown_deployment"
  | "new_model_added"
  | "model_deprecation_warnings"
  | "outage_alerts"
  | "region_outage_alerts"
  | "fallback_reports"
  | "new_virtual_key_created"
  | "virtual_key_updated"
  | "virtual_key_deleted"
  | "new_team_created"
  | "team_updated"
  | "team_deleted"
  | "new_internal_user_created"
  | "internal_user_updated"
  | "internal_user_deleted";
export const AlertType = S.String;

export type ConfigGeneralSettingsAlertTypesList = Array<
  AlertType | (string & {})
>;
export const ConfigGeneralSettingsAlertTypesList = /*@__PURE__*/ S.Array(
  AlertType,
) as any as S.Schema<ConfigGeneralSettingsAlertTypesList>;

export type ConfigGeneralSettingsAlertingList = Array<unknown>;
export const ConfigGeneralSettingsAlertingList = /*@__PURE__*/ S.Array(
  S.Unknown,
) as any as S.Schema<ConfigGeneralSettingsAlertingList>;

export type ConfigGeneralSettingsAlertingArgsMap = {
  [key: string]: unknown | undefined;
};
export const ConfigGeneralSettingsAlertingArgsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<ConfigGeneralSettingsAlertingArgsMap>;

export type ConfigGeneralSettingsAllowedRoutesList = Array<unknown>;
export const ConfigGeneralSettingsAllowedRoutesList = /*@__PURE__*/ S.Array(
  S.Unknown,
) as any as S.Schema<ConfigGeneralSettingsAllowedRoutesList>;

export type ConfigGeneralSettingsBackgroundHealthCheckModelGroupsList =
  Array<string>;
export const ConfigGeneralSettingsBackgroundHealthCheckModelGroupsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<ConfigGeneralSettingsBackgroundHealthCheckModelGroupsList>;

export type CoordinationRedisParamsSentinelNodesItemItem = string | number;
export const CoordinationRedisParamsSentinelNodesItemItem =
  S.Unknown as any as S.Schema<CoordinationRedisParamsSentinelNodesItemItem>;

export type CoordinationRedisParamsSentinelNodesItemList =
  Array<CoordinationRedisParamsSentinelNodesItemItem>;
export const CoordinationRedisParamsSentinelNodesItemList =
  /*@__PURE__*/ S.Array(
    CoordinationRedisParamsSentinelNodesItemItem,
  ) as any as S.Schema<CoordinationRedisParamsSentinelNodesItemList>;

export type CoordinationRedisParamsSentinelNodesList =
  Array<CoordinationRedisParamsSentinelNodesItemList>;
export const CoordinationRedisParamsSentinelNodesList = /*@__PURE__*/ S.Array(
  CoordinationRedisParamsSentinelNodesItemList,
) as any as S.Schema<CoordinationRedisParamsSentinelNodesList>;

/** A single startup node of a cluster-mode Redis used for proxy coordination. */
export interface CoordinationRedisNode {
  /** hostname of the cluster node */
  host: string;
  /** port of the cluster node */
  port: number;
}
export const CoordinationRedisNode = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    host: S.String,
    port: S.Number,
  }),
).annotate({
  identifier: "CoordinationRedisNode",
}) as any as S.Schema<CoordinationRedisNode>;

export type CoordinationRedisParamsStartupNodesList =
  Array<CoordinationRedisNode>;
export const CoordinationRedisParamsStartupNodesList = /*@__PURE__*/ S.Array(
  CoordinationRedisNode,
) as any as S.Schema<CoordinationRedisParamsStartupNodesList>;

/** Connection params for the proxy's coordination Redis (cross-pod tpm/rpm rate limits, spend tracking, pod lock manager, shared health checks), configured independently of the response-cache backend in `litellm_settings.cache_params`. */
export interface CoordinationRedisParams {
  /** Redis hostname */
  host?: string | null;
  /** Redis password */
  password?: string | null;
  /** Redis port */
  port?: number | null;
  /** sentinel [host, port] pairs; when set a sentinel-managed client is used */
  sentinel_nodes?: CoordinationRedisParamsSentinelNodesList | null;
  /** password for the sentinel nodes */
  sentinel_password?: string | null;
  /** sentinel service name */
  service_name?: string | null;
  /** connect over TLS */
  ssl?: boolean | null;
  /** cluster-mode startup nodes; when set a cluster client is used */
  startup_nodes?: CoordinationRedisParamsStartupNodesList | null;
  /** full Redis connection url, e.g. redis://:pass@host:6379 */
  url?: string | null;
  /** Redis username */
  username?: string | null;
}
export const CoordinationRedisParams = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    host: S.optional(S.NullOr(S.String)),
    password: S.optional(S.NullOr(S.String)),
    port: S.optional(S.NullOr(S.Number)),
    sentinel_nodes: S.optional(
      S.NullOr(CoordinationRedisParamsSentinelNodesList),
    ),
    sentinel_password: S.optional(S.NullOr(S.String)),
    service_name: S.optional(S.NullOr(S.String)),
    ssl: S.optional(S.NullOr(S.Boolean)),
    startup_nodes: S.optional(
      S.NullOr(CoordinationRedisParamsStartupNodesList),
    ),
    url: S.optional(S.NullOr(S.String)),
    username: S.optional(S.NullOr(S.String)),
  }),
).annotate({
  identifier: "CoordinationRedisParams",
}) as any as S.Schema<CoordinationRedisParams>;

export type DynamoDBArgsAwsPolicyArnsList = Array<string>;
export const DynamoDBArgsAwsPolicyArnsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<DynamoDBArgsAwsPolicyArnsList>;

export type DynamoDBArgsBillingMode =
  | "PROVISIONED_THROUGHPUT"
  | "PAY_PER_REQUEST";
export const DynamoDBArgsBillingMode = S.String;

export interface DynamoDBArgs {
  assume_role_aws_role_name?: string | null;
  assume_role_aws_session_name?: string | null;
  aws_duration_seconds?: number | null;
  aws_policy?: string | null;
  aws_policy_arns?: DynamoDBArgsAwsPolicyArnsList | null;
  aws_provider_id?: string | null;
  aws_role_name?: string | null;
  aws_session_name?: string | null;
  aws_web_identity_token?: string | null;
  billing_mode: DynamoDBArgsBillingMode | (string & {});
  config_table_name?: string;
  key_table_name?: string;
  read_capacity_units?: number | null;
  region_name: string;
  spend_table_name?: string;
  ssl_verify?: boolean | null;
  user_table_name?: string;
  write_capacity_units?: number | null;
}
export const DynamoDBArgs = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    assume_role_aws_role_name: S.optional(S.NullOr(S.String)),
    assume_role_aws_session_name: S.optional(S.NullOr(S.String)),
    aws_duration_seconds: S.optional(S.NullOr(S.Number)),
    aws_policy: S.optional(S.NullOr(S.String)),
    aws_policy_arns: S.optional(S.NullOr(DynamoDBArgsAwsPolicyArnsList)),
    aws_provider_id: S.optional(S.NullOr(S.String)),
    aws_role_name: S.optional(S.NullOr(S.String)),
    aws_session_name: S.optional(S.NullOr(S.String)),
    aws_web_identity_token: S.optional(S.NullOr(S.String)),
    billing_mode: DynamoDBArgsBillingMode,
    config_table_name: S.optional(S.String),
    key_table_name: S.optional(S.String),
    read_capacity_units: S.optional(S.NullOr(S.Number)),
    region_name: S.String,
    spend_table_name: S.optional(S.String),
    ssl_verify: S.optional(S.NullOr(S.Boolean)),
    user_table_name: S.optional(S.String),
    write_capacity_units: S.optional(S.NullOr(S.Number)),
  }),
).annotate({ identifier: "DynamoDBArgs" }) as any as S.Schema<DynamoDBArgs>;

export type ConfigGeneralSettingsDatabaseExtraConnectionParamsMap = {
  [key: string]: unknown | undefined;
};
export const ConfigGeneralSettingsDatabaseExtraConnectionParamsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.Unknown,
  ) as any as S.Schema<ConfigGeneralSettingsDatabaseExtraConnectionParamsMap>;

export type KeyManagementSystem =
  | "google_kms"
  | "azure_key_vault"
  | "aws_secret_manager"
  | "google_secret_manager"
  | "hashicorp_vault"
  | "cyberark"
  | "local"
  | "aws_kms"
  | "custom";
export const KeyManagementSystem = S.String;

export type ConfigGeneralSettingsMcpInternalIpRangesList = Array<string>;
export const ConfigGeneralSettingsMcpInternalIpRangesList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<ConfigGeneralSettingsMcpInternalIpRangesList>;

export type ConfigGeneralSettingsMcpRequiredFieldsList = Array<string>;
export const ConfigGeneralSettingsMcpRequiredFieldsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<ConfigGeneralSettingsMcpRequiredFieldsList>;

export type ConfigGeneralSettingsMcpTrustedProxyRangesList = Array<string>;
export const ConfigGeneralSettingsMcpTrustedProxyRangesList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<ConfigGeneralSettingsMcpTrustedProxyRangesList>;

/** Key-value pairs of default query parameters to be sent with every request to this endpoint. These can be overridden by client-provided query parameters. For example: {'key': 'default_value', 'api_version': '2023-01'} */
export type PassThroughGenericEndpointDefaultQueryParamsMap = {
  [key: string]: unknown | undefined;
};
export const PassThroughGenericEndpointDefaultQueryParamsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.Unknown,
  ) as any as S.Schema<PassThroughGenericEndpointDefaultQueryParamsMap>;

export type PassThroughGuardrailSettingsRequestFieldsList = Array<string>;
export const PassThroughGuardrailSettingsRequestFieldsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<PassThroughGuardrailSettingsRequestFieldsList>;

export type PassThroughGuardrailSettingsResponseFieldsList = Array<string>;
export const PassThroughGuardrailSettingsResponseFieldsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<PassThroughGuardrailSettingsResponseFieldsList>;

/** Settings for a specific guardrail on a passthrough endpoint. Allows field-level targeting for guardrail execution. */
export interface PassThroughGuardrailSettings {
  /** JSONPath expressions for input field targeting (pre_call). Examples: 'query', 'documents[*].text', 'messages[*].content'. If not specified, guardrail runs on entire request payload. */
  request_fields?: PassThroughGuardrailSettingsRequestFieldsList | null;
  /** JSONPath expressions for output field targeting (post_call). Examples: 'results[*].text', 'output'. If not specified, guardrail runs on entire response payload. */
  response_fields?: PassThroughGuardrailSettingsResponseFieldsList | null;
}
export const PassThroughGuardrailSettings = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    request_fields: S.optional(
      S.NullOr(PassThroughGuardrailSettingsRequestFieldsList),
    ),
    response_fields: S.optional(
      S.NullOr(PassThroughGuardrailSettingsResponseFieldsList),
    ),
  }),
).annotate({
  identifier: "PassThroughGuardrailSettings",
}) as any as S.Schema<PassThroughGuardrailSettings>;

export type PassThroughGenericEndpointGuardrailsMap = {
  [key: string]: PassThroughGuardrailSettings | null | undefined;
};
export const PassThroughGenericEndpointGuardrailsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.NullOr(PassThroughGuardrailSettings),
) as any as S.Schema<PassThroughGenericEndpointGuardrailsMap>;

/** Key-value pairs of headers to be forwarded with the request. You can set any key value pair here and it will be forwarded to your target endpoint */
export type PassThroughGenericEndpointHeadersMap = {
  [key: string]: unknown | undefined;
};
export const PassThroughGenericEndpointHeadersMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<PassThroughGenericEndpointHeadersMap>;

export type PassThroughGenericEndpointMethodsList = Array<string>;
export const PassThroughGenericEndpointMethodsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<PassThroughGenericEndpointMethodsList>;

export interface PassThroughGenericEndpoint {
  /** Whether authentication is required for the pass-through endpoint. Defaults to True so a pass-through silently created without an explicit value still requires a valid LiteLLM API key — set to False only if the endpoint is meant to be a public forwarder (e.g. an unauthenticated webhook target). */
  auth?: boolean;
  /** The USD cost per request to the target endpoint. This is used to calculate the cost of the request to the target endpoint. */
  cost_per_request?: number;
  /** Key-value pairs of default query parameters to be sent with every request to this endpoint. These can be overridden by client-provided query parameters. For example: {'key': 'default_value', 'api_version': '2023-01'} */
  default_query_params?: PassThroughGenericEndpointDefaultQueryParamsMap;
  /** Guardrails configuration for this passthrough endpoint. Dict keys are guardrail names, values are optional settings for field targeting. When set, all org/team/key level guardrails will also execute. Defaults to None (no guardrails execute). */
  guardrails?: PassThroughGenericEndpointGuardrailsMap | null;
  /** Key-value pairs of headers to be forwarded with the request. You can set any key value pair here and it will be forwarded to your target endpoint */
  headers?: PassThroughGenericEndpointHeadersMap;
  /** Optional unique identifier for the pass-through endpoint. If not provided, endpoints will be identified by path for backwards compatibility. */
  id?: string | null;
  /** If True, requests to subpaths of the path will be forwarded to the target endpoint. For example, if the path is /bria and include_subpath is True, requests to /bria/v1/text-to-image/base/2.3 will be forwarded to the target endpoint. */
  include_subpath?: boolean;
  /** True if this endpoint is defined in the config file, False if from DB. Config-defined endpoints cannot be edited via the UI. */
  is_from_config?: boolean;
  /** List of HTTP methods this endpoint handles (e.g., ['GET', 'POST']). If None or empty, all methods (GET, POST, PUT, DELETE, PATCH) are supported for backward compatibility. This allows the same path to have different targets for different HTTP methods. */
  methods?: PassThroughGenericEndpointMethodsList | null;
  /** The route to be added to the LiteLLM Proxy Server. */
  path: string;
  /** The URL to which requests for this path should be forwarded. */
  target: string;
  /** Upstream request timeout in seconds for this pass-through endpoint. If unset, uses general_settings.pass_through_request_timeout (default 600). */
  timeout?: number | null;
}
export const PassThroughGenericEndpoint = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    auth: S.optional(S.Boolean),
    cost_per_request: S.optional(S.Number),
    default_query_params: S.optional(
      PassThroughGenericEndpointDefaultQueryParamsMap,
    ),
    guardrails: S.optional(S.NullOr(PassThroughGenericEndpointGuardrailsMap)),
    headers: S.optional(PassThroughGenericEndpointHeadersMap),
    id: S.optional(S.NullOr(S.String)),
    include_subpath: S.optional(S.Boolean),
    is_from_config: S.optional(S.Boolean),
    methods: S.optional(S.NullOr(PassThroughGenericEndpointMethodsList)),
    path: S.String,
    target: S.String,
    timeout: S.optional(S.NullOr(S.Number)),
  }),
).annotate({
  identifier: "PassThroughGenericEndpoint",
}) as any as S.Schema<PassThroughGenericEndpoint>;

export type ConfigGeneralSettingsPassThroughEndpointsList =
  Array<PassThroughGenericEndpoint>;
export const ConfigGeneralSettingsPassThroughEndpointsList =
  /*@__PURE__*/ S.Array(
    PassThroughGenericEndpoint,
  ) as any as S.Schema<ConfigGeneralSettingsPassThroughEndpointsList>;

/** A single external service registered as an embeddable UI plugin. */
export interface PluginConfig {
  /** human-readable label shown in the UI view switcher */
  display_name?: string | null;
  /** unique plugin identifier (kebab-case) */
  name: string;
  /** plugin's own credential, injected as Bearer auth only on /plugin-proxy/<name>/* reverse-proxy calls */
  plugin_key?: string | null;
  /** base URL of the plugin service */
  url: string;
}
export const PluginConfig = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    display_name: S.optional(S.NullOr(S.String)),
    name: S.String,
    plugin_key: S.optional(S.NullOr(S.String)),
    url: S.String,
  }),
).annotate({ identifier: "PluginConfig" }) as any as S.Schema<PluginConfig>;

export type ConfigGeneralSettingsPluginsList = Array<PluginConfig>;
export const ConfigGeneralSettingsPluginsList = /*@__PURE__*/ S.Array(
  PluginConfig,
) as any as S.Schema<ConfigGeneralSettingsPluginsList>;

export type ConfigGeneralSettingsProviderUrlDestinationAllowedHostsList =
  Array<string>;
export const ConfigGeneralSettingsProviderUrlDestinationAllowedHostsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<ConfigGeneralSettingsProviderUrlDestinationAllowedHostsList>;

/** explicit offset in seconds per scheduler job id, overriding the derived value. 0 pins a job to its unshifted schedule */
export type ScheduledJobStaggerSettingsOffsetsMap = {
  [key: string]: number | undefined;
};
export const ScheduledJobStaggerSettingsOffsetsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Number,
) as any as S.Schema<ScheduledJobStaggerSettingsOffsetsMap>;

/** Spreads the proxy's scheduled background jobs across a window instead of firing them all on one instant, on every replica, forever. */
export interface ScheduledJobStaggerSettings {
  /** apply deterministic phase offsets to scheduled background jobs */
  enabled?: boolean;
  /** replaces the POD_NAME/HOSTNAME-derived component of the offset hash. Set this when replicas share a hostname and would otherwise land on the same offset */
  identity?: string | null;
  /** explicit offset in seconds per scheduler job id, overriding the derived value. 0 pins a job to its unshifted schedule */
  offsets?: ScheduledJobStaggerSettingsOffsetsMap;
  /** width of the window jobs are spread over. An interval job is never offset by more than one of its own periods, so it is not delayed past the wait it already has */
  window_seconds?: number;
}
export const ScheduledJobStaggerSettings = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    enabled: S.optional(S.Boolean),
    identity: S.optional(S.NullOr(S.String)),
    offsets: S.optional(ScheduledJobStaggerSettingsOffsetsMap),
    window_seconds: S.optional(S.Number),
  }),
).annotate({
  identifier: "ScheduledJobStaggerSettings",
}) as any as S.Schema<ScheduledJobStaggerSettings>;

/** Supported database object types for fine-grained DB storage control. Use in general_settings.supported_db_objects to specify which objects to load from DB. */
export type SupportedDBObjectType =
  | "models"
  | "mcp"
  | "guardrails"
  | "policies"
  | "vector_stores"
  | "pass_through_endpoints"
  | "prompts"
  | "model_cost_map"
  | "tools"
  | "config_overrides";
export const SupportedDBObjectType = S.String;

export type ConfigGeneralSettingsSupportedDbObjectsList = Array<
  SupportedDBObjectType | (string & {})
>;
export const ConfigGeneralSettingsSupportedDbObjectsList =
  /*@__PURE__*/ S.Array(
    SupportedDBObjectType,
  ) as any as S.Schema<ConfigGeneralSettingsSupportedDbObjectsList>;

export type ConfigGeneralSettingsTrustedProxyRangesList = Array<string>;
export const ConfigGeneralSettingsTrustedProxyRangesList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<ConfigGeneralSettingsTrustedProxyRangesList>;

export type ConfigGeneralSettingsUiAccessMode = "admin_only" | "all";
export const ConfigGeneralSettingsUiAccessMode = S.String;

export type UserHeaderMappingLitellmUserRole = "internal_user" | "customer";
export const UserHeaderMappingLitellmUserRole = S.String;

/** Map an incoming HTTP header to a LiteLLM user role. */
export interface UserHeaderMapping {
  header_name: string;
  litellm_user_role: UserHeaderMappingLitellmUserRole | (string & {});
}
export const UserHeaderMapping = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    header_name: S.String,
    litellm_user_role: UserHeaderMappingLitellmUserRole,
  }),
).annotate({
  identifier: "UserHeaderMapping",
}) as any as S.Schema<UserHeaderMapping>;

export type ConfigGeneralSettingsUserHeaderMappingsList =
  Array<UserHeaderMapping>;
export const ConfigGeneralSettingsUserHeaderMappingsList =
  /*@__PURE__*/ S.Array(
    UserHeaderMapping,
  ) as any as S.Schema<ConfigGeneralSettingsUserHeaderMappingsList>;

export type ConfigGeneralSettingsUserMcpManagementMode =
  | "restricted"
  | "view_all";
export const ConfigGeneralSettingsUserMcpManagementMode = S.String;

export type ConfigGeneralSettingsUserUrlAllowedHostsList = Array<string>;
export const ConfigGeneralSettingsUserUrlAllowedHostsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<ConfigGeneralSettingsUserUrlAllowedHostsList>;

/** Documents all the fields supported by `general_settings` in config.yaml */
export interface ConfigGeneralSettings {
  /** Mapping of alert type to webhook url. e.g. `alert_to_webhook_url: {'budget_alerts': 'https://nothooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'}` */
  alert_to_webhook_url?: ConfigGeneralSettingsAlertToWebhookUrlMap | null;
  /** List of alerting types. By default it is all alerts */
  alert_types?: ConfigGeneralSettingsAlertTypesList | null;
  /** List of alerting integrations. Today, just slack - `alerting: ['slack']` */
  alerting?: ConfigGeneralSettingsAlertingList | null;
  /** Controllable params for slack alerting - e.g. ttl in cache. */
  alerting_args?: ConfigGeneralSettingsAlertingArgsMap | null;
  /** sends alerts if requests hang for 5min+ */
  alerting_threshold?: number | null;
  /** opt-in to RFC 8628 verification_uri_complete for the CLI SSO device flow, pre-filling the user_code in the browser. Off by default; intended for same-host clients where the device that starts the flow and the browser run on the same machine */
  allow_cli_sso_verification_uri_complete?: boolean | null;
  /** Proxy API Endpoints you want users to be able to access */
  allowed_routes?: ConfigGeneralSettingsAllowedRoutesList | null;
  /** If True, a user's personal max_budget is enforced on every request they make, including requests made with a team-scoped key. Defaults to False, where a team-scoped key is governed only by the team and team-member budgets and the key owner's personal max_budget does not apply (see GitHub issue #12905). */
  apply_user_budget_to_team_keys?: boolean | null;
  /** Opt-in allowlist of model group names for background health checks and health-check routing. When set, the background loop probes only deployments whose model_name is listed, and enable_health_check_routing filters unhealthy deployments only within the listed groups; every other group, including newly added deployments, is skipped and keeps its configured routing strategy. When unset, all deployments participate (opt out per deployment via model_info.disable_background_health_check). */
  background_health_check_model_groups?: ConfigGeneralSettingsBackgroundHealthCheckModelGroupsList | null;
  /** run health checks in background */
  background_health_checks?: boolean | null;
  /** cancel the in-flight upstream LLM request (non-streaming) when the client disconnects, freeing backend capacity (e.g. a vLLM GPU slot); the request is logged as a 499 failure */
  cancel_on_disconnect?: boolean | null;
  /** proxy level default model for all chat completion calls */
  completion_model?: string | null;
  /** Global Control Plane: URL of the control plane whose admin UI manages this instance. Enables /v3/login and /v3/login/exchange on this instance so that UI can authenticate against it cross-origin, and restricts the SSO return_to origin to that URL. No state is shared with the control plane */
  control_plane_url?: string | null;
  /** standalone Redis for cross-pod coordination (tpm/rpm rate limits, spend tracking, pod lock manager, shared health checks), configured independently of the response-cache backend; takes precedence over borrowing the `cache_params` Redis and over the REDIS_* env fallback */
  coordination_redis?: CoordinationRedisParams | null;
  /** override user_api_key_auth with your own auth script - https://docs.litellm.ai/docs/proxy/virtual_keys#custom-auth */
  custom_auth?: string | null;
  /** custom args for instantiating dynamodb client - e.g. billing provision */
  database_args?: DynamoDBArgs | null;
  /** Prisma `connect_timeout` URL param (seconds). Bounds how long the engine waits to establish a new connection before failing. Defaults to Prisma's built-in value when unset. */
  database_connect_timeout?: number | null;
  /** default connection pool for prisma client connecting to postgres db */
  database_connection_pool_limit?: number | null;
  /** default timeout for a connection to the database */
  database_connection_timeout?: number | null;
  /** Disable server-side prepared statements by setting Prisma's `pgbouncer=true` URL param. Use this for pgbouncer transaction-pooling deployments, or to prevent the 'cached plan must not change result type' error that pooled connections hit during rolling schema migrations. An explicit `pgbouncer` in `database_extra_connection_params` takes precedence. */
  database_disable_prepared_statements?: boolean | null;
  /** Escape hatch: extra key/value pairs appended verbatim to the Prisma DATABASE_URL / DIRECT_URL query string (e.g. `sslmode`, `pgbouncer`, `statement_cache_size`). Keys here override any default LiteLLM sets. */
  database_extra_connection_params?: ConfigGeneralSettingsDatabaseExtraConnectionParamsMap | null;
  /** Prisma `socket_timeout` URL param (seconds). When set, an idle/slow connection that has not produced data within this window is closed. This is the main knob for capping idle DB connections from LiteLLM. */
  database_socket_timeout?: number | null;
  /** to use dynamodb instead of postgres db */
  database_type?: string | null;
  /** connect to a postgres db - needed for generating temporary keys + tracking spend / key */
  database_url?: string | null;
  /** By default, the user calling /team/new is automatically added to the new team as a team admin. If True, proxy admins are no longer auto-added; members explicitly listed in members_with_roles are unaffected. Default is False. */
  disable_auto_add_proxy_admin_to_teams?: boolean | null;
  /** If True, disables the optimistic per-request budget reservation introduced in v1.84.0. WARNING: This weakens hard budget enforcement. Without the reservation, a burst of concurrent requests from a single key can each pass the read-time spend check before any of them is charged, allowing a configured budget to be exceeded under high concurrency. Budgets are still evaluated on every request at read time, so an already-exhausted budget is still rejected. Enable only if your deployment is experiencing phantom BudgetExceededError responses caused by leaked reservations (see GitHub issue #27639). A proxy-level WARNING is logged on every request while this flag is active as a reminder that hard enforcement is relaxed. */
  disable_budget_reservation?: boolean | null;
  /** Public model hub for users to see what models they have access to, supported openai params, etc. */
  enable_public_model_hub?: boolean;
  /** If True, router fallbacks configured in router_settings are only attempted when the calling key (and its team and project) is allowed to call the fallback model; unauthorized fallback targets are skipped and the primary model's error is returned. Default is False. */
  enforce_fallback_model_access?: boolean | null;
  /** If True, forwards client headers (e.g. Authorization) to the LLM API. Required for Claude Code with Max subscription. */
  forward_client_headers_to_llm_api?: boolean | null;
  /** global max parallel requests to allow for a proxy instance. */
  global_max_parallel_requests?: number | null;
  /** limit concurrent health checks per cycle; when unset, health checks run without a concurrency cap */
  health_check_concurrency?: number | null;
  /** background health check interval in seconds */
  health_check_interval?: number;
  /** When true, deployments with model_info.disable_background_health_check are skipped for on-demand GET /health as well as the background health loop. */
  health_check_skip_disabled_background_models?: boolean;
  /** for `/models` endpoint, infers available model based on environment keys (e.g. OPENAI_API_KEY) */
  infer_model_from_keys?: boolean | null;
  /** key manager to load keys from / decrypt keys with */
  key_management_system?: KeyManagementSystem | (string & {}) | null;
  /** require a key for all calls to proxy */
  master_key?: string | null;
  /** max batch input file size in MB for /v1/files uploads with purpose=batch, if a file is larger than this size it will be rejected before being forwarded to the provider */
  max_batch_file_size_mb?: number | null;
  /** maximum parallel requests for each api key */
  max_parallel_requests?: number | null;
  /** max request size in MB, if a request is larger than this size it will be rejected */
  max_request_size_mb?: number | null;
  /** max response size in MB, if a response is larger than this size it will be rejected */
  max_response_size_mb?: number | null;
  /** Maximum retention period for auto-router benchmark session rollup rows (e.g., '365d'). Rows whose last turn is older than this are deleted by the spend log cleanup job, on that job's schedule. Unset means rollup rows are never deleted. */
  maximum_autorouter_session_retention_period?: string | null;
  /** Maximum retention period for health-check rows (e.g., '30d'). Rows whose checked_at is older than this are deleted by the spend log cleanup job, on that job's schedule. Unset means rows are never deleted. Set this well above health_check_interval because /health and the UI read the latest row per model. */
  maximum_health_check_retention_period?: string | null;
  /** Rows deleted per DELETE statement by the spend log cleanup job. Defaults to 1000. */
  maximum_spend_logs_cleanup_batch_size?: number | null;
  /** Postgres statement_timeout and lock_timeout applied to each spend log cleanup delete batch (e.g. '30s'), so cleanup cannot hold row locks or a connection indefinitely. Defaults to '30s'. */
  maximum_spend_logs_cleanup_batch_timeout?: string | null;
  /** Maximum DELETE statements the spend log cleanup job issues per table per run. Defaults to 500. */
  maximum_spend_logs_cleanup_max_batches?: number | null;
  /** Wall-clock budget for one spend log cleanup run (e.g. '5m'), shared across every table it prunes. A run that hits the budget stops and the next run resumes from where it left off. Defaults to '5m'. */
  maximum_spend_logs_cleanup_run_budget?: string | null;
  /** Maximum retention period for spend logs (e.g., '7d' for 7 days). Logs older than this will be deleted. */
  maximum_spend_logs_retention_period?: string | null;
  /** Custom CIDR ranges that define internal/private networks for MCP access control. When set, only these ranges are treated as internal. Defaults to RFC 1918 private ranges (10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.0/8). */
  mcp_internal_ip_ranges?: ConfigGeneralSettingsMcpInternalIpRangesList | null;
  /** List of MCP server fields that must be filled in for a submission to pass standards checks (e.g. ['description', 'source_url', 'alias']). */
  mcp_required_fields?: ConfigGeneralSettingsMcpRequiredFieldsList | null;
  /** CIDR ranges of trusted reverse proxies. When set, X-Forwarded-For and X-Forwarded-* origin headers are only trusted from these IPs. */
  mcp_trusted_proxy_ranges?: ConfigGeneralSettingsMcpTrustedProxyRangesList | null;
  /** Number of trusted reverse proxies/load balancers in front of the gateway that append to X-Forwarded-For. When set (and mcp_trusted_proxy_ranges validates the direct peer), the client IP for MCP access control is read this many entries from the right of the chain instead of the spoofable leftmost value, defeating append-style X-Forwarded-For forgery. */
  mcp_xff_num_trusted_hops?: number | null;
  /** When true, `/models`, `/v1/models/{id}` and `/model/info` hide models whose backing deployments are all unhealthy, for every caller, without needing `healthy_only=true` per request. Requires `background_health_checks: true`, and keeps deployment health state cached without turning on `enable_health_check_routing`, so routing is unaffected. With no health state nothing is hidden. Hiding is presentation-only, a hidden model can still be called. */
  model_list_healthy_only?: boolean | null;
  /** [BETA] OpenTelemetry support - this might change, use with caution. */
  otel?: boolean | null;
  /** Set-up pass-through endpoints for provider-specific endpoints. Docs - https://docs.litellm.ai/docs/proxy/pass_through */
  pass_through_endpoints?: ConfigGeneralSettingsPassThroughEndpointsList | null;
  /** Default upstream request timeout in seconds for native and custom pass-through endpoints that use pass_through_request. Defaults to 600 when unset. */
  pass_through_request_timeout?: number | null;
  /** external services registered as embeddable UI plugins */
  plugins?: ConfigGeneralSettingsPluginsList | null;
  /** Allowlist of hosts a request may redirect a provider call's destination URL to. */
  provider_url_destination_allowed_hosts?: ConfigGeneralSettingsProviderUrlDestinationAllowedHostsList | null;
  /** how often (in seconds) each pod reloads config-in-DB objects (models, credentials, guardrails, etc.) when store_model_in_db is enabled; lower values speed up multi-pod convergence at the cost of more DB load. Applied on proxy startup */
  proxy_config_reload_interval_seconds?: number;
  /** When set to True, rejects requests that contain client-side 'metadata.tags' to prevent users from influencing budgets by sending different tags. Tags can only be inherited from the API key metadata. */
  reject_clientside_metadata_tags?: boolean | null;
  /** Spreads the proxy's scheduled background jobs (spend flushes, budget resets, config reloads, exports) across a window instead of firing them together on every replica. On by default; set to tune the window, pin a job, or turn it off. */
  scheduled_job_stagger?: ScheduledJobStaggerSettings | null;
  /** If True, models and config are stored in and loaded from the database. Default is False. */
  store_model_in_db?: boolean | null;
  /** If True, stores request messages and responses in spend logs. Default is False. */
  store_prompts_in_spend_logs?: boolean | null;
  /** Fine-grained control over which object types to load from the database when store_model_in_db is True. Available types: 'models', 'mcp', 'guardrails', 'vector_stores', 'pass_through_endpoints', 'prompts', 'model_cost_map', 'tools', 'config_overrides'. If not set, all objects are loaded (default behavior). */
  supported_db_objects?: ConfigGeneralSettingsSupportedDbObjectsList | null;
  /** CIDR ranges of trusted reverse proxies allowed to provide identity headers for header-based auth paths such as enable_oauth2_proxy_auth and custom_ui_sso_sign_in_handler. */
  trusted_proxy_ranges?: ConfigGeneralSettingsTrustedProxyRangesList | null;
  /** Control access to the Proxy UI */
  ui_access_mode?: ConfigGeneralSettingsUiAccessMode | (string & {}) | null;
  /** load keys from azure key vault */
  use_azure_key_vault?: boolean | null;
  /** decrypt keys with google kms */
  use_google_kms?: boolean | null;
  /** If True and LiteLLM_SpendLogs has been converted to a range-partitioned table (db_scripts/partition_spend_logs.sql), retention cleanup drops expired partitions instead of deleting rows, and pre-creates upcoming partitions. Default is False. */
  use_spend_logs_partitioning?: boolean | null;
  user_header_mappings?: ConfigGeneralSettingsUserHeaderMappingsList | null;
  /** [DEPRECATED] Use 'user_header_mappings' instead. When set, the header value is treated as the end user id unless overridden by user_header_mappings. */
  user_header_name?: string | null;
  /** Controls how non-admin users interact with MCP servers in the dashboard. 'restricted' shows only accessible servers, 'view_all' lists every server in read-only mode. */
  user_mcp_management_mode?:
    | ConfigGeneralSettingsUserMcpManagementMode
    | (string & {})
    | null;
  /** SSRF allowlist for user-supplied URLs. Entries are `hostname` or `hostname:port` (bracketed for IPv6, e.g. `[::1]:8080`). Allowlisted hosts skip the blocked-network check in validate_url() but still resolve DNS. Use this to permit legitimate internal targets, e.g. an internal OpenAPI/MCP server. */
  user_url_allowed_hosts?: ConfigGeneralSettingsUserUrlAllowedHostsList | null;
  /** Master switch for the SSRF guard applied to user-supplied URLs (image_url, file_url, MCP/OpenAPI spec URLs, etc). Defaults to True. Set to False to disable DNS/IP validation entirely (not recommended). */
  user_url_validation?: boolean | null;
}
export const ConfigGeneralSettings = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    alert_to_webhook_url: S.optional(
      S.NullOr(ConfigGeneralSettingsAlertToWebhookUrlMap),
    ),
    alert_types: S.optional(S.NullOr(ConfigGeneralSettingsAlertTypesList)),
    alerting: S.optional(S.NullOr(ConfigGeneralSettingsAlertingList)),
    alerting_args: S.optional(S.NullOr(ConfigGeneralSettingsAlertingArgsMap)),
    alerting_threshold: S.optional(S.NullOr(S.Number)),
    allow_cli_sso_verification_uri_complete: S.optional(S.NullOr(S.Boolean)),
    allowed_routes: S.optional(
      S.NullOr(ConfigGeneralSettingsAllowedRoutesList),
    ),
    apply_user_budget_to_team_keys: S.optional(S.NullOr(S.Boolean)),
    background_health_check_model_groups: S.optional(
      S.NullOr(ConfigGeneralSettingsBackgroundHealthCheckModelGroupsList),
    ),
    background_health_checks: S.optional(S.NullOr(S.Boolean)),
    cancel_on_disconnect: S.optional(S.NullOr(S.Boolean)),
    completion_model: S.optional(S.NullOr(S.String)),
    control_plane_url: S.optional(S.NullOr(S.String)),
    coordination_redis: S.optional(S.NullOr(CoordinationRedisParams)),
    custom_auth: S.optional(S.NullOr(S.String)),
    database_args: S.optional(S.NullOr(DynamoDBArgs)),
    database_connect_timeout: S.optional(S.NullOr(S.Number)),
    database_connection_pool_limit: S.optional(S.NullOr(S.Number)),
    database_connection_timeout: S.optional(S.NullOr(S.Number)),
    database_disable_prepared_statements: S.optional(S.NullOr(S.Boolean)),
    database_extra_connection_params: S.optional(
      S.NullOr(ConfigGeneralSettingsDatabaseExtraConnectionParamsMap),
    ),
    database_socket_timeout: S.optional(S.NullOr(S.Number)),
    database_type: S.optional(S.NullOr(S.String)),
    database_url: S.optional(S.NullOr(S.String)),
    disable_auto_add_proxy_admin_to_teams: S.optional(S.NullOr(S.Boolean)),
    disable_budget_reservation: S.optional(S.NullOr(S.Boolean)),
    enable_public_model_hub: S.optional(S.Boolean),
    enforce_fallback_model_access: S.optional(S.NullOr(S.Boolean)),
    forward_client_headers_to_llm_api: S.optional(S.NullOr(S.Boolean)),
    global_max_parallel_requests: S.optional(S.NullOr(S.Number)),
    health_check_concurrency: S.optional(S.NullOr(S.Number)),
    health_check_interval: S.optional(S.Number),
    health_check_skip_disabled_background_models: S.optional(S.Boolean),
    infer_model_from_keys: S.optional(S.NullOr(S.Boolean)),
    key_management_system: S.optional(S.NullOr(KeyManagementSystem)),
    master_key: S.optional(S.NullOr(S.String)),
    max_batch_file_size_mb: S.optional(S.NullOr(S.Number)),
    max_parallel_requests: S.optional(S.NullOr(S.Number)),
    max_request_size_mb: S.optional(S.NullOr(S.Number)),
    max_response_size_mb: S.optional(S.NullOr(S.Number)),
    maximum_autorouter_session_retention_period: S.optional(S.NullOr(S.String)),
    maximum_health_check_retention_period: S.optional(S.NullOr(S.String)),
    maximum_spend_logs_cleanup_batch_size: S.optional(S.NullOr(S.Number)),
    maximum_spend_logs_cleanup_batch_timeout: S.optional(S.NullOr(S.String)),
    maximum_spend_logs_cleanup_max_batches: S.optional(S.NullOr(S.Number)),
    maximum_spend_logs_cleanup_run_budget: S.optional(S.NullOr(S.String)),
    maximum_spend_logs_retention_period: S.optional(S.NullOr(S.String)),
    mcp_internal_ip_ranges: S.optional(
      S.NullOr(ConfigGeneralSettingsMcpInternalIpRangesList),
    ),
    mcp_required_fields: S.optional(
      S.NullOr(ConfigGeneralSettingsMcpRequiredFieldsList),
    ),
    mcp_trusted_proxy_ranges: S.optional(
      S.NullOr(ConfigGeneralSettingsMcpTrustedProxyRangesList),
    ),
    mcp_xff_num_trusted_hops: S.optional(S.NullOr(S.Number)),
    model_list_healthy_only: S.optional(S.NullOr(S.Boolean)),
    otel: S.optional(S.NullOr(S.Boolean)),
    pass_through_endpoints: S.optional(
      S.NullOr(ConfigGeneralSettingsPassThroughEndpointsList),
    ),
    pass_through_request_timeout: S.optional(S.NullOr(S.Number)),
    plugins: S.optional(S.NullOr(ConfigGeneralSettingsPluginsList)),
    provider_url_destination_allowed_hosts: S.optional(
      S.NullOr(ConfigGeneralSettingsProviderUrlDestinationAllowedHostsList),
    ),
    proxy_config_reload_interval_seconds: S.optional(S.Number),
    reject_clientside_metadata_tags: S.optional(S.NullOr(S.Boolean)),
    scheduled_job_stagger: S.optional(S.NullOr(ScheduledJobStaggerSettings)),
    store_model_in_db: S.optional(S.NullOr(S.Boolean)),
    store_prompts_in_spend_logs: S.optional(S.NullOr(S.Boolean)),
    supported_db_objects: S.optional(
      S.NullOr(ConfigGeneralSettingsSupportedDbObjectsList),
    ),
    trusted_proxy_ranges: S.optional(
      S.NullOr(ConfigGeneralSettingsTrustedProxyRangesList),
    ),
    ui_access_mode: S.optional(S.NullOr(ConfigGeneralSettingsUiAccessMode)),
    use_azure_key_vault: S.optional(S.NullOr(S.Boolean)),
    use_google_kms: S.optional(S.NullOr(S.Boolean)),
    use_spend_logs_partitioning: S.optional(S.NullOr(S.Boolean)),
    user_header_mappings: S.optional(
      S.NullOr(ConfigGeneralSettingsUserHeaderMappingsList),
    ),
    user_header_name: S.optional(S.NullOr(S.String)),
    user_mcp_management_mode: S.optional(
      S.NullOr(ConfigGeneralSettingsUserMcpManagementMode),
    ),
    user_url_allowed_hosts: S.optional(
      S.NullOr(ConfigGeneralSettingsUserUrlAllowedHostsList),
    ),
    user_url_validation: S.optional(S.NullOr(S.Boolean)),
  }),
).annotate({
  identifier: "ConfigGeneralSettings",
}) as any as S.Schema<ConfigGeneralSettings>;

export type GetConfigYamlEndpointConfigYamlRequestLitellmSettingsMap = {
  [key: string]: unknown | undefined;
};
export const GetConfigYamlEndpointConfigYamlRequestLitellmSettingsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.Unknown,
  ) as any as S.Schema<GetConfigYamlEndpointConfigYamlRequestLitellmSettingsMap>;

export type ModelParamsLitellmParamsMap = {
  [key: string]: unknown | undefined;
};
export const ModelParamsLitellmParamsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<ModelParamsLitellmParamsMap>;

export type LitellmProxyTypesModelInfoBaseModel =
  | "gpt-4-1106-preview"
  | "gpt-4-32k"
  | "gpt-4"
  | "gpt-3.5-turbo-16k"
  | "gpt-3.5-turbo"
  | "text-embedding-ada-002";
export const LitellmProxyTypesModelInfoBaseModel = S.String;

export type LitellmProxyTypesModelInfoMode =
  | "embedding"
  | "chat"
  | "completion";
export const LitellmProxyTypesModelInfoMode = S.String;

export interface LitellmProxyTypesModelInfo {
  base_model: LitellmProxyTypesModelInfoBaseModel | (string & {}) | null;
  id: string | null;
  input_cost_per_token?: number | null;
  max_tokens?: number | null;
  mode: LitellmProxyTypesModelInfoMode | (string & {}) | null;
  output_cost_per_token?: number | null;
}
export const LitellmProxyTypesModelInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    base_model: S.NullOr(LitellmProxyTypesModelInfoBaseModel),
    id: S.NullOr(S.String),
    input_cost_per_token: S.optional(S.NullOr(S.Number)),
    max_tokens: S.optional(S.NullOr(S.Number)),
    mode: S.NullOr(LitellmProxyTypesModelInfoMode),
    output_cost_per_token: S.optional(S.NullOr(S.Number)),
  }),
).annotate({
  identifier: "LitellmProxyTypesModelInfo",
}) as any as S.Schema<LitellmProxyTypesModelInfo>;

export interface ModelParams {
  litellm_params: ModelParamsLitellmParamsMap;
  model_info: LitellmProxyTypesModelInfo;
  model_name: string;
}
export const ModelParams = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    litellm_params: ModelParamsLitellmParamsMap,
    model_info: LitellmProxyTypesModelInfo,
    model_name: S.String,
  }),
).annotate({ identifier: "ModelParams" }) as any as S.Schema<ModelParams>;

export type GetConfigYamlEndpointConfigYamlRequestModelListList =
  Array<ModelParams>;
export const GetConfigYamlEndpointConfigYamlRequestModelListList =
  /*@__PURE__*/ S.Array(
    ModelParams,
  ) as any as S.Schema<GetConfigYamlEndpointConfigYamlRequestModelListList>;

export type UpdateRouterConfigContextWindowFallbacksItemMap = {
  [key: string]: unknown | undefined;
};
export const UpdateRouterConfigContextWindowFallbacksItemMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.Unknown,
  ) as any as S.Schema<UpdateRouterConfigContextWindowFallbacksItemMap>;

export type UpdateRouterConfigContextWindowFallbacksList =
  Array<UpdateRouterConfigContextWindowFallbacksItemMap>;
export const UpdateRouterConfigContextWindowFallbacksList =
  /*@__PURE__*/ S.Array(
    UpdateRouterConfigContextWindowFallbacksItemMap,
  ) as any as S.Schema<UpdateRouterConfigContextWindowFallbacksList>;

export type UpdateRouterConfigFallbacksItemMap = {
  [key: string]: unknown | undefined;
};
export const UpdateRouterConfigFallbacksItemMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<UpdateRouterConfigFallbacksItemMap>;

export type UpdateRouterConfigFallbacksList =
  Array<UpdateRouterConfigFallbacksItemMap>;
export const UpdateRouterConfigFallbacksList = /*@__PURE__*/ S.Array(
  UpdateRouterConfigFallbacksItemMap,
) as any as S.Schema<UpdateRouterConfigFallbacksList>;

export type UpdateRouterConfigModelGroupAffinityConfigValueList = Array<string>;
export const UpdateRouterConfigModelGroupAffinityConfigValueList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<UpdateRouterConfigModelGroupAffinityConfigValueList>;

export type UpdateRouterConfigModelGroupAffinityConfigMap = {
  [key: string]:
    | UpdateRouterConfigModelGroupAffinityConfigValueList
    | undefined;
};
export const UpdateRouterConfigModelGroupAffinityConfigMap =
  /*@__PURE__*/ S.Record(
    S.String,
    UpdateRouterConfigModelGroupAffinityConfigValueList,
  ) as any as S.Schema<UpdateRouterConfigModelGroupAffinityConfigMap>;

export type UpdateRouterConfigModelGroupAliasValueCase1Map = {
  [key: string]: unknown | undefined;
};
export const UpdateRouterConfigModelGroupAliasValueCase1Map =
  /*@__PURE__*/ S.Record(
    S.String,
    S.Unknown,
  ) as any as S.Schema<UpdateRouterConfigModelGroupAliasValueCase1Map>;

export type UpdateRouterConfigModelGroupAliasValue =
  | string
  | UpdateRouterConfigModelGroupAliasValueCase1Map;
export const UpdateRouterConfigModelGroupAliasValue =
  S.Unknown as any as S.Schema<UpdateRouterConfigModelGroupAliasValue>;

export type UpdateRouterConfigModelGroupAliasMap = {
  [key: string]: UpdateRouterConfigModelGroupAliasValue | undefined;
};
export const UpdateRouterConfigModelGroupAliasMap = /*@__PURE__*/ S.Record(
  S.String,
  UpdateRouterConfigModelGroupAliasValue,
) as any as S.Schema<UpdateRouterConfigModelGroupAliasMap>;

/** Use this to set a custom number of retries per exception type If RateLimitErrorRetries = 3, then 3 retries will be made for RateLimitError Mapping of Exception type to number of retries https://docs.litellm.ai/docs/exception_mapping */
export interface RetryPolicy {
  AuthenticationErrorRetries?: number | null;
  BadRequestErrorRetries?: number | null;
  ContentPolicyViolationErrorRetries?: number | null;
  InternalServerErrorRetries?: number | null;
  RateLimitErrorRetries?: number | null;
  TimeoutErrorRetries?: number | null;
}
export const RetryPolicy = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    AuthenticationErrorRetries: S.optional(S.NullOr(S.Number)),
    BadRequestErrorRetries: S.optional(S.NullOr(S.Number)),
    ContentPolicyViolationErrorRetries: S.optional(S.NullOr(S.Number)),
    InternalServerErrorRetries: S.optional(S.NullOr(S.Number)),
    RateLimitErrorRetries: S.optional(S.NullOr(S.Number)),
    TimeoutErrorRetries: S.optional(S.NullOr(S.Number)),
  }),
).annotate({ identifier: "RetryPolicy" }) as any as S.Schema<RetryPolicy>;

export type UpdateRouterConfigModelGroupRetryPolicyMap = {
  [key: string]: RetryPolicy | undefined;
};
export const UpdateRouterConfigModelGroupRetryPolicyMap =
  /*@__PURE__*/ S.Record(
    S.String,
    RetryPolicy,
  ) as any as S.Schema<UpdateRouterConfigModelGroupRetryPolicyMap>;

export type RoutingGroupModelsList = Array<string>;
export const RoutingGroupModelsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<RoutingGroupModelsList>;

export type RoutingGroupRoutingStrategyArgsMap = {
  [key: string]: unknown | undefined;
};
export const RoutingGroupRoutingStrategyArgsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<RoutingGroupRoutingStrategyArgsMap>;

/** A group of models that share a routing strategy. */
export interface RoutingGroup {
  group_name: string;
  models: RoutingGroupModelsList;
  routing_strategy: string;
  routing_strategy_args?: RoutingGroupRoutingStrategyArgsMap | null;
}
export const RoutingGroup = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    group_name: S.String,
    models: RoutingGroupModelsList,
    routing_strategy: S.String,
    routing_strategy_args: S.optional(
      S.NullOr(RoutingGroupRoutingStrategyArgsMap),
    ),
  }),
).annotate({ identifier: "RoutingGroup" }) as any as S.Schema<RoutingGroup>;

export type UpdateRouterConfigRoutingGroupsList = Array<RoutingGroup>;
export const UpdateRouterConfigRoutingGroupsList = /*@__PURE__*/ S.Array(
  RoutingGroup,
) as any as S.Schema<UpdateRouterConfigRoutingGroupsList>;

export type UpdateRouterConfigRoutingStrategyArgsMap = {
  [key: string]: unknown | undefined;
};
export const UpdateRouterConfigRoutingStrategyArgsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<UpdateRouterConfigRoutingStrategyArgsMap>;

/** Set of params that you can modify via `router.update_settings()`. */
export interface UpdateRouterConfig {
  allowed_fails?: number | null;
  context_window_fallbacks?: UpdateRouterConfigContextWindowFallbacksList | null;
  cooldown_time?: number | null;
  enable_tag_filtering?: boolean | null;
  fallbacks?: UpdateRouterConfigFallbacksList | null;
  max_retries?: number | null;
  model_group_affinity_config?: UpdateRouterConfigModelGroupAffinityConfigMap | null;
  model_group_alias?: UpdateRouterConfigModelGroupAliasMap | null;
  model_group_retry_policy?: UpdateRouterConfigModelGroupRetryPolicyMap | null;
  num_retries?: number | null;
  retry_after?: number | null;
  retry_policy?: RetryPolicy | null;
  routing_groups?: UpdateRouterConfigRoutingGroupsList | null;
  routing_strategy?: string | null;
  routing_strategy_args?: UpdateRouterConfigRoutingStrategyArgsMap | null;
  tag_routing_prefix?: string | null;
  timeout?: number | null;
}
export const UpdateRouterConfig = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    allowed_fails: S.optional(S.NullOr(S.Number)),
    context_window_fallbacks: S.optional(
      S.NullOr(UpdateRouterConfigContextWindowFallbacksList),
    ),
    cooldown_time: S.optional(S.NullOr(S.Number)),
    enable_tag_filtering: S.optional(S.NullOr(S.Boolean)),
    fallbacks: S.optional(S.NullOr(UpdateRouterConfigFallbacksList)),
    max_retries: S.optional(S.NullOr(S.Number)),
    model_group_affinity_config: S.optional(
      S.NullOr(UpdateRouterConfigModelGroupAffinityConfigMap),
    ),
    model_group_alias: S.optional(
      S.NullOr(UpdateRouterConfigModelGroupAliasMap),
    ),
    model_group_retry_policy: S.optional(
      S.NullOr(UpdateRouterConfigModelGroupRetryPolicyMap),
    ),
    num_retries: S.optional(S.NullOr(S.Number)),
    retry_after: S.optional(S.NullOr(S.Number)),
    retry_policy: S.optional(S.NullOr(RetryPolicy)),
    routing_groups: S.optional(S.NullOr(UpdateRouterConfigRoutingGroupsList)),
    routing_strategy: S.optional(S.NullOr(S.String)),
    routing_strategy_args: S.optional(
      S.NullOr(UpdateRouterConfigRoutingStrategyArgsMap),
    ),
    tag_routing_prefix: S.optional(S.NullOr(S.String)),
    timeout: S.optional(S.NullOr(S.Number)),
  }),
).annotate({
  identifier: "UpdateRouterConfig",
}) as any as S.Schema<UpdateRouterConfig>;

export interface WorkerRegistryEntry {
  name: string;
  url: string;
  worker_id: string;
}
export const WorkerRegistryEntry = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.String,
    url: S.String,
    worker_id: S.String,
  }),
).annotate({
  identifier: "WorkerRegistryEntry",
}) as any as S.Schema<WorkerRegistryEntry>;

export type GetConfigYamlEndpointConfigYamlRequestWorkerRegistryList =
  Array<WorkerRegistryEntry>;
export const GetConfigYamlEndpointConfigYamlRequestWorkerRegistryList =
  /*@__PURE__*/ S.Array(
    WorkerRegistryEntry,
  ) as any as S.Schema<GetConfigYamlEndpointConfigYamlRequestWorkerRegistryList>;

export interface GetConfigYamlEndpointConfigYamlRequest {
  /** Object to pass in additional environment variables via POST request */
  environment_variables?: GetConfigYamlEndpointConfigYamlRequestEnvironmentVariablesMap | null;
  general_settings?: ConfigGeneralSettings | null;
  /** litellm Module settings. See __init__.py for all, example litellm.drop_params=True, litellm.set_verbose=True, litellm.api_base, litellm.cache */
  litellm_settings?: GetConfigYamlEndpointConfigYamlRequestLitellmSettingsMap | null;
  /** List of supported models on the server, with model-specific configs */
  model_list?: GetConfigYamlEndpointConfigYamlRequestModelListList | null;
  /** litellm router object settings. See router.py __init__ for all, example router.num_retries=5, router.timeout=5, router.max_retries=5, router.retry_after=5 */
  router_settings?: UpdateRouterConfig | null;
  /** Global Control Plane: the independent proxy instances this instance's admin UI manages. Setting it makes this a control plane, which serves the UI and does not route LLM requests. Enterprise-only */
  worker_registry?: GetConfigYamlEndpointConfigYamlRequestWorkerRegistryList | null;
}
export const GetConfigYamlEndpointConfigYamlRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      environment_variables: S.optional(
        S.NullOr(GetConfigYamlEndpointConfigYamlRequestEnvironmentVariablesMap),
      ),
      general_settings: S.optional(S.NullOr(ConfigGeneralSettings)),
      litellm_settings: S.optional(
        S.NullOr(GetConfigYamlEndpointConfigYamlRequestLitellmSettingsMap),
      ),
      model_list: S.optional(
        S.NullOr(GetConfigYamlEndpointConfigYamlRequestModelListList),
      ),
      router_settings: S.optional(S.NullOr(UpdateRouterConfig)),
      worker_registry: S.optional(
        S.NullOr(GetConfigYamlEndpointConfigYamlRequestWorkerRegistryList),
      ),
    }).pipe(T.Http({ method: "GET", uri: "/config/yaml", code: 200 })),
).annotate({
  identifier: "GetConfigYamlEndpointConfigYamlRequest",
}) as any as S.Schema<GetConfigYamlEndpointConfigYamlRequest>;

export interface GetConfigYamlEndpointConfigYamlResponse {
  body: unknown;
}
export const GetConfigYamlEndpointConfigYamlResponse = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      body: S.Unknown,
    }),
).annotate({
  identifier: "GetConfigYamlEndpointConfigYamlResponse",
}) as any as S.Schema<GetConfigYamlEndpointConfigYamlResponse>;

export type UpdateConfigConfigUpdatePostRequestEnvironmentVariablesMap = {
  [key: string]: unknown | undefined;
};
export const UpdateConfigConfigUpdatePostRequestEnvironmentVariablesMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.Unknown,
  ) as any as S.Schema<UpdateConfigConfigUpdatePostRequestEnvironmentVariablesMap>;

export type UpdateConfigConfigUpdatePostRequestLitellmSettingsMap = {
  [key: string]: unknown | undefined;
};
export const UpdateConfigConfigUpdatePostRequestLitellmSettingsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.Unknown,
  ) as any as S.Schema<UpdateConfigConfigUpdatePostRequestLitellmSettingsMap>;

export type UpdateConfigConfigUpdatePostRequestModelListList =
  Array<ModelParams>;
export const UpdateConfigConfigUpdatePostRequestModelListList =
  /*@__PURE__*/ S.Array(
    ModelParams,
  ) as any as S.Schema<UpdateConfigConfigUpdatePostRequestModelListList>;

export type UpdateConfigConfigUpdatePostRequestWorkerRegistryList =
  Array<WorkerRegistryEntry>;
export const UpdateConfigConfigUpdatePostRequestWorkerRegistryList =
  /*@__PURE__*/ S.Array(
    WorkerRegistryEntry,
  ) as any as S.Schema<UpdateConfigConfigUpdatePostRequestWorkerRegistryList>;

export interface UpdateConfigConfigUpdatePostRequest {
  /** Object to pass in additional environment variables via POST request */
  environment_variables?: UpdateConfigConfigUpdatePostRequestEnvironmentVariablesMap | null;
  general_settings?: ConfigGeneralSettings | null;
  /** litellm Module settings. See __init__.py for all, example litellm.drop_params=True, litellm.set_verbose=True, litellm.api_base, litellm.cache */
  litellm_settings?: UpdateConfigConfigUpdatePostRequestLitellmSettingsMap | null;
  /** List of supported models on the server, with model-specific configs */
  model_list?: UpdateConfigConfigUpdatePostRequestModelListList | null;
  /** litellm router object settings. See router.py __init__ for all, example router.num_retries=5, router.timeout=5, router.max_retries=5, router.retry_after=5 */
  router_settings?: UpdateRouterConfig | null;
  /** Global Control Plane: the independent proxy instances this instance's admin UI manages. Setting it makes this a control plane, which serves the UI and does not route LLM requests. Enterprise-only */
  worker_registry?: UpdateConfigConfigUpdatePostRequestWorkerRegistryList | null;
}
export const UpdateConfigConfigUpdatePostRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    environment_variables: S.optional(
      S.NullOr(UpdateConfigConfigUpdatePostRequestEnvironmentVariablesMap),
    ),
    general_settings: S.optional(S.NullOr(ConfigGeneralSettings)),
    litellm_settings: S.optional(
      S.NullOr(UpdateConfigConfigUpdatePostRequestLitellmSettingsMap),
    ),
    model_list: S.optional(
      S.NullOr(UpdateConfigConfigUpdatePostRequestModelListList),
    ),
    router_settings: S.optional(S.NullOr(UpdateRouterConfig)),
    worker_registry: S.optional(
      S.NullOr(UpdateConfigConfigUpdatePostRequestWorkerRegistryList),
    ),
  }).pipe(T.Http({ method: "POST", uri: "/config/update", code: 200 })),
).annotate({
  identifier: "UpdateConfigConfigUpdatePostRequest",
}) as any as S.Schema<UpdateConfigConfigUpdatePostRequest>;

export interface UpdateConfigConfigUpdatePostResponse {
  body: unknown;
}
export const UpdateConfigConfigUpdatePostResponse = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      body: S.Unknown,
    }),
).annotate({
  identifier: "UpdateConfigConfigUpdatePostResponse",
}) as any as S.Schema<UpdateConfigConfigUpdatePostResponse>;

export interface UpdateConfigGeneralSettingsConfigFieldUpdatePostRequest {
  config_type: string;
  field_name: string;
  field_value: unknown;
}
export const UpdateConfigGeneralSettingsConfigFieldUpdatePostRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      config_type: S.String,
      field_name: S.String,
      field_value: S.Unknown,
    }).pipe(T.Http({ method: "POST", uri: "/config/field/update", code: 200 })),
  ).annotate({
    identifier: "UpdateConfigGeneralSettingsConfigFieldUpdatePostRequest",
  }) as any as S.Schema<UpdateConfigGeneralSettingsConfigFieldUpdatePostRequest>;

export interface UpdateConfigGeneralSettingsConfigFieldUpdatePostResponse {
  body: unknown;
}
export const UpdateConfigGeneralSettingsConfigFieldUpdatePostResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "UpdateConfigGeneralSettingsConfigFieldUpdatePostResponse",
  }) as any as S.Schema<UpdateConfigGeneralSettingsConfigFieldUpdatePostResponse>;

export type DeleteCallbackConfigCallbackDeletePostError =
  | UnprocessableEntity
  | LitellmOpError;
/** Delete Callback Delete specific logging callback from configuration. */
export const deleteCallbackConfigCallbackDeletePost: API.OperationMethod<
  DeleteCallbackConfigCallbackDeletePostRequest,
  DeleteCallbackConfigCallbackDeletePostResponse,
  DeleteCallbackConfigCallbackDeletePostError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteCallbackConfigCallbackDeletePostRequest,
  output: DeleteCallbackConfigCallbackDeletePostResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type DeleteConfigGeneralSettingsConfigFieldDeletePostError =
  | UnprocessableEntity
  | LitellmOpError;
/** Delete Config General Settings Delete the db value of this field in litellm general settings. Resets it to it's initial default value on litellm. */
export const deleteConfigGeneralSettingsConfigFieldDeletePost: API.OperationMethod<
  DeleteConfigGeneralSettingsConfigFieldDeletePostRequest,
  DeleteConfigGeneralSettingsConfigFieldDeletePostResponse,
  DeleteConfigGeneralSettingsConfigFieldDeletePostError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteConfigGeneralSettingsConfigFieldDeletePostRequest,
  output: DeleteConfigGeneralSettingsConfigFieldDeletePostResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetConfigGeneralSettingsConfigFieldInfoGetError =
  | UnprocessableEntity
  | LitellmOpError;
/** Get Config General Settings */
export const getConfigGeneralSettingsConfigFieldInfoGet: API.OperationMethod<
  GetConfigGeneralSettingsConfigFieldInfoGetRequest,
  ConfigFieldInfo,
  GetConfigGeneralSettingsConfigFieldInfoGetError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetConfigGeneralSettingsConfigFieldInfoGetRequest,
  output: ConfigFieldInfo,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetConfigGetConfigCallbacksGetError = LitellmOpError;
/** Get Config For Admin UI - allows admin to view config via UI # return the callbacks and the env variables for the callback */
export const getConfigGetConfigCallbacksGet: API.OperationMethod<
  GetConfigGetConfigCallbacksGetRequest,
  GetConfigGetConfigCallbacksGetResponse,
  GetConfigGetConfigCallbacksGetError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetConfigGetConfigCallbacksGetRequest,
  output: GetConfigGetConfigCallbacksGetResponse,
  errors: [],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetConfigListConfigListGetError =
  | UnprocessableEntity
  | LitellmOpError;
/** Get Config List List the available fields + current values for a given type of setting (currently just 'general_settings'user_api_key_dict: UserAPIKeyAuth = Depends(user_api_key_auth),) */
export const getConfigListConfigListGet: API.OperationMethod<
  GetConfigListConfigListGetRequest,
  GetConfigListConfigListGetResponse,
  GetConfigListConfigListGetError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetConfigListConfigListGetRequest,
  output: GetConfigListConfigListGetResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetConfigYamlEndpointConfigYamlError =
  | UnprocessableEntity
  | LitellmOpError;
/** Config Yaml Endpoint This is a mock endpoint, to show what you can set in config.yaml details in the Swagger UI. Parameters: The config.yaml object has the following attributes: - **model_list**: *Optional[List[ModelParams]]* - A list of supported models on the server, along with model-specific configurations. ModelParams includes "model_name" (name of the model), "litellm_params" (litellm-specific parameters for the model), and "model_info" (additional info about the model such as id, mode, cost per token, etc). - **litellm_settings**: *Optional[dict]*: Settings for the litellm module. You can specify multiple properties like "drop_params", "set_verbose", "api_base", "cache". - **general_settings**: *Optional[ConfigGeneralSettings]*: General settings for the server like "completion_model" (default model for chat completion calls), "use_azure_key_vault" (option to load keys from azure key vault), "master_key" (key required for all calls to proxy), and others. Please, refer to each class's description for a better understanding of the specific attributes within them. Note: This is a mock endpoint primarily meant for demonstration purposes, and does not actually provide or change any configurations. */
export const getConfigYamlEndpointConfigYaml: API.OperationMethod<
  GetConfigYamlEndpointConfigYamlRequest,
  GetConfigYamlEndpointConfigYamlResponse,
  GetConfigYamlEndpointConfigYamlError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetConfigYamlEndpointConfigYamlRequest,
  output: GetConfigYamlEndpointConfigYamlResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type UpdateConfigConfigUpdatePostError =
  | UnprocessableEntity
  | LitellmOpError;
/** Update Config For Admin UI - allows admin to update config via UI. Writes only the sections present in the request body to LiteLLM_Config rows (one row per top-level section). Sections the caller did not send are left untouched — this endpoint never persists pre-existing YAML values to DB as a side effect of an unrelated update. */
export const updateConfigConfigUpdatePost: API.OperationMethod<
  UpdateConfigConfigUpdatePostRequest,
  UpdateConfigConfigUpdatePostResponse,
  UpdateConfigConfigUpdatePostError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateConfigConfigUpdatePostRequest,
  output: UpdateConfigConfigUpdatePostResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type UpdateConfigGeneralSettingsConfigFieldUpdatePostError =
  | UnprocessableEntity
  | LitellmOpError;
/** Update Config General Settings Update a specific field in litellm general settings */
export const updateConfigGeneralSettingsConfigFieldUpdatePost: API.OperationMethod<
  UpdateConfigGeneralSettingsConfigFieldUpdatePostRequest,
  UpdateConfigGeneralSettingsConfigFieldUpdatePostResponse,
  UpdateConfigGeneralSettingsConfigFieldUpdatePostError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateConfigGeneralSettingsConfigFieldUpdatePostRequest,
  output: UpdateConfigGeneralSettingsConfigFieldUpdatePostResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));
