// AUTO-GENERATED by scripts/generate.ts from .generated-specs (pinned litellm-openapi @ 1.100.0 — see README). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
import * as T from "../traits.ts";
import {
  LitellmProtocol,
  type LitellmOpError,
  type LitellmOpContext,
} from "../protocol.ts";
import * as Retry from "../retry.ts";

export type { LitellmOpError, LitellmOpContext };

export class UnprocessableEntity
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<UnprocessableEntity>()("UnprocessableEntity", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 422 }],
  ) {}

export interface CreateContainerContainersPostRequest {}
export const CreateContainerContainersPostRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({}).pipe(
      T.Http({ method: "POST", uri: "/containers", code: 200 }),
    ),
).annotate({
  identifier: "CreateContainerContainersPostRequest",
}) as any as S.Schema<CreateContainerContainersPostRequest>;

export interface CreateContainerContainersPostResponse {
  body: unknown;
}
export const CreateContainerContainersPostResponse = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      body: S.Unknown,
    }),
).annotate({
  identifier: "CreateContainerContainersPostResponse",
}) as any as S.Schema<CreateContainerContainersPostResponse>;

export interface CreateContainerV1ContainersPostRequest {}
export const CreateContainerV1ContainersPostRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({}).pipe(
      T.Http({ method: "POST", uri: "/v1/containers", code: 200 }),
    ),
).annotate({
  identifier: "CreateContainerV1ContainersPostRequest",
}) as any as S.Schema<CreateContainerV1ContainersPostRequest>;

export interface CreateContainerV1ContainersPostResponse {
  body: unknown;
}
export const CreateContainerV1ContainersPostResponse = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      body: S.Unknown,
    }),
).annotate({
  identifier: "CreateContainerV1ContainersPostResponse",
}) as any as S.Schema<CreateContainerV1ContainersPostResponse>;

export interface DeleteContainerContainersContainerIdDeleteRequest {
  container_id: string;
}
export const DeleteContainerContainersContainerIdDeleteRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      container_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "DELETE",
        uri: "/containers/{container_id}",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "DeleteContainerContainersContainerIdDeleteRequest",
  }) as any as S.Schema<DeleteContainerContainersContainerIdDeleteRequest>;

export interface DeleteContainerContainersContainerIdDeleteResponse {
  body: unknown;
}
export const DeleteContainerContainersContainerIdDeleteResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "DeleteContainerContainersContainerIdDeleteResponse",
  }) as any as S.Schema<DeleteContainerContainersContainerIdDeleteResponse>;

export interface DeleteContainerV1ContainersContainerIdDeleteRequest {
  container_id: string;
}
export const DeleteContainerV1ContainersContainerIdDeleteRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      container_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "DELETE",
        uri: "/v1/containers/{container_id}",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "DeleteContainerV1ContainersContainerIdDeleteRequest",
  }) as any as S.Schema<DeleteContainerV1ContainersContainerIdDeleteRequest>;

export interface DeleteContainerV1ContainersContainerIdDeleteResponse {
  body: unknown;
}
export const DeleteContainerV1ContainersContainerIdDeleteResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "DeleteContainerV1ContainersContainerIdDeleteResponse",
  }) as any as S.Schema<DeleteContainerV1ContainersContainerIdDeleteResponse>;

export interface DeleteHandlerContainerFileContainersContainerIdFilesFileIdRequest {
  container_id: string;
  file_id: string;
}
export const DeleteHandlerContainerFileContainersContainerIdFilesFileIdRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      container_id: S.String.pipe(T.Label()),
      file_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "DELETE",
        uri: "/containers/{container_id}/files/{file_id}",
        code: 200,
      }),
    ),
  ).annotate({
    identifier:
      "DeleteHandlerContainerFileContainersContainerIdFilesFileIdRequest",
  }) as any as S.Schema<DeleteHandlerContainerFileContainersContainerIdFilesFileIdRequest>;

export interface DeleteHandlerContainerFileContainersContainerIdFilesFileIdResponse {
  body: unknown;
}
export const DeleteHandlerContainerFileContainersContainerIdFilesFileIdResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier:
      "DeleteHandlerContainerFileContainersContainerIdFilesFileIdResponse",
  }) as any as S.Schema<DeleteHandlerContainerFileContainersContainerIdFilesFileIdResponse>;

export interface DeleteHandlerContainerFileV1ContainersContainerIdFilesFileIdRequest {
  container_id: string;
  file_id: string;
}
export const DeleteHandlerContainerFileV1ContainersContainerIdFilesFileIdRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      container_id: S.String.pipe(T.Label()),
      file_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "DELETE",
        uri: "/v1/containers/{container_id}/files/{file_id}",
        code: 200,
      }),
    ),
  ).annotate({
    identifier:
      "DeleteHandlerContainerFileV1ContainersContainerIdFilesFileIdRequest",
  }) as any as S.Schema<DeleteHandlerContainerFileV1ContainersContainerIdFilesFileIdRequest>;

export interface DeleteHandlerContainerFileV1ContainersContainerIdFilesFileIdResponse {
  body: unknown;
}
export const DeleteHandlerContainerFileV1ContainersContainerIdFilesFileIdResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier:
      "DeleteHandlerContainerFileV1ContainersContainerIdFilesFileIdResponse",
  }) as any as S.Schema<DeleteHandlerContainerFileV1ContainersContainerIdFilesFileIdResponse>;

export interface GetContainerContainersContainerIdGetRequest {
  container_id: string;
}
export const GetContainerContainersContainerIdGetRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      container_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({ method: "GET", uri: "/containers/{container_id}", code: 200 }),
    ),
  ).annotate({
    identifier: "GetContainerContainersContainerIdGetRequest",
  }) as any as S.Schema<GetContainerContainersContainerIdGetRequest>;

export interface GetContainerContainersContainerIdGetResponse {
  body: unknown;
}
export const GetContainerContainersContainerIdGetResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "GetContainerContainersContainerIdGetResponse",
  }) as any as S.Schema<GetContainerContainersContainerIdGetResponse>;

export interface GetContainerV1ContainersContainerIdGetRequest {
  container_id: string;
}
export const GetContainerV1ContainersContainerIdGetRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      container_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/v1/containers/{container_id}",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "GetContainerV1ContainersContainerIdGetRequest",
  }) as any as S.Schema<GetContainerV1ContainersContainerIdGetRequest>;

export interface GetContainerV1ContainersContainerIdGetResponse {
  body: unknown;
}
export const GetContainerV1ContainersContainerIdGetResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "GetContainerV1ContainersContainerIdGetResponse",
  }) as any as S.Schema<GetContainerV1ContainersContainerIdGetResponse>;

export interface GetHandlerBinaryContentContainersContainerIdFilesFileIdContentRequest {
  container_id: string;
  file_id: string;
}
export const GetHandlerBinaryContentContainersContainerIdFilesFileIdContentRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      container_id: S.String.pipe(T.Label()),
      file_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/containers/{container_id}/files/{file_id}/content",
        code: 200,
      }),
    ),
  ).annotate({
    identifier:
      "GetHandlerBinaryContentContainersContainerIdFilesFileIdContentRequest",
  }) as any as S.Schema<GetHandlerBinaryContentContainersContainerIdFilesFileIdContentRequest>;

export interface GetHandlerBinaryContentContainersContainerIdFilesFileIdContentResponse {
  body: unknown;
}
export const GetHandlerBinaryContentContainersContainerIdFilesFileIdContentResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier:
      "GetHandlerBinaryContentContainersContainerIdFilesFileIdContentResponse",
  }) as any as S.Schema<GetHandlerBinaryContentContainersContainerIdFilesFileIdContentResponse>;

export interface GetHandlerBinaryContentV1ContainersContainerIdFilesFileIdContentRequest {
  container_id: string;
  file_id: string;
}
export const GetHandlerBinaryContentV1ContainersContainerIdFilesFileIdContentRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      container_id: S.String.pipe(T.Label()),
      file_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/v1/containers/{container_id}/files/{file_id}/content",
        code: 200,
      }),
    ),
  ).annotate({
    identifier:
      "GetHandlerBinaryContentV1ContainersContainerIdFilesFileIdContentRequest",
  }) as any as S.Schema<GetHandlerBinaryContentV1ContainersContainerIdFilesFileIdContentRequest>;

export interface GetHandlerBinaryContentV1ContainersContainerIdFilesFileIdContentResponse {
  body: unknown;
}
export const GetHandlerBinaryContentV1ContainersContainerIdFilesFileIdContentResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier:
      "GetHandlerBinaryContentV1ContainersContainerIdFilesFileIdContentResponse",
  }) as any as S.Schema<GetHandlerBinaryContentV1ContainersContainerIdFilesFileIdContentResponse>;

export interface GetHandlerContainerFileContainersContainerIdFilesFileIdRequest {
  container_id: string;
  file_id: string;
}
export const GetHandlerContainerFileContainersContainerIdFilesFileIdRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      container_id: S.String.pipe(T.Label()),
      file_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/containers/{container_id}/files/{file_id}",
        code: 200,
      }),
    ),
  ).annotate({
    identifier:
      "GetHandlerContainerFileContainersContainerIdFilesFileIdRequest",
  }) as any as S.Schema<GetHandlerContainerFileContainersContainerIdFilesFileIdRequest>;

export interface GetHandlerContainerFileContainersContainerIdFilesFileIdResponse {
  body: unknown;
}
export const GetHandlerContainerFileContainersContainerIdFilesFileIdResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier:
      "GetHandlerContainerFileContainersContainerIdFilesFileIdResponse",
  }) as any as S.Schema<GetHandlerContainerFileContainersContainerIdFilesFileIdResponse>;

export interface GetHandlerContainerFileV1ContainersContainerIdFilesFileIdRequest {
  container_id: string;
  file_id: string;
}
export const GetHandlerContainerFileV1ContainersContainerIdFilesFileIdRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      container_id: S.String.pipe(T.Label()),
      file_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/v1/containers/{container_id}/files/{file_id}",
        code: 200,
      }),
    ),
  ).annotate({
    identifier:
      "GetHandlerContainerFileV1ContainersContainerIdFilesFileIdRequest",
  }) as any as S.Schema<GetHandlerContainerFileV1ContainersContainerIdFilesFileIdRequest>;

export interface GetHandlerContainerFileV1ContainersContainerIdFilesFileIdResponse {
  body: unknown;
}
export const GetHandlerContainerFileV1ContainersContainerIdFilesFileIdResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier:
      "GetHandlerContainerFileV1ContainersContainerIdFilesFileIdResponse",
  }) as any as S.Schema<GetHandlerContainerFileV1ContainersContainerIdFilesFileIdResponse>;

export interface GetHandlerContainerIdContainersContainerIdFileRequest {
  container_id: string;
}
export const GetHandlerContainerIdContainersContainerIdFileRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      container_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/containers/{container_id}/files",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "GetHandlerContainerIdContainersContainerIdFileRequest",
  }) as any as S.Schema<GetHandlerContainerIdContainersContainerIdFileRequest>;

export interface GetHandlerContainerIdContainersContainerIdFileResponse {
  body: unknown;
}
export const GetHandlerContainerIdContainersContainerIdFileResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "GetHandlerContainerIdContainersContainerIdFileResponse",
  }) as any as S.Schema<GetHandlerContainerIdContainersContainerIdFileResponse>;

export interface GetHandlerContainerIdV1ContainersContainerIdFileRequest {
  container_id: string;
}
export const GetHandlerContainerIdV1ContainersContainerIdFileRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      container_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/v1/containers/{container_id}/files",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "GetHandlerContainerIdV1ContainersContainerIdFileRequest",
  }) as any as S.Schema<GetHandlerContainerIdV1ContainersContainerIdFileRequest>;

export interface GetHandlerContainerIdV1ContainersContainerIdFileResponse {
  body: unknown;
}
export const GetHandlerContainerIdV1ContainersContainerIdFileResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "GetHandlerContainerIdV1ContainersContainerIdFileResponse",
  }) as any as S.Schema<GetHandlerContainerIdV1ContainersContainerIdFileResponse>;

export interface HandlerMultipartUploadContainersContainerIdFilesPostRequest {
  container_id: string;
}
export const HandlerMultipartUploadContainersContainerIdFilesPostRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      container_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/containers/{container_id}/files",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "HandlerMultipartUploadContainersContainerIdFilesPostRequest",
  }) as any as S.Schema<HandlerMultipartUploadContainersContainerIdFilesPostRequest>;

export interface HandlerMultipartUploadContainersContainerIdFilesPostResponse {
  body: unknown;
}
export const HandlerMultipartUploadContainersContainerIdFilesPostResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "HandlerMultipartUploadContainersContainerIdFilesPostResponse",
  }) as any as S.Schema<HandlerMultipartUploadContainersContainerIdFilesPostResponse>;

export interface HandlerMultipartUploadV1ContainersContainerIdFilesPostRequest {
  container_id: string;
}
export const HandlerMultipartUploadV1ContainersContainerIdFilesPostRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      container_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/v1/containers/{container_id}/files",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "HandlerMultipartUploadV1ContainersContainerIdFilesPostRequest",
  }) as any as S.Schema<HandlerMultipartUploadV1ContainersContainerIdFilesPostRequest>;

export interface HandlerMultipartUploadV1ContainersContainerIdFilesPostResponse {
  body: unknown;
}
export const HandlerMultipartUploadV1ContainersContainerIdFilesPostResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier:
      "HandlerMultipartUploadV1ContainersContainerIdFilesPostResponse",
  }) as any as S.Schema<HandlerMultipartUploadV1ContainersContainerIdFilesPostResponse>;

export interface ListContainersContainersGetRequest {}
export const ListContainersContainersGetRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/containers", code: 200 })),
).annotate({
  identifier: "ListContainersContainersGetRequest",
}) as any as S.Schema<ListContainersContainersGetRequest>;

export interface ListContainersContainersGetResponse {
  body: unknown;
}
export const ListContainersContainersGetResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    body: S.Unknown,
  }),
).annotate({
  identifier: "ListContainersContainersGetResponse",
}) as any as S.Schema<ListContainersContainersGetResponse>;

export interface ListContainersV1ContainersGetRequest {}
export const ListContainersV1ContainersGetRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({}).pipe(
      T.Http({ method: "GET", uri: "/v1/containers", code: 200 }),
    ),
).annotate({
  identifier: "ListContainersV1ContainersGetRequest",
}) as any as S.Schema<ListContainersV1ContainersGetRequest>;

export interface ListContainersV1ContainersGetResponse {
  body: unknown;
}
export const ListContainersV1ContainersGetResponse = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      body: S.Unknown,
    }),
).annotate({
  identifier: "ListContainersV1ContainersGetResponse",
}) as any as S.Schema<ListContainersV1ContainersGetResponse>;

export type CreateContainerContainersPostError = LitellmOpError;
/** Create Container Container creation endpoint for creating new containers. Follows the OpenAI Containers API spec: https://platform.openai.com/docs/api-reference/containers Example: ```bash curl -X POST "http://localhost:4000/v1/containers" -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" -d '{ "name": "My Container", "expires_after": { "anchor": "last_active_at", "minutes": 20 } }' ``` Or specify provider via header: ```bash curl -X POST "http://localhost:4000/v1/containers" -H "Authorization: Bearer sk-1234" -H "custom-llm-provider: azure" -H "Content-Type: application/json" -d '{ "name": "My Container" }' ``` */
export const createContainerContainersPost: API.OperationMethod<
  CreateContainerContainersPostRequest,
  CreateContainerContainersPostResponse,
  CreateContainerContainersPostError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateContainerContainersPostRequest,
  output: CreateContainerContainersPostResponse,
  errors: [],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type CreateContainerV1ContainersPostError = LitellmOpError;
/** Create Container Container creation endpoint for creating new containers. Follows the OpenAI Containers API spec: https://platform.openai.com/docs/api-reference/containers Example: ```bash curl -X POST "http://localhost:4000/v1/containers" -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" -d '{ "name": "My Container", "expires_after": { "anchor": "last_active_at", "minutes": 20 } }' ``` Or specify provider via header: ```bash curl -X POST "http://localhost:4000/v1/containers" -H "Authorization: Bearer sk-1234" -H "custom-llm-provider: azure" -H "Content-Type: application/json" -d '{ "name": "My Container" }' ``` */
export const createContainerV1ContainersPost: API.OperationMethod<
  CreateContainerV1ContainersPostRequest,
  CreateContainerV1ContainersPostResponse,
  CreateContainerV1ContainersPostError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateContainerV1ContainersPostRequest,
  output: CreateContainerV1ContainersPostResponse,
  errors: [],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type DeleteContainerContainersContainerIdDeleteError =
  | UnprocessableEntity
  | LitellmOpError;
/** Delete Container Container delete endpoint for deleting a specific container. Follows the OpenAI Containers API spec: https://platform.openai.com/docs/api-reference/containers Example: ```bash curl -X DELETE "http://localhost:4000/v1/containers/cntr_123" -H "Authorization: Bearer sk-1234" ``` Or specify provider via header: ```bash curl -X DELETE "http://localhost:4000/v1/containers/cntr_123" -H "Authorization: Bearer sk-1234" -H "custom-llm-provider: azure" ``` */
export const deleteContainerContainersContainerIdDelete: API.OperationMethod<
  DeleteContainerContainersContainerIdDeleteRequest,
  DeleteContainerContainersContainerIdDeleteResponse,
  DeleteContainerContainersContainerIdDeleteError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteContainerContainersContainerIdDeleteRequest,
  output: DeleteContainerContainersContainerIdDeleteResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type DeleteContainerV1ContainersContainerIdDeleteError =
  | UnprocessableEntity
  | LitellmOpError;
/** Delete Container Container delete endpoint for deleting a specific container. Follows the OpenAI Containers API spec: https://platform.openai.com/docs/api-reference/containers Example: ```bash curl -X DELETE "http://localhost:4000/v1/containers/cntr_123" -H "Authorization: Bearer sk-1234" ``` Or specify provider via header: ```bash curl -X DELETE "http://localhost:4000/v1/containers/cntr_123" -H "Authorization: Bearer sk-1234" -H "custom-llm-provider: azure" ``` */
export const deleteContainerV1ContainersContainerIdDelete: API.OperationMethod<
  DeleteContainerV1ContainersContainerIdDeleteRequest,
  DeleteContainerV1ContainersContainerIdDeleteResponse,
  DeleteContainerV1ContainersContainerIdDeleteError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteContainerV1ContainersContainerIdDeleteRequest,
  output: DeleteContainerV1ContainersContainerIdDeleteResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type DeleteHandlerContainerFileContainersContainerIdFilesFileIdError =
  | UnprocessableEntity
  | LitellmOpError;
/** Handler Container File */
export const deleteHandlerContainerFileContainersContainerIdFilesFileId: API.OperationMethod<
  DeleteHandlerContainerFileContainersContainerIdFilesFileIdRequest,
  DeleteHandlerContainerFileContainersContainerIdFilesFileIdResponse,
  DeleteHandlerContainerFileContainersContainerIdFilesFileIdError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteHandlerContainerFileContainersContainerIdFilesFileIdRequest,
  output: DeleteHandlerContainerFileContainersContainerIdFilesFileIdResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type DeleteHandlerContainerFileV1ContainersContainerIdFilesFileIdError =
  | UnprocessableEntity
  | LitellmOpError;
/** Handler Container File */
export const deleteHandlerContainerFileV1ContainersContainerIdFilesFileId: API.OperationMethod<
  DeleteHandlerContainerFileV1ContainersContainerIdFilesFileIdRequest,
  DeleteHandlerContainerFileV1ContainersContainerIdFilesFileIdResponse,
  DeleteHandlerContainerFileV1ContainersContainerIdFilesFileIdError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteHandlerContainerFileV1ContainersContainerIdFilesFileIdRequest,
  output: DeleteHandlerContainerFileV1ContainersContainerIdFilesFileIdResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetContainerContainersContainerIdGetError =
  | UnprocessableEntity
  | LitellmOpError;
/** Retrieve Container Container retrieve endpoint for getting details of a specific container. Follows the OpenAI Containers API spec: https://platform.openai.com/docs/api-reference/containers Example: ```bash curl -X GET "http://localhost:4000/v1/containers/cntr_123" -H "Authorization: Bearer sk-1234" ``` Or specify provider via header: ```bash curl -X GET "http://localhost:4000/v1/containers/cntr_123" -H "Authorization: Bearer sk-1234" -H "custom-llm-provider: azure" ``` */
export const getContainerContainersContainerIdGet: API.OperationMethod<
  GetContainerContainersContainerIdGetRequest,
  GetContainerContainersContainerIdGetResponse,
  GetContainerContainersContainerIdGetError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetContainerContainersContainerIdGetRequest,
  output: GetContainerContainersContainerIdGetResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetContainerV1ContainersContainerIdGetError =
  | UnprocessableEntity
  | LitellmOpError;
/** Retrieve Container Container retrieve endpoint for getting details of a specific container. Follows the OpenAI Containers API spec: https://platform.openai.com/docs/api-reference/containers Example: ```bash curl -X GET "http://localhost:4000/v1/containers/cntr_123" -H "Authorization: Bearer sk-1234" ``` Or specify provider via header: ```bash curl -X GET "http://localhost:4000/v1/containers/cntr_123" -H "Authorization: Bearer sk-1234" -H "custom-llm-provider: azure" ``` */
export const getContainerV1ContainersContainerIdGet: API.OperationMethod<
  GetContainerV1ContainersContainerIdGetRequest,
  GetContainerV1ContainersContainerIdGetResponse,
  GetContainerV1ContainersContainerIdGetError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetContainerV1ContainersContainerIdGetRequest,
  output: GetContainerV1ContainersContainerIdGetResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetHandlerBinaryContentContainersContainerIdFilesFileIdContentError =
  | UnprocessableEntity
  | LitellmOpError;
/** Handler Binary Content */
export const getHandlerBinaryContentContainersContainerIdFilesFileIdContent: API.OperationMethod<
  GetHandlerBinaryContentContainersContainerIdFilesFileIdContentRequest,
  GetHandlerBinaryContentContainersContainerIdFilesFileIdContentResponse,
  GetHandlerBinaryContentContainersContainerIdFilesFileIdContentError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetHandlerBinaryContentContainersContainerIdFilesFileIdContentRequest,
  output:
    GetHandlerBinaryContentContainersContainerIdFilesFileIdContentResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetHandlerBinaryContentV1ContainersContainerIdFilesFileIdContentError =
  | UnprocessableEntity
  | LitellmOpError;
/** Handler Binary Content */
export const getHandlerBinaryContentV1ContainersContainerIdFilesFileIdContent: API.OperationMethod<
  GetHandlerBinaryContentV1ContainersContainerIdFilesFileIdContentRequest,
  GetHandlerBinaryContentV1ContainersContainerIdFilesFileIdContentResponse,
  GetHandlerBinaryContentV1ContainersContainerIdFilesFileIdContentError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input:
    GetHandlerBinaryContentV1ContainersContainerIdFilesFileIdContentRequest,
  output:
    GetHandlerBinaryContentV1ContainersContainerIdFilesFileIdContentResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetHandlerContainerFileContainersContainerIdFilesFileIdError =
  | UnprocessableEntity
  | LitellmOpError;
/** Handler Container File */
export const getHandlerContainerFileContainersContainerIdFilesFileId: API.OperationMethod<
  GetHandlerContainerFileContainersContainerIdFilesFileIdRequest,
  GetHandlerContainerFileContainersContainerIdFilesFileIdResponse,
  GetHandlerContainerFileContainersContainerIdFilesFileIdError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetHandlerContainerFileContainersContainerIdFilesFileIdRequest,
  output: GetHandlerContainerFileContainersContainerIdFilesFileIdResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetHandlerContainerFileV1ContainersContainerIdFilesFileIdError =
  | UnprocessableEntity
  | LitellmOpError;
/** Handler Container File */
export const getHandlerContainerFileV1ContainersContainerIdFilesFileId: API.OperationMethod<
  GetHandlerContainerFileV1ContainersContainerIdFilesFileIdRequest,
  GetHandlerContainerFileV1ContainersContainerIdFilesFileIdResponse,
  GetHandlerContainerFileV1ContainersContainerIdFilesFileIdError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetHandlerContainerFileV1ContainersContainerIdFilesFileIdRequest,
  output: GetHandlerContainerFileV1ContainersContainerIdFilesFileIdResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetHandlerContainerIdContainersContainerIdFileError =
  | UnprocessableEntity
  | LitellmOpError;
/** Handler Container Id */
export const getHandlerContainerIdContainersContainerIdFile: API.OperationMethod<
  GetHandlerContainerIdContainersContainerIdFileRequest,
  GetHandlerContainerIdContainersContainerIdFileResponse,
  GetHandlerContainerIdContainersContainerIdFileError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetHandlerContainerIdContainersContainerIdFileRequest,
  output: GetHandlerContainerIdContainersContainerIdFileResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetHandlerContainerIdV1ContainersContainerIdFileError =
  | UnprocessableEntity
  | LitellmOpError;
/** Handler Container Id */
export const getHandlerContainerIdV1ContainersContainerIdFile: API.OperationMethod<
  GetHandlerContainerIdV1ContainersContainerIdFileRequest,
  GetHandlerContainerIdV1ContainersContainerIdFileResponse,
  GetHandlerContainerIdV1ContainersContainerIdFileError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetHandlerContainerIdV1ContainersContainerIdFileRequest,
  output: GetHandlerContainerIdV1ContainersContainerIdFileResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type HandlerMultipartUploadContainersContainerIdFilesPostError =
  | UnprocessableEntity
  | LitellmOpError;
/** Handler Multipart Upload */
export const handlerMultipartUploadContainersContainerIdFilesPost: API.OperationMethod<
  HandlerMultipartUploadContainersContainerIdFilesPostRequest,
  HandlerMultipartUploadContainersContainerIdFilesPostResponse,
  HandlerMultipartUploadContainersContainerIdFilesPostError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: HandlerMultipartUploadContainersContainerIdFilesPostRequest,
  output: HandlerMultipartUploadContainersContainerIdFilesPostResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type HandlerMultipartUploadV1ContainersContainerIdFilesPostError =
  | UnprocessableEntity
  | LitellmOpError;
/** Handler Multipart Upload */
export const handlerMultipartUploadV1ContainersContainerIdFilesPost: API.OperationMethod<
  HandlerMultipartUploadV1ContainersContainerIdFilesPostRequest,
  HandlerMultipartUploadV1ContainersContainerIdFilesPostResponse,
  HandlerMultipartUploadV1ContainersContainerIdFilesPostError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: HandlerMultipartUploadV1ContainersContainerIdFilesPostRequest,
  output: HandlerMultipartUploadV1ContainersContainerIdFilesPostResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type ListContainersContainersGetError = LitellmOpError;
/** List Containers Container list endpoint for retrieving a list of containers. Follows the OpenAI Containers API spec: https://platform.openai.com/docs/api-reference/containers Example: ```bash curl -X GET "http://localhost:4000/v1/containers?limit=20&order=desc" -H "Authorization: Bearer sk-1234" ``` Or specify provider via header or query param: ```bash curl -X GET "http://localhost:4000/v1/containers?custom_llm_provider=azure" -H "Authorization: Bearer sk-1234" ``` */
export const listContainersContainersGet: API.OperationMethod<
  ListContainersContainersGetRequest,
  ListContainersContainersGetResponse,
  ListContainersContainersGetError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListContainersContainersGetRequest,
  output: ListContainersContainersGetResponse,
  errors: [],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type ListContainersV1ContainersGetError = LitellmOpError;
/** List Containers Container list endpoint for retrieving a list of containers. Follows the OpenAI Containers API spec: https://platform.openai.com/docs/api-reference/containers Example: ```bash curl -X GET "http://localhost:4000/v1/containers?limit=20&order=desc" -H "Authorization: Bearer sk-1234" ``` Or specify provider via header or query param: ```bash curl -X GET "http://localhost:4000/v1/containers?custom_llm_provider=azure" -H "Authorization: Bearer sk-1234" ``` */
export const listContainersV1ContainersGet: API.OperationMethod<
  ListContainersV1ContainersGetRequest,
  ListContainersV1ContainersGetResponse,
  ListContainersV1ContainersGetError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListContainersV1ContainersGetRequest,
  output: ListContainersV1ContainersGetResponse,
  errors: [],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));
