// AUTO-GENERATED by scripts/generate.ts from .generated-specs (pinned litellm-openapi @ 1.100.0 — see README). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
import * as T from "../traits.ts";
import {
  LitellmProtocol,
  type LitellmOpError,
  type LitellmOpContext,
} from "../protocol.ts";
import * as Retry from "../retry.ts";

export type { LitellmOpError, LitellmOpContext };

export class UnprocessableEntity
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<UnprocessableEntity>()("UnprocessableEntity", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 422 }],
  ) {}

export interface GetCoordinationRedisSettingsCoordinationRedisSettingsGetRequest {}
export const GetCoordinationRedisSettingsCoordinationRedisSettingsGetRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({}).pipe(
      T.Http({ method: "GET", uri: "/coordination_redis/settings", code: 200 }),
    ),
  ).annotate({
    identifier:
      "GetCoordinationRedisSettingsCoordinationRedisSettingsGetRequest",
  }) as any as S.Schema<GetCoordinationRedisSettingsCoordinationRedisSettingsGetRequest>;

export type CoordinationRedisSettingsFieldSection =
  | "connection"
  | "cluster"
  | "sentinel";
export const CoordinationRedisSettingsFieldSection = S.String;

export interface CoordinationRedisSettingsField {
  field_default?: unknown | null;
  field_description: string;
  field_name: string;
  field_type: string;
  field_value?: unknown | null;
  section: CoordinationRedisSettingsFieldSection;
  ui_field_name: string;
}
export const CoordinationRedisSettingsField = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    field_default: S.optional(S.NullOr(S.Unknown)),
    field_description: S.String,
    field_name: S.String,
    field_type: S.String,
    field_value: S.optional(S.NullOr(S.Unknown)),
    section: CoordinationRedisSettingsFieldSection,
    ui_field_name: S.String,
  }),
).annotate({
  identifier: "CoordinationRedisSettingsField",
}) as any as S.Schema<CoordinationRedisSettingsField>;

/** List of all configurable coordination Redis settings with metadata */
export type CoordinationRedisSettingsResponseFieldsList =
  Array<CoordinationRedisSettingsField>;
export const CoordinationRedisSettingsResponseFieldsList =
  /*@__PURE__*/ S.Array(
    CoordinationRedisSettingsField,
  ) as any as S.Schema<CoordinationRedisSettingsResponseFieldsList>;

export type CoordinationRedisSettingsResponseSource =
  | "coordination_redis"
  | "cache_backend"
  | "environment";
export const CoordinationRedisSettingsResponseSource = S.String;

/** Current coordination Redis settings, with credentials redacted */
export type CoordinationRedisSettingsResponseValuesMap = {
  [key: string]: unknown | undefined;
};
export const CoordinationRedisSettingsResponseValuesMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.Unknown,
  ) as any as S.Schema<CoordinationRedisSettingsResponseValuesMap>;

export interface CoordinationRedisSettingsResponse {
  /** List of all configurable coordination Redis settings with metadata */
  fields: CoordinationRedisSettingsResponseFieldsList;
  /** Where the proxy's coordination Redis comes from; null when it has none */
  source: CoordinationRedisSettingsResponseSource | null;
  /** Current coordination Redis settings, with credentials redacted */
  values: CoordinationRedisSettingsResponseValuesMap;
}
export const CoordinationRedisSettingsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    fields: CoordinationRedisSettingsResponseFieldsList,
    source: S.NullOr(CoordinationRedisSettingsResponseSource),
    values: CoordinationRedisSettingsResponseValuesMap,
  }),
).annotate({
  identifier: "CoordinationRedisSettingsResponse",
}) as any as S.Schema<CoordinationRedisSettingsResponse>;

/** Coordination Redis connection params */
export type PostCheckCoordinationRedisConnectionCoordinationRedisSettingsTestRequestSettingsMap =
  { [key: string]: unknown | undefined };
export const PostCheckCoordinationRedisConnectionCoordinationRedisSettingsTestRequestSettingsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.Unknown,
  ) as any as S.Schema<PostCheckCoordinationRedisConnectionCoordinationRedisSettingsTestRequestSettingsMap>;

export interface PostCheckCoordinationRedisConnectionCoordinationRedisSettingsTestRequest {
  /** Coordination Redis connection params */
  settings: PostCheckCoordinationRedisConnectionCoordinationRedisSettingsTestRequestSettingsMap;
}
export const PostCheckCoordinationRedisConnectionCoordinationRedisSettingsTestRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      settings:
        PostCheckCoordinationRedisConnectionCoordinationRedisSettingsTestRequestSettingsMap,
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/coordination_redis/settings/test",
        code: 200,
      }),
    ),
  ).annotate({
    identifier:
      "PostCheckCoordinationRedisConnectionCoordinationRedisSettingsTestRequest",
  }) as any as S.Schema<PostCheckCoordinationRedisConnectionCoordinationRedisSettingsTestRequest>;

export interface CoordinationRedisTestResponse {
  /** Error message if the connection failed */
  error?: string | null;
  /** Connection status: 'healthy' or 'unhealthy' */
  status: string;
}
export const CoordinationRedisTestResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    error: S.optional(S.NullOr(S.String)),
    status: S.String,
  }),
).annotate({
  identifier: "CoordinationRedisTestResponse",
}) as any as S.Schema<CoordinationRedisTestResponse>;

/** Coordination Redis connection params */
export type UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostRequestSettingsMap =
  { [key: string]: unknown | undefined };
export const UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostRequestSettingsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.Unknown,
  ) as any as S.Schema<UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostRequestSettingsMap>;

export interface UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostRequest {
  /** Coordination Redis connection params */
  settings: UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostRequestSettingsMap;
}
export const UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      settings:
        UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostRequestSettingsMap,
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/coordination_redis/settings",
        code: 200,
      }),
    ),
  ).annotate({
    identifier:
      "UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostRequest",
  }) as any as S.Schema<UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostRequest>;

export type UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostResponseBodyMap =
  { [key: string]: unknown | undefined };
export const UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostResponseBodyMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.Unknown,
  ) as any as S.Schema<UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostResponseBodyMap>;

export interface UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostResponse {
  body: UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostResponseBodyMap;
}
export const UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostResponseBodyMap,
    }),
  ).annotate({
    identifier:
      "UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostResponse",
  }) as any as S.Schema<UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostResponse>;

export type GetCoordinationRedisSettingsCoordinationRedisSettingsGetError =
  LitellmOpError;
/** Get Coordination Redis Settings Get the coordination Redis configuration and available settings. Returns: - values: current coordination Redis settings, with password/sentinel_password/url redacted - fields: all configurable settings with their metadata (type, description, default, section) - source: "coordination_redis" | "cache_backend" | "environment" | null */
export const getCoordinationRedisSettingsCoordinationRedisSettingsGet: API.OperationMethod<
  GetCoordinationRedisSettingsCoordinationRedisSettingsGetRequest,
  CoordinationRedisSettingsResponse,
  GetCoordinationRedisSettingsCoordinationRedisSettingsGetError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetCoordinationRedisSettingsCoordinationRedisSettingsGetRequest,
  output: CoordinationRedisSettingsResponse,
  errors: [],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type PostCheckCoordinationRedisConnectionCoordinationRedisSettingsTestError =
  | UnprocessableEntity
  | LitellmOpError;
/** Check Coordination Redis Connection Test a coordination Redis connection with the provided credentials. Parameters: - settings: dict - Redis connection params to test. Credential fields sent back as `***REDACTED***` fall back to the saved value Builds a throwaway client (never touching global state) and pings it. */
export const postCheckCoordinationRedisConnectionCoordinationRedisSettingsTest: API.OperationMethod<
  PostCheckCoordinationRedisConnectionCoordinationRedisSettingsTestRequest,
  CoordinationRedisTestResponse,
  PostCheckCoordinationRedisConnectionCoordinationRedisSettingsTestError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input:
    PostCheckCoordinationRedisConnectionCoordinationRedisSettingsTestRequest,
  output: CoordinationRedisTestResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostError =
  | UnprocessableEntity
  | LitellmOpError;
/** Update Coordination Redis Settings Save coordination Redis settings under `general_settings.coordination_redis`. Parameters: - settings: dict - Redis connection params (host, port, username, password, url, ssl, startup_nodes, sentinel_nodes, sentinel_password, service_name). Values may be `os.environ/VAR` references, which are stored as written and resolved at startup The settings are written to the `general_settings` row of LiteLLM_Config, which startup merges over the yaml config; the proxy picks them up on its next restart. */
export const updateCoordinationRedisSettingsCoordinationRedisSettingsPost: API.OperationMethod<
  UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostRequest,
  UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostResponse,
  UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostRequest,
  output: UpdateCoordinationRedisSettingsCoordinationRedisSettingsPostResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));
