// AUTO-GENERATED by scripts/generate.ts from .generated-specs (pinned litellm-openapi @ 1.100.0 — see README). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
import * as T from "../traits.ts";
import {
  LitellmProtocol,
  type LitellmOpError,
  type LitellmOpContext,
} from "../protocol.ts";
import * as Retry from "../retry.ts";

export type { LitellmOpError, LitellmOpContext };

export class UnprocessableEntity
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<UnprocessableEntity>()("UnprocessableEntity", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 422 }],
  ) {}

export interface DeleteGeminiProxyRouteGeminiEndpointRequest {
  endpoint: string;
}
export const DeleteGeminiProxyRouteGeminiEndpointRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      endpoint: S.String.pipe(T.Label()),
    }).pipe(T.Http({ method: "DELETE", uri: "/gemini/{endpoint}", code: 200 })),
  ).annotate({
    identifier: "DeleteGeminiProxyRouteGeminiEndpointRequest",
  }) as any as S.Schema<DeleteGeminiProxyRouteGeminiEndpointRequest>;

export interface DeleteGeminiProxyRouteGeminiEndpointResponse {
  body: unknown;
}
export const DeleteGeminiProxyRouteGeminiEndpointResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "DeleteGeminiProxyRouteGeminiEndpointResponse",
  }) as any as S.Schema<DeleteGeminiProxyRouteGeminiEndpointResponse>;

export interface GetGeminiProxyRouteGeminiEndpointRequest {
  endpoint: string;
}
export const GetGeminiProxyRouteGeminiEndpointRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      endpoint: S.String.pipe(T.Label()),
    }).pipe(T.Http({ method: "GET", uri: "/gemini/{endpoint}", code: 200 })),
).annotate({
  identifier: "GetGeminiProxyRouteGeminiEndpointRequest",
}) as any as S.Schema<GetGeminiProxyRouteGeminiEndpointRequest>;

export interface GetGeminiProxyRouteGeminiEndpointResponse {
  body: unknown;
}
export const GetGeminiProxyRouteGeminiEndpointResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "GetGeminiProxyRouteGeminiEndpointResponse",
  }) as any as S.Schema<GetGeminiProxyRouteGeminiEndpointResponse>;

export interface PatchGeminiProxyRouteGeminiEndpointRequest {
  endpoint: string;
}
export const PatchGeminiProxyRouteGeminiEndpointRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      endpoint: S.String.pipe(T.Label()),
    }).pipe(T.Http({ method: "PATCH", uri: "/gemini/{endpoint}", code: 200 })),
  ).annotate({
    identifier: "PatchGeminiProxyRouteGeminiEndpointRequest",
  }) as any as S.Schema<PatchGeminiProxyRouteGeminiEndpointRequest>;

export interface PatchGeminiProxyRouteGeminiEndpointResponse {
  body: unknown;
}
export const PatchGeminiProxyRouteGeminiEndpointResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "PatchGeminiProxyRouteGeminiEndpointResponse",
  }) as any as S.Schema<PatchGeminiProxyRouteGeminiEndpointResponse>;

export interface PostGeminiProxyRouteGeminiEndpointRequest {
  endpoint: string;
}
export const PostGeminiProxyRouteGeminiEndpointRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      endpoint: S.String.pipe(T.Label()),
    }).pipe(T.Http({ method: "POST", uri: "/gemini/{endpoint}", code: 200 })),
  ).annotate({
    identifier: "PostGeminiProxyRouteGeminiEndpointRequest",
  }) as any as S.Schema<PostGeminiProxyRouteGeminiEndpointRequest>;

export interface PostGeminiProxyRouteGeminiEndpointResponse {
  body: unknown;
}
export const PostGeminiProxyRouteGeminiEndpointResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "PostGeminiProxyRouteGeminiEndpointResponse",
  }) as any as S.Schema<PostGeminiProxyRouteGeminiEndpointResponse>;

export interface PutGeminiProxyRouteGeminiEndpointRequest {
  endpoint: string;
}
export const PutGeminiProxyRouteGeminiEndpointRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      endpoint: S.String.pipe(T.Label()),
    }).pipe(T.Http({ method: "PUT", uri: "/gemini/{endpoint}", code: 200 })),
).annotate({
  identifier: "PutGeminiProxyRouteGeminiEndpointRequest",
}) as any as S.Schema<PutGeminiProxyRouteGeminiEndpointRequest>;

export interface PutGeminiProxyRouteGeminiEndpointResponse {
  body: unknown;
}
export const PutGeminiProxyRouteGeminiEndpointResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "PutGeminiProxyRouteGeminiEndpointResponse",
  }) as any as S.Schema<PutGeminiProxyRouteGeminiEndpointResponse>;

export type DeleteGeminiProxyRouteGeminiEndpointError =
  | UnprocessableEntity
  | LitellmOpError;
/** Gemini Proxy Route [Docs](https://docs.litellm.ai/docs/pass_through/google_ai_studio) */
export const deleteGeminiProxyRouteGeminiEndpoint: API.OperationMethod<
  DeleteGeminiProxyRouteGeminiEndpointRequest,
  DeleteGeminiProxyRouteGeminiEndpointResponse,
  DeleteGeminiProxyRouteGeminiEndpointError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteGeminiProxyRouteGeminiEndpointRequest,
  output: DeleteGeminiProxyRouteGeminiEndpointResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetGeminiProxyRouteGeminiEndpointError =
  | UnprocessableEntity
  | LitellmOpError;
/** Gemini Proxy Route [Docs](https://docs.litellm.ai/docs/pass_through/google_ai_studio) */
export const getGeminiProxyRouteGeminiEndpoint: API.OperationMethod<
  GetGeminiProxyRouteGeminiEndpointRequest,
  GetGeminiProxyRouteGeminiEndpointResponse,
  GetGeminiProxyRouteGeminiEndpointError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetGeminiProxyRouteGeminiEndpointRequest,
  output: GetGeminiProxyRouteGeminiEndpointResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type PatchGeminiProxyRouteGeminiEndpointError =
  | UnprocessableEntity
  | LitellmOpError;
/** Gemini Proxy Route [Docs](https://docs.litellm.ai/docs/pass_through/google_ai_studio) */
export const patchGeminiProxyRouteGeminiEndpoint: API.OperationMethod<
  PatchGeminiProxyRouteGeminiEndpointRequest,
  PatchGeminiProxyRouteGeminiEndpointResponse,
  PatchGeminiProxyRouteGeminiEndpointError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PatchGeminiProxyRouteGeminiEndpointRequest,
  output: PatchGeminiProxyRouteGeminiEndpointResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type PostGeminiProxyRouteGeminiEndpointError =
  | UnprocessableEntity
  | LitellmOpError;
/** Gemini Proxy Route [Docs](https://docs.litellm.ai/docs/pass_through/google_ai_studio) */
export const postGeminiProxyRouteGeminiEndpoint: API.OperationMethod<
  PostGeminiProxyRouteGeminiEndpointRequest,
  PostGeminiProxyRouteGeminiEndpointResponse,
  PostGeminiProxyRouteGeminiEndpointError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PostGeminiProxyRouteGeminiEndpointRequest,
  output: PostGeminiProxyRouteGeminiEndpointResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type PutGeminiProxyRouteGeminiEndpointError =
  | UnprocessableEntity
  | LitellmOpError;
/** Gemini Proxy Route [Docs](https://docs.litellm.ai/docs/pass_through/google_ai_studio) */
export const putGeminiProxyRouteGeminiEndpoint: API.OperationMethod<
  PutGeminiProxyRouteGeminiEndpointRequest,
  PutGeminiProxyRouteGeminiEndpointResponse,
  PutGeminiProxyRouteGeminiEndpointError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PutGeminiProxyRouteGeminiEndpointRequest,
  output: PutGeminiProxyRouteGeminiEndpointResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));
