// AUTO-GENERATED by scripts/generate.ts from .generated-specs (pinned litellm-openapi @ 1.100.0 — see README). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
import * as T from "../traits.ts";
import {
  LitellmProtocol,
  type LitellmOpError,
  type LitellmOpContext,
} from "../protocol.ts";
import * as Retry from "../retry.ts";

export type { LitellmOpError, LitellmOpContext };

export class UnprocessableEntity
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<UnprocessableEntity>()("UnprocessableEntity", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 422 }],
  ) {}

export interface ListToolRestApiMcpRestToolsListGetRequest {
  /** The server id to list tools for */
  server_id?: string;
  /** Filter tools to a single MCP server by name or alias */
  mcp_server_name?: string;
  /** Filter tools to a single toolset by name */
  toolset_name?: string;
  /** Admin only. Return the full server tool catalog without the allowed_tools filter or per-key tool permissions, so the MCP settings UI can configure the allowlist. Ignored for non-admins. */
  include_disabled_tools?: boolean;
}
export const ListToolRestApiMcpRestToolsListGetRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      server_id: S.optional(S.String.pipe(T.Query())),
      mcp_server_name: S.optional(S.String.pipe(T.Query())),
      toolset_name: S.optional(S.String.pipe(T.Query())),
      include_disabled_tools: S.optional(S.Boolean.pipe(T.Query())),
    }).pipe(T.Http({ method: "GET", uri: "/mcp-rest/tools/list", code: 200 })),
  ).annotate({
    identifier: "ListToolRestApiMcpRestToolsListGetRequest",
  }) as any as S.Schema<ListToolRestApiMcpRestToolsListGetRequest>;

export type ListToolRestApiMcpRestToolsListGetResponseBodyMap = {
  [key: string]: unknown | undefined;
};
export const ListToolRestApiMcpRestToolsListGetResponseBodyMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.Unknown,
  ) as any as S.Schema<ListToolRestApiMcpRestToolsListGetResponseBodyMap>;

export interface ListToolRestApiMcpRestToolsListGetResponse {
  body: ListToolRestApiMcpRestToolsListGetResponseBodyMap;
}
export const ListToolRestApiMcpRestToolsListGetResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: ListToolRestApiMcpRestToolsListGetResponseBodyMap,
    }),
  ).annotate({
    identifier: "ListToolRestApiMcpRestToolsListGetResponse",
  }) as any as S.Schema<ListToolRestApiMcpRestToolsListGetResponse>;

export interface PostCallToolRestApiMcpRestToolsCallRequest {}
export const PostCallToolRestApiMcpRestToolsCallRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({}).pipe(
      T.Http({ method: "POST", uri: "/mcp-rest/tools/call", code: 200 }),
    ),
  ).annotate({
    identifier: "PostCallToolRestApiMcpRestToolsCallRequest",
  }) as any as S.Schema<PostCallToolRestApiMcpRestToolsCallRequest>;

export interface PostCallToolRestApiMcpRestToolsCallResponse {
  body: unknown;
}
export const PostCallToolRestApiMcpRestToolsCallResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "PostCallToolRestApiMcpRestToolsCallResponse",
  }) as any as S.Schema<PostCallToolRestApiMcpRestToolsCallResponse>;

export type PostTestConnectionMcpRestTestConnectionRequestAllowedToolsList =
  Array<string>;
export const PostTestConnectionMcpRestTestConnectionRequestAllowedToolsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<PostTestConnectionMcpRestTestConnectionRequestAllowedToolsList>;

export type PostTestConnectionMcpRestTestConnectionRequestArgsList =
  Array<string>;
export const PostTestConnectionMcpRestTestConnectionRequestArgsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<PostTestConnectionMcpRestTestConnectionRequestArgsList>;

export type PostTestConnectionMcpRestTestConnectionRequestAuthType =
  | "none"
  | "api_key"
  | "bearer_token"
  | "basic"
  | "authorization"
  | "oauth2"
  | "aws_sigv4"
  | "token"
  | "oauth2_token_exchange"
  | "oauth2_id_jag"
  | "true_passthrough"
  | "oauth_delegate";
export const PostTestConnectionMcpRestTestConnectionRequestAuthType = S.String;

export type PostTestConnectionMcpRestTestConnectionRequestByokDescriptionList =
  Array<string>;
export const PostTestConnectionMcpRestTestConnectionRequestByokDescriptionList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<PostTestConnectionMcpRestTestConnectionRequestByokDescriptionList>;

export type MCPCredentialsRedirectUrisList = Array<string>;
export const MCPCredentialsRedirectUrisList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<MCPCredentialsRedirectUrisList>;

export type MCPCredentialsScopesList = Array<string>;
export const MCPCredentialsScopesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<MCPCredentialsScopesList>;

export type MCPCredentialsTokenEndpointAuthMethod =
  | "client_secret_basic"
  | "client_secret_post";
export const MCPCredentialsTokenEndpointAuthMethod = S.String;

export interface MCPCredentials {
  audience?: string | null;
  auth_value?: string | null;
  aws_access_key_id?: string | null;
  aws_region_name?: string | null;
  aws_role_name?: string | null;
  aws_secret_access_key?: string | null;
  aws_service_name?: string | null;
  aws_session_name?: string | null;
  aws_session_token?: string | null;
  client_assertion_signing_alg?: string | null;
  client_id?: string | null;
  client_private_key?: string | null;
  client_private_key_id?: string | null;
  client_secret?: string | null;
  id_jag_resource?: string | null;
  id_jag_resource_token_endpoint?: string | null;
  redirect_uris?: MCPCredentialsRedirectUrisList | null;
  scopes?: MCPCredentialsScopesList | null;
  subject_token_type?: string | null;
  token_endpoint_auth_method?:
    | MCPCredentialsTokenEndpointAuthMethod
    | (string & {})
    | null;
  token_exchange_endpoint?: string | null;
  token_exchange_profile?: string | null;
  upstream_resource?: string | null;
  upstream_token_header?: string | null;
}
export const MCPCredentials = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    audience: S.optional(S.NullOr(S.String)),
    auth_value: S.optional(S.NullOr(S.String)),
    aws_access_key_id: S.optional(S.NullOr(S.String)),
    aws_region_name: S.optional(S.NullOr(S.String)),
    aws_role_name: S.optional(S.NullOr(S.String)),
    aws_secret_access_key: S.optional(S.NullOr(S.String)),
    aws_service_name: S.optional(S.NullOr(S.String)),
    aws_session_name: S.optional(S.NullOr(S.String)),
    aws_session_token: S.optional(S.NullOr(S.String)),
    client_assertion_signing_alg: S.optional(S.NullOr(S.String)),
    client_id: S.optional(S.NullOr(S.String)),
    client_private_key: S.optional(S.NullOr(S.String)),
    client_private_key_id: S.optional(S.NullOr(S.String)),
    client_secret: S.optional(S.NullOr(S.String)),
    id_jag_resource: S.optional(S.NullOr(S.String)),
    id_jag_resource_token_endpoint: S.optional(S.NullOr(S.String)),
    redirect_uris: S.optional(S.NullOr(MCPCredentialsRedirectUrisList)),
    scopes: S.optional(S.NullOr(MCPCredentialsScopesList)),
    subject_token_type: S.optional(S.NullOr(S.String)),
    token_endpoint_auth_method: S.optional(
      S.NullOr(MCPCredentialsTokenEndpointAuthMethod),
    ),
    token_exchange_endpoint: S.optional(S.NullOr(S.String)),
    token_exchange_profile: S.optional(S.NullOr(S.String)),
    upstream_resource: S.optional(S.NullOr(S.String)),
    upstream_token_header: S.optional(S.NullOr(S.String)),
  }),
).annotate({ identifier: "MCPCredentials" }) as any as S.Schema<MCPCredentials>;

export type PostTestConnectionMcpRestTestConnectionRequestEnvMap = {
  [key: string]: string | undefined;
};
export const PostTestConnectionMcpRestTestConnectionRequestEnvMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<PostTestConnectionMcpRestTestConnectionRequestEnvMap>;

/** Scope for an MCP server environment variable. - ``global``: value is provided by the admin and used for all users. - ``user``: each user must provide their own value via the per-user env-var endpoint. The admin-supplied ``value`` is treated as a placeholder/hint and is not used at request time. */
export type MCPEnvVarScope = "global" | "user";
export const MCPEnvVarScope = S.String;

/** One environment variable for an MCP server. Variables can be interpolated into ``static_headers`` using ``${NAME}`` syntax. ``scope=global`` values are stored on the server. ``scope=user`` values are stored per-user in ``LiteLLM_MCPUserEnvVars`` and supplied by each user. */
export interface MCPEnvVar {
  description?: string | null;
  name: string;
  scope?: MCPEnvVarScope | (string & {});
  value?: string;
}
export const MCPEnvVar = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    description: S.optional(S.NullOr(S.String)),
    name: S.String,
    scope: S.optional(MCPEnvVarScope),
    value: S.optional(S.String),
  }),
).annotate({ identifier: "MCPEnvVar" }) as any as S.Schema<MCPEnvVar>;

export type PostTestConnectionMcpRestTestConnectionRequestEnvVarsList =
  Array<MCPEnvVar>;
export const PostTestConnectionMcpRestTestConnectionRequestEnvVarsList =
  /*@__PURE__*/ S.Array(
    MCPEnvVar,
  ) as any as S.Schema<PostTestConnectionMcpRestTestConnectionRequestEnvVarsList>;

export type PostTestConnectionMcpRestTestConnectionRequestExtraHeadersList =
  Array<string>;
export const PostTestConnectionMcpRestTestConnectionRequestExtraHeadersList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<PostTestConnectionMcpRestTestConnectionRequestExtraHeadersList>;

export type PostTestConnectionMcpRestTestConnectionRequestMcpAccessGroupsList =
  Array<string>;
export const PostTestConnectionMcpRestTestConnectionRequestMcpAccessGroupsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<PostTestConnectionMcpRestTestConnectionRequestMcpAccessGroupsList>;

export type PostTestConnectionMcpRestTestConnectionRequestMcpInfoMap = {
  [key: string]: unknown | undefined;
};
export const PostTestConnectionMcpRestTestConnectionRequestMcpInfoMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.Unknown,
  ) as any as S.Schema<PostTestConnectionMcpRestTestConnectionRequestMcpInfoMap>;

export type PostTestConnectionMcpRestTestConnectionRequestOauth2Flow =
  | "client_credentials"
  | "authorization_code";
export const PostTestConnectionMcpRestTestConnectionRequestOauth2Flow =
  S.String;

export type PostTestConnectionMcpRestTestConnectionRequestStaticHeadersMap = {
  [key: string]: string | undefined;
};
export const PostTestConnectionMcpRestTestConnectionRequestStaticHeadersMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<PostTestConnectionMcpRestTestConnectionRequestStaticHeadersMap>;

export type PostTestConnectionMcpRestTestConnectionRequestToolNameToDescriptionMap =
  { [key: string]: string | undefined };
export const PostTestConnectionMcpRestTestConnectionRequestToolNameToDescriptionMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<PostTestConnectionMcpRestTestConnectionRequestToolNameToDescriptionMap>;

export type PostTestConnectionMcpRestTestConnectionRequestToolNameToDisplayNameMap =
  { [key: string]: string | undefined };
export const PostTestConnectionMcpRestTestConnectionRequestToolNameToDisplayNameMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<PostTestConnectionMcpRestTestConnectionRequestToolNameToDisplayNameMap>;

export type PostTestConnectionMcpRestTestConnectionRequestTransport =
  | "sse"
  | "http"
  | "stdio";
export const PostTestConnectionMcpRestTestConnectionRequestTransport = S.String;

export interface PostTestConnectionMcpRestTestConnectionRequest {
  alias?: string | null;
  allow_all_keys?: boolean;
  allowed_tools?: PostTestConnectionMcpRestTestConnectionRequestAllowedToolsList | null;
  /** Server-managed: set by the endpoint; caller values are overridden. */
  approval_status?: string | null;
  args?: PostTestConnectionMcpRestTestConnectionRequestArgsList;
  audience?: string | null;
  auth_type?:
    | PostTestConnectionMcpRestTestConnectionRequestAuthType
    | (string & {})
    | null;
  authorization_url?: string | null;
  available_on_public_internet?: boolean;
  byok_api_key_help_url?: string | null;
  byok_description?: PostTestConnectionMcpRestTestConnectionRequestByokDescriptionList;
  command?: string | null;
  credentials?: MCPCredentials | null;
  dcr_bridge?: boolean | null;
  delegate_auth_to_upstream?: boolean;
  description?: string | null;
  env?: PostTestConnectionMcpRestTestConnectionRequestEnvMap;
  env_vars?: PostTestConnectionMcpRestTestConnectionRequestEnvVarsList | null;
  extra_headers?: PostTestConnectionMcpRestTestConnectionRequestExtraHeadersList | null;
  instructions?: string | null;
  is_byok?: boolean;
  issuer?: string | null;
  max_concurrent_requests?: number | null;
  mcp_access_groups?: PostTestConnectionMcpRestTestConnectionRequestMcpAccessGroupsList;
  mcp_info?: PostTestConnectionMcpRestTestConnectionRequestMcpInfoMap | null;
  oauth2_flow?:
    | PostTestConnectionMcpRestTestConnectionRequestOauth2Flow
    | (string & {})
    | null;
  oauth_passthrough?: boolean;
  registration_url?: string | null;
  server_id?: string | null;
  server_name?: string | null;
  source_url?: string | null;
  spec_path?: string | null;
  static_headers?: PostTestConnectionMcpRestTestConnectionRequestStaticHeadersMap | null;
  subject_token_type?: string | null;
  /** Server-managed: set by the endpoint; caller values are overridden. */
  submitted_at?: string | null;
  /** Server-managed: set by the endpoint; caller values are overridden. */
  submitted_by?: string | null;
  timeout?: number | null;
  token_exchange_endpoint?: string | null;
  token_exchange_profile?: string | null;
  token_url?: string | null;
  tool_name_to_description?: PostTestConnectionMcpRestTestConnectionRequestToolNameToDescriptionMap | null;
  tool_name_to_display_name?: PostTestConnectionMcpRestTestConnectionRequestToolNameToDisplayNameMap | null;
  transport?:
    | PostTestConnectionMcpRestTestConnectionRequestTransport
    | (string & {});
  url?: string | null;
}
export const PostTestConnectionMcpRestTestConnectionRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      alias: S.optional(S.NullOr(S.String)),
      allow_all_keys: S.optional(S.Boolean),
      allowed_tools: S.optional(
        S.NullOr(
          PostTestConnectionMcpRestTestConnectionRequestAllowedToolsList,
        ),
      ),
      approval_status: S.optional(S.NullOr(S.String)),
      args: S.optional(PostTestConnectionMcpRestTestConnectionRequestArgsList),
      audience: S.optional(S.NullOr(S.String)),
      auth_type: S.optional(
        S.NullOr(PostTestConnectionMcpRestTestConnectionRequestAuthType),
      ),
      authorization_url: S.optional(S.NullOr(S.String)),
      available_on_public_internet: S.optional(S.Boolean),
      byok_api_key_help_url: S.optional(S.NullOr(S.String)),
      byok_description: S.optional(
        PostTestConnectionMcpRestTestConnectionRequestByokDescriptionList,
      ),
      command: S.optional(S.NullOr(S.String)),
      credentials: S.optional(S.NullOr(MCPCredentials)),
      dcr_bridge: S.optional(S.NullOr(S.Boolean)),
      delegate_auth_to_upstream: S.optional(S.Boolean),
      description: S.optional(S.NullOr(S.String)),
      env: S.optional(PostTestConnectionMcpRestTestConnectionRequestEnvMap),
      env_vars: S.optional(
        S.NullOr(PostTestConnectionMcpRestTestConnectionRequestEnvVarsList),
      ),
      extra_headers: S.optional(
        S.NullOr(
          PostTestConnectionMcpRestTestConnectionRequestExtraHeadersList,
        ),
      ),
      instructions: S.optional(S.NullOr(S.String)),
      is_byok: S.optional(S.Boolean),
      issuer: S.optional(S.NullOr(S.String)),
      max_concurrent_requests: S.optional(S.NullOr(S.Number)),
      mcp_access_groups: S.optional(
        PostTestConnectionMcpRestTestConnectionRequestMcpAccessGroupsList,
      ),
      mcp_info: S.optional(
        S.NullOr(PostTestConnectionMcpRestTestConnectionRequestMcpInfoMap),
      ),
      oauth2_flow: S.optional(
        S.NullOr(PostTestConnectionMcpRestTestConnectionRequestOauth2Flow),
      ),
      oauth_passthrough: S.optional(S.Boolean),
      registration_url: S.optional(S.NullOr(S.String)),
      server_id: S.optional(S.NullOr(S.String)),
      server_name: S.optional(S.NullOr(S.String)),
      source_url: S.optional(S.NullOr(S.String)),
      spec_path: S.optional(S.NullOr(S.String)),
      static_headers: S.optional(
        S.NullOr(
          PostTestConnectionMcpRestTestConnectionRequestStaticHeadersMap,
        ),
      ),
      subject_token_type: S.optional(S.NullOr(S.String)),
      submitted_at: S.optional(S.NullOr(S.String)),
      submitted_by: S.optional(S.NullOr(S.String)),
      timeout: S.optional(S.NullOr(S.Number)),
      token_exchange_endpoint: S.optional(S.NullOr(S.String)),
      token_exchange_profile: S.optional(S.NullOr(S.String)),
      token_url: S.optional(S.NullOr(S.String)),
      tool_name_to_description: S.optional(
        S.NullOr(
          PostTestConnectionMcpRestTestConnectionRequestToolNameToDescriptionMap,
        ),
      ),
      tool_name_to_display_name: S.optional(
        S.NullOr(
          PostTestConnectionMcpRestTestConnectionRequestToolNameToDisplayNameMap,
        ),
      ),
      transport: S.optional(
        PostTestConnectionMcpRestTestConnectionRequestTransport,
      ),
      url: S.optional(S.NullOr(S.String)),
    }).pipe(
      T.Http({ method: "POST", uri: "/mcp-rest/test/connection", code: 200 }),
    ),
  ).annotate({
    identifier: "PostTestConnectionMcpRestTestConnectionRequest",
  }) as any as S.Schema<PostTestConnectionMcpRestTestConnectionRequest>;

export interface PostTestConnectionMcpRestTestConnectionResponse {
  body: unknown;
}
export const PostTestConnectionMcpRestTestConnectionResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "PostTestConnectionMcpRestTestConnectionResponse",
  }) as any as S.Schema<PostTestConnectionMcpRestTestConnectionResponse>;

export type TestToolsListMcpRestTestToolsListPostRequestAllowedToolsList =
  Array<string>;
export const TestToolsListMcpRestTestToolsListPostRequestAllowedToolsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<TestToolsListMcpRestTestToolsListPostRequestAllowedToolsList>;

export type TestToolsListMcpRestTestToolsListPostRequestArgsList =
  Array<string>;
export const TestToolsListMcpRestTestToolsListPostRequestArgsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<TestToolsListMcpRestTestToolsListPostRequestArgsList>;

export type TestToolsListMcpRestTestToolsListPostRequestAuthType =
  | "none"
  | "api_key"
  | "bearer_token"
  | "basic"
  | "authorization"
  | "oauth2"
  | "aws_sigv4"
  | "token"
  | "oauth2_token_exchange"
  | "oauth2_id_jag"
  | "true_passthrough"
  | "oauth_delegate";
export const TestToolsListMcpRestTestToolsListPostRequestAuthType = S.String;

export type TestToolsListMcpRestTestToolsListPostRequestByokDescriptionList =
  Array<string>;
export const TestToolsListMcpRestTestToolsListPostRequestByokDescriptionList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<TestToolsListMcpRestTestToolsListPostRequestByokDescriptionList>;

export type TestToolsListMcpRestTestToolsListPostRequestEnvMap = {
  [key: string]: string | undefined;
};
export const TestToolsListMcpRestTestToolsListPostRequestEnvMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<TestToolsListMcpRestTestToolsListPostRequestEnvMap>;

export type TestToolsListMcpRestTestToolsListPostRequestEnvVarsList =
  Array<MCPEnvVar>;
export const TestToolsListMcpRestTestToolsListPostRequestEnvVarsList =
  /*@__PURE__*/ S.Array(
    MCPEnvVar,
  ) as any as S.Schema<TestToolsListMcpRestTestToolsListPostRequestEnvVarsList>;

export type TestToolsListMcpRestTestToolsListPostRequestExtraHeadersList =
  Array<string>;
export const TestToolsListMcpRestTestToolsListPostRequestExtraHeadersList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<TestToolsListMcpRestTestToolsListPostRequestExtraHeadersList>;

export type TestToolsListMcpRestTestToolsListPostRequestMcpAccessGroupsList =
  Array<string>;
export const TestToolsListMcpRestTestToolsListPostRequestMcpAccessGroupsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<TestToolsListMcpRestTestToolsListPostRequestMcpAccessGroupsList>;

export type TestToolsListMcpRestTestToolsListPostRequestMcpInfoMap = {
  [key: string]: unknown | undefined;
};
export const TestToolsListMcpRestTestToolsListPostRequestMcpInfoMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.Unknown,
  ) as any as S.Schema<TestToolsListMcpRestTestToolsListPostRequestMcpInfoMap>;

export type TestToolsListMcpRestTestToolsListPostRequestOauth2Flow =
  | "client_credentials"
  | "authorization_code";
export const TestToolsListMcpRestTestToolsListPostRequestOauth2Flow = S.String;

export type TestToolsListMcpRestTestToolsListPostRequestStaticHeadersMap = {
  [key: string]: string | undefined;
};
export const TestToolsListMcpRestTestToolsListPostRequestStaticHeadersMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<TestToolsListMcpRestTestToolsListPostRequestStaticHeadersMap>;

export type TestToolsListMcpRestTestToolsListPostRequestToolNameToDescriptionMap =
  { [key: string]: string | undefined };
export const TestToolsListMcpRestTestToolsListPostRequestToolNameToDescriptionMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<TestToolsListMcpRestTestToolsListPostRequestToolNameToDescriptionMap>;

export type TestToolsListMcpRestTestToolsListPostRequestToolNameToDisplayNameMap =
  { [key: string]: string | undefined };
export const TestToolsListMcpRestTestToolsListPostRequestToolNameToDisplayNameMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<TestToolsListMcpRestTestToolsListPostRequestToolNameToDisplayNameMap>;

export type TestToolsListMcpRestTestToolsListPostRequestTransport =
  | "sse"
  | "http"
  | "stdio";
export const TestToolsListMcpRestTestToolsListPostRequestTransport = S.String;

export interface TestToolsListMcpRestTestToolsListPostRequest {
  alias?: string | null;
  allow_all_keys?: boolean;
  allowed_tools?: TestToolsListMcpRestTestToolsListPostRequestAllowedToolsList | null;
  /** Server-managed: set by the endpoint; caller values are overridden. */
  approval_status?: string | null;
  args?: TestToolsListMcpRestTestToolsListPostRequestArgsList;
  audience?: string | null;
  auth_type?:
    | TestToolsListMcpRestTestToolsListPostRequestAuthType
    | (string & {})
    | null;
  authorization_url?: string | null;
  available_on_public_internet?: boolean;
  byok_api_key_help_url?: string | null;
  byok_description?: TestToolsListMcpRestTestToolsListPostRequestByokDescriptionList;
  command?: string | null;
  credentials?: MCPCredentials | null;
  dcr_bridge?: boolean | null;
  delegate_auth_to_upstream?: boolean;
  description?: string | null;
  env?: TestToolsListMcpRestTestToolsListPostRequestEnvMap;
  env_vars?: TestToolsListMcpRestTestToolsListPostRequestEnvVarsList | null;
  extra_headers?: TestToolsListMcpRestTestToolsListPostRequestExtraHeadersList | null;
  instructions?: string | null;
  is_byok?: boolean;
  issuer?: string | null;
  max_concurrent_requests?: number | null;
  mcp_access_groups?: TestToolsListMcpRestTestToolsListPostRequestMcpAccessGroupsList;
  mcp_info?: TestToolsListMcpRestTestToolsListPostRequestMcpInfoMap | null;
  oauth2_flow?:
    | TestToolsListMcpRestTestToolsListPostRequestOauth2Flow
    | (string & {})
    | null;
  oauth_passthrough?: boolean;
  registration_url?: string | null;
  server_id?: string | null;
  server_name?: string | null;
  source_url?: string | null;
  spec_path?: string | null;
  static_headers?: TestToolsListMcpRestTestToolsListPostRequestStaticHeadersMap | null;
  subject_token_type?: string | null;
  /** Server-managed: set by the endpoint; caller values are overridden. */
  submitted_at?: string | null;
  /** Server-managed: set by the endpoint; caller values are overridden. */
  submitted_by?: string | null;
  timeout?: number | null;
  token_exchange_endpoint?: string | null;
  token_exchange_profile?: string | null;
  token_url?: string | null;
  tool_name_to_description?: TestToolsListMcpRestTestToolsListPostRequestToolNameToDescriptionMap | null;
  tool_name_to_display_name?: TestToolsListMcpRestTestToolsListPostRequestToolNameToDisplayNameMap | null;
  transport?:
    | TestToolsListMcpRestTestToolsListPostRequestTransport
    | (string & {});
  url?: string | null;
}
export const TestToolsListMcpRestTestToolsListPostRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      alias: S.optional(S.NullOr(S.String)),
      allow_all_keys: S.optional(S.Boolean),
      allowed_tools: S.optional(
        S.NullOr(TestToolsListMcpRestTestToolsListPostRequestAllowedToolsList),
      ),
      approval_status: S.optional(S.NullOr(S.String)),
      args: S.optional(TestToolsListMcpRestTestToolsListPostRequestArgsList),
      audience: S.optional(S.NullOr(S.String)),
      auth_type: S.optional(
        S.NullOr(TestToolsListMcpRestTestToolsListPostRequestAuthType),
      ),
      authorization_url: S.optional(S.NullOr(S.String)),
      available_on_public_internet: S.optional(S.Boolean),
      byok_api_key_help_url: S.optional(S.NullOr(S.String)),
      byok_description: S.optional(
        TestToolsListMcpRestTestToolsListPostRequestByokDescriptionList,
      ),
      command: S.optional(S.NullOr(S.String)),
      credentials: S.optional(S.NullOr(MCPCredentials)),
      dcr_bridge: S.optional(S.NullOr(S.Boolean)),
      delegate_auth_to_upstream: S.optional(S.Boolean),
      description: S.optional(S.NullOr(S.String)),
      env: S.optional(TestToolsListMcpRestTestToolsListPostRequestEnvMap),
      env_vars: S.optional(
        S.NullOr(TestToolsListMcpRestTestToolsListPostRequestEnvVarsList),
      ),
      extra_headers: S.optional(
        S.NullOr(TestToolsListMcpRestTestToolsListPostRequestExtraHeadersList),
      ),
      instructions: S.optional(S.NullOr(S.String)),
      is_byok: S.optional(S.Boolean),
      issuer: S.optional(S.NullOr(S.String)),
      max_concurrent_requests: S.optional(S.NullOr(S.Number)),
      mcp_access_groups: S.optional(
        TestToolsListMcpRestTestToolsListPostRequestMcpAccessGroupsList,
      ),
      mcp_info: S.optional(
        S.NullOr(TestToolsListMcpRestTestToolsListPostRequestMcpInfoMap),
      ),
      oauth2_flow: S.optional(
        S.NullOr(TestToolsListMcpRestTestToolsListPostRequestOauth2Flow),
      ),
      oauth_passthrough: S.optional(S.Boolean),
      registration_url: S.optional(S.NullOr(S.String)),
      server_id: S.optional(S.NullOr(S.String)),
      server_name: S.optional(S.NullOr(S.String)),
      source_url: S.optional(S.NullOr(S.String)),
      spec_path: S.optional(S.NullOr(S.String)),
      static_headers: S.optional(
        S.NullOr(TestToolsListMcpRestTestToolsListPostRequestStaticHeadersMap),
      ),
      subject_token_type: S.optional(S.NullOr(S.String)),
      submitted_at: S.optional(S.NullOr(S.String)),
      submitted_by: S.optional(S.NullOr(S.String)),
      timeout: S.optional(S.NullOr(S.Number)),
      token_exchange_endpoint: S.optional(S.NullOr(S.String)),
      token_exchange_profile: S.optional(S.NullOr(S.String)),
      token_url: S.optional(S.NullOr(S.String)),
      tool_name_to_description: S.optional(
        S.NullOr(
          TestToolsListMcpRestTestToolsListPostRequestToolNameToDescriptionMap,
        ),
      ),
      tool_name_to_display_name: S.optional(
        S.NullOr(
          TestToolsListMcpRestTestToolsListPostRequestToolNameToDisplayNameMap,
        ),
      ),
      transport: S.optional(
        TestToolsListMcpRestTestToolsListPostRequestTransport,
      ),
      url: S.optional(S.NullOr(S.String)),
    }).pipe(
      T.Http({ method: "POST", uri: "/mcp-rest/test/tools/list", code: 200 }),
    ),
  ).annotate({
    identifier: "TestToolsListMcpRestTestToolsListPostRequest",
  }) as any as S.Schema<TestToolsListMcpRestTestToolsListPostRequest>;

export interface TestToolsListMcpRestTestToolsListPostResponse {
  body: unknown;
}
export const TestToolsListMcpRestTestToolsListPostResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "TestToolsListMcpRestTestToolsListPostResponse",
  }) as any as S.Schema<TestToolsListMcpRestTestToolsListPostResponse>;

export type ListToolRestApiMcpRestToolsListGetError =
  | UnprocessableEntity
  | LitellmOpError;
/** List Tool Rest Api List all available tools with information about the server they belong to. Example response: { "tools": [ { "name": "create_zap", "description": "Create a new zap", "inputSchema": "tool_input_schema", "mcp_info": { "server_name": "zapier", "logo_url": "https://www.zapier.com/logo.png", "server_id": "a1b2c3d4-...", "alias": "zapier_prod", } } ], "error": null, "message": "Successfully retrieved tools" } */
export const listToolRestApiMcpRestToolsListGet: API.OperationMethod<
  ListToolRestApiMcpRestToolsListGetRequest,
  ListToolRestApiMcpRestToolsListGetResponse,
  ListToolRestApiMcpRestToolsListGetError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListToolRestApiMcpRestToolsListGetRequest,
  output: ListToolRestApiMcpRestToolsListGetResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type PostCallToolRestApiMcpRestToolsCallError = LitellmOpError;
/** Call Tool Rest Api REST API to call a specific MCP tool with the provided arguments */
export const postCallToolRestApiMcpRestToolsCall: API.OperationMethod<
  PostCallToolRestApiMcpRestToolsCallRequest,
  PostCallToolRestApiMcpRestToolsCallResponse,
  PostCallToolRestApiMcpRestToolsCallError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PostCallToolRestApiMcpRestToolsCallRequest,
  output: PostCallToolRestApiMcpRestToolsCallResponse,
  errors: [],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type PostTestConnectionMcpRestTestConnectionError =
  | UnprocessableEntity
  | LitellmOpError;
/** Test Connection Test if we can connect to the provided MCP server before adding it */
export const postTestConnectionMcpRestTestConnection: API.OperationMethod<
  PostTestConnectionMcpRestTestConnectionRequest,
  PostTestConnectionMcpRestTestConnectionResponse,
  PostTestConnectionMcpRestTestConnectionError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PostTestConnectionMcpRestTestConnectionRequest,
  output: PostTestConnectionMcpRestTestConnectionResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type TestToolsListMcpRestTestToolsListPostError =
  | UnprocessableEntity
  | LitellmOpError;
/** Test Tools List Preview tools available from MCP server before adding it */
export const testToolsListMcpRestTestToolsListPost: API.OperationMethod<
  TestToolsListMcpRestTestToolsListPostRequest,
  TestToolsListMcpRestTestToolsListPostResponse,
  TestToolsListMcpRestTestToolsListPostError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: TestToolsListMcpRestTestToolsListPostRequest,
  output: TestToolsListMcpRestTestToolsListPostResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));
