// AUTO-GENERATED by scripts/generate.ts from .generated-specs (pinned litellm-openapi @ 1.100.0 — see README). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
import * as T from "../traits.ts";
import {
  LitellmProtocol,
  type LitellmOpError,
  type LitellmOpContext,
} from "../protocol.ts";
import * as Retry from "../retry.ts";

export type { LitellmOpError, LitellmOpContext };

export class UnprocessableEntity
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<UnprocessableEntity>()("UnprocessableEntity", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 422 }],
  ) {}

export interface GetOauthAuthorizationServerAggregateWellKnownOauthAuthorizationServerMcpRequest {}
export const GetOauthAuthorizationServerAggregateWellKnownOauthAuthorizationServerMcpRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({}).pipe(
      T.Http({
        method: "GET",
        uri: "/.well-known/oauth-authorization-server/mcp",
        code: 200,
      }),
    ),
  ).annotate({
    identifier:
      "GetOauthAuthorizationServerAggregateWellKnownOauthAuthorizationServerMcpRequest",
  }) as any as S.Schema<GetOauthAuthorizationServerAggregateWellKnownOauthAuthorizationServerMcpRequest>;

export interface GetOauthAuthorizationServerAggregateWellKnownOauthAuthorizationServerMcpResponse {
  body: unknown;
}
export const GetOauthAuthorizationServerAggregateWellKnownOauthAuthorizationServerMcpResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier:
      "GetOauthAuthorizationServerAggregateWellKnownOauthAuthorizationServerMcpResponse",
  }) as any as S.Schema<GetOauthAuthorizationServerAggregateWellKnownOauthAuthorizationServerMcpResponse>;

export interface GetOauthAuthorizationServerLegacyWellKnownOauthAuthorizationServerMcpServerNameMcpRequest {
  mcp_server_name: string;
}
export const GetOauthAuthorizationServerLegacyWellKnownOauthAuthorizationServerMcpServerNameMcpRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      mcp_server_name: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/.well-known/oauth-authorization-server/{mcp_server_name}/mcp",
        code: 200,
      }),
    ),
  ).annotate({
    identifier:
      "GetOauthAuthorizationServerLegacyWellKnownOauthAuthorizationServerMcpServerNameMcpRequest",
  }) as any as S.Schema<GetOauthAuthorizationServerLegacyWellKnownOauthAuthorizationServerMcpServerNameMcpRequest>;

export interface GetOauthAuthorizationServerLegacyWellKnownOauthAuthorizationServerMcpServerNameMcpResponse {
  body: unknown;
}
export const GetOauthAuthorizationServerLegacyWellKnownOauthAuthorizationServerMcpServerNameMcpResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier:
      "GetOauthAuthorizationServerLegacyWellKnownOauthAuthorizationServerMcpServerNameMcpResponse",
  }) as any as S.Schema<GetOauthAuthorizationServerLegacyWellKnownOauthAuthorizationServerMcpServerNameMcpResponse>;

export interface GetOauthAuthorizationServerMcpStandardWellKnownOauthAuthorizationServerMcpMcpServerNameRequest {
  mcp_server_name: string;
}
export const GetOauthAuthorizationServerMcpStandardWellKnownOauthAuthorizationServerMcpMcpServerNameRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      mcp_server_name: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/.well-known/oauth-authorization-server/mcp/{mcp_server_name}",
        code: 200,
      }),
    ),
  ).annotate({
    identifier:
      "GetOauthAuthorizationServerMcpStandardWellKnownOauthAuthorizationServerMcpMcpServerNameRequest",
  }) as any as S.Schema<GetOauthAuthorizationServerMcpStandardWellKnownOauthAuthorizationServerMcpMcpServerNameRequest>;

export interface GetOauthAuthorizationServerMcpStandardWellKnownOauthAuthorizationServerMcpMcpServerNameResponse {
  body: unknown;
}
export const GetOauthAuthorizationServerMcpStandardWellKnownOauthAuthorizationServerMcpMcpServerNameResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier:
      "GetOauthAuthorizationServerMcpStandardWellKnownOauthAuthorizationServerMcpMcpServerNameResponse",
  }) as any as S.Schema<GetOauthAuthorizationServerMcpStandardWellKnownOauthAuthorizationServerMcpMcpServerNameResponse>;

export interface GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerRequest {
  mcp_server_name?: string;
}
export const GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      mcp_server_name: S.optional(S.String.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/.well-known/oauth-authorization-server",
        code: 200,
      }),
    ),
  ).annotate({
    identifier:
      "GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerRequest",
  }) as any as S.Schema<GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerRequest>;

export interface GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerResponse {
  body: unknown;
}
export const GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier:
      "GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerResponse",
  }) as any as S.Schema<GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerResponse>;

export interface GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerMcpServerNameRequest {
  mcp_server_name: string;
}
export const GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerMcpServerNameRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      mcp_server_name: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/.well-known/oauth-authorization-server/{mcp_server_name}",
        code: 200,
      }),
    ),
  ).annotate({
    identifier:
      "GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerMcpServerNameRequest",
  }) as any as S.Schema<GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerMcpServerNameRequest>;

export interface GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerMcpServerNameResponse {
  body: unknown;
}
export const GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerMcpServerNameResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier:
      "GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerMcpServerNameResponse",
  }) as any as S.Schema<GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerMcpServerNameResponse>;

export interface GetOauthProtectedResourceAggregateWellKnownOauthProtectedResourceMcpRequest {}
export const GetOauthProtectedResourceAggregateWellKnownOauthProtectedResourceMcpRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({}).pipe(
      T.Http({
        method: "GET",
        uri: "/.well-known/oauth-protected-resource/mcp",
        code: 200,
      }),
    ),
  ).annotate({
    identifier:
      "GetOauthProtectedResourceAggregateWellKnownOauthProtectedResourceMcpRequest",
  }) as any as S.Schema<GetOauthProtectedResourceAggregateWellKnownOauthProtectedResourceMcpRequest>;

export interface GetOauthProtectedResourceAggregateWellKnownOauthProtectedResourceMcpResponse {
  body: unknown;
}
export const GetOauthProtectedResourceAggregateWellKnownOauthProtectedResourceMcpResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier:
      "GetOauthProtectedResourceAggregateWellKnownOauthProtectedResourceMcpResponse",
  }) as any as S.Schema<GetOauthProtectedResourceAggregateWellKnownOauthProtectedResourceMcpResponse>;

export interface GetOauthProtectedResourceMcpStandardWellKnownOauthProtectedResourceMcpMcpServerNameRequest {
  mcp_server_name: string;
}
export const GetOauthProtectedResourceMcpStandardWellKnownOauthProtectedResourceMcpMcpServerNameRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      mcp_server_name: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/.well-known/oauth-protected-resource/mcp/{mcp_server_name}",
        code: 200,
      }),
    ),
  ).annotate({
    identifier:
      "GetOauthProtectedResourceMcpStandardWellKnownOauthProtectedResourceMcpMcpServerNameRequest",
  }) as any as S.Schema<GetOauthProtectedResourceMcpStandardWellKnownOauthProtectedResourceMcpMcpServerNameRequest>;

export interface GetOauthProtectedResourceMcpStandardWellKnownOauthProtectedResourceMcpMcpServerNameResponse {
  body: unknown;
}
export const GetOauthProtectedResourceMcpStandardWellKnownOauthProtectedResourceMcpMcpServerNameResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier:
      "GetOauthProtectedResourceMcpStandardWellKnownOauthProtectedResourceMcpMcpServerNameResponse",
  }) as any as S.Schema<GetOauthProtectedResourceMcpStandardWellKnownOauthProtectedResourceMcpMcpServerNameResponse>;

export interface GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceRequest {
  mcp_server_name?: string;
}
export const GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      mcp_server_name: S.optional(S.String.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/.well-known/oauth-protected-resource",
        code: 200,
      }),
    ),
  ).annotate({
    identifier:
      "GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceRequest",
  }) as any as S.Schema<GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceRequest>;

export interface GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceResponse {
  body: unknown;
}
export const GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier:
      "GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceResponse",
  }) as any as S.Schema<GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceResponse>;

export interface GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpServerNameMcpRequest {
  mcp_server_name: string;
}
export const GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpServerNameMcpRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      mcp_server_name: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/.well-known/oauth-protected-resource/{mcp_server_name}/mcp",
        code: 200,
      }),
    ),
  ).annotate({
    identifier:
      "GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpServerNameMcpRequest",
  }) as any as S.Schema<GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpServerNameMcpRequest>;

export interface GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpServerNameMcpResponse {
  body: unknown;
}
export const GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpServerNameMcpResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier:
      "GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpServerNameMcpResponse",
  }) as any as S.Schema<GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpServerNameMcpResponse>;

export type GetOauthAuthorizationServerAggregateWellKnownOauthAuthorizationServerMcpError =
  LitellmOpError;
/** Oauth Authorization Server Aggregate OAuth authorization server discovery for the aggregate /mcp endpoint, the RFC 8414 path-inserted form for a client that treats {base}/mcp as its authorization base URL. The single-segment /mcp is reserved for the aggregate so the discovery chain stays consistent: the aggregate protected-resource document advertises {base}/mcp as its authorization server, so the document served here must have issuer {base}/mcp. A server literally named ``mcp`` therefore does not take this route; it keeps its standard two-segment discovery at /.well-known/oauth-authorization-server/mcp/mcp. Letting the per-server row win here instead would serve an issuer of {base} against a resource that advertised {base}/mcp, which fails the RFC 8414 issuer check and breaks the front door. */
export const getOauthAuthorizationServerAggregateWellKnownOauthAuthorizationServerMcp: API.OperationMethod<
  GetOauthAuthorizationServerAggregateWellKnownOauthAuthorizationServerMcpRequest,
  GetOauthAuthorizationServerAggregateWellKnownOauthAuthorizationServerMcpResponse,
  GetOauthAuthorizationServerAggregateWellKnownOauthAuthorizationServerMcpError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input:
    GetOauthAuthorizationServerAggregateWellKnownOauthAuthorizationServerMcpRequest,
  output:
    GetOauthAuthorizationServerAggregateWellKnownOauthAuthorizationServerMcpResponse,
  errors: [],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetOauthAuthorizationServerLegacyWellKnownOauthAuthorizationServerMcpServerNameMcpError =
  | UnprocessableEntity
  | LitellmOpError;
/** Oauth Authorization Server Legacy OAuth authorization server discovery for legacy /{server_name}/mcp pattern. */
export const getOauthAuthorizationServerLegacyWellKnownOauthAuthorizationServerMcpServerNameMcp: API.OperationMethod<
  GetOauthAuthorizationServerLegacyWellKnownOauthAuthorizationServerMcpServerNameMcpRequest,
  GetOauthAuthorizationServerLegacyWellKnownOauthAuthorizationServerMcpServerNameMcpResponse,
  GetOauthAuthorizationServerLegacyWellKnownOauthAuthorizationServerMcpServerNameMcpError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input:
    GetOauthAuthorizationServerLegacyWellKnownOauthAuthorizationServerMcpServerNameMcpRequest,
  output:
    GetOauthAuthorizationServerLegacyWellKnownOauthAuthorizationServerMcpServerNameMcpResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetOauthAuthorizationServerMcpStandardWellKnownOauthAuthorizationServerMcpMcpServerNameError =
  | UnprocessableEntity
  | LitellmOpError;
/** Oauth Authorization Server Mcp Standard OAuth authorization server discovery endpoint using standard MCP URL pattern. Standard pattern: /mcp/{server_name} Discovery path: /.well-known/oauth-authorization-server/mcp/{server_name} */
export const getOauthAuthorizationServerMcpStandardWellKnownOauthAuthorizationServerMcpMcpServerName: API.OperationMethod<
  GetOauthAuthorizationServerMcpStandardWellKnownOauthAuthorizationServerMcpMcpServerNameRequest,
  GetOauthAuthorizationServerMcpStandardWellKnownOauthAuthorizationServerMcpMcpServerNameResponse,
  GetOauthAuthorizationServerMcpStandardWellKnownOauthAuthorizationServerMcpMcpServerNameError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input:
    GetOauthAuthorizationServerMcpStandardWellKnownOauthAuthorizationServerMcpMcpServerNameRequest,
  output:
    GetOauthAuthorizationServerMcpStandardWellKnownOauthAuthorizationServerMcpMcpServerNameResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerError =
  | UnprocessableEntity
  | LitellmOpError;
/** Oauth Authorization Server Mcp OAuth authorization server discovery endpoint. Supports both legacy pattern (/{server_name}) and root endpoint. */
export const getOauthAuthorizationServerMcpWellKnownOauthAuthorizationServer: API.OperationMethod<
  GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerRequest,
  GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerResponse,
  GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerRequest,
  output:
    GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerMcpServerNameError =
  | UnprocessableEntity
  | LitellmOpError;
/** Oauth Authorization Server Mcp OAuth authorization server discovery endpoint. Supports both legacy pattern (/{server_name}) and root endpoint. */
export const getOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerMcpServerName: API.OperationMethod<
  GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerMcpServerNameRequest,
  GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerMcpServerNameResponse,
  GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerMcpServerNameError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input:
    GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerMcpServerNameRequest,
  output:
    GetOauthAuthorizationServerMcpWellKnownOauthAuthorizationServerMcpServerNameResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetOauthProtectedResourceAggregateWellKnownOauthProtectedResourceMcpError =
  LitellmOpError;
/** Oauth Protected Resource Aggregate OAuth protected resource discovery for the aggregate /mcp endpoint. The single-segment ``/mcp`` path does not collide with any per-server PRM pattern (those are two-segment: ``/mcp/{server}`` or ``/{server}/mcp``), so this unambiguously describes the aggregate resource. */
export const getOauthProtectedResourceAggregateWellKnownOauthProtectedResourceMcp: API.OperationMethod<
  GetOauthProtectedResourceAggregateWellKnownOauthProtectedResourceMcpRequest,
  GetOauthProtectedResourceAggregateWellKnownOauthProtectedResourceMcpResponse,
  GetOauthProtectedResourceAggregateWellKnownOauthProtectedResourceMcpError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input:
    GetOauthProtectedResourceAggregateWellKnownOauthProtectedResourceMcpRequest,
  output:
    GetOauthProtectedResourceAggregateWellKnownOauthProtectedResourceMcpResponse,
  errors: [],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetOauthProtectedResourceMcpStandardWellKnownOauthProtectedResourceMcpMcpServerNameError =
  | UnprocessableEntity
  | LitellmOpError;
/** Oauth Protected Resource Mcp Standard OAuth protected resource discovery endpoint using standard MCP URL pattern. Standard pattern: /mcp/{server_name} Discovery path: /.well-known/oauth-protected-resource/mcp/{server_name} This endpoint is compliant with MCP specification and works with standard MCP clients like mcp-inspector and VSCode Copilot. */
export const getOauthProtectedResourceMcpStandardWellKnownOauthProtectedResourceMcpMcpServerName: API.OperationMethod<
  GetOauthProtectedResourceMcpStandardWellKnownOauthProtectedResourceMcpMcpServerNameRequest,
  GetOauthProtectedResourceMcpStandardWellKnownOauthProtectedResourceMcpMcpServerNameResponse,
  GetOauthProtectedResourceMcpStandardWellKnownOauthProtectedResourceMcpMcpServerNameError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input:
    GetOauthProtectedResourceMcpStandardWellKnownOauthProtectedResourceMcpMcpServerNameRequest,
  output:
    GetOauthProtectedResourceMcpStandardWellKnownOauthProtectedResourceMcpMcpServerNameResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceError =
  | UnprocessableEntity
  | LitellmOpError;
/** Oauth Protected Resource Mcp OAuth protected resource discovery endpoint using LiteLLM legacy URL pattern. Legacy pattern: /{server_name}/mcp Discovery path: /.well-known/oauth-protected-resource/{server_name}/mcp This endpoint is kept for backward compatibility. New integrations should use the standard MCP pattern (/mcp/{server_name}) instead. */
export const getOauthProtectedResourceMcpWellKnownOauthProtectedResource: API.OperationMethod<
  GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceRequest,
  GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceResponse,
  GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceRequest,
  output: GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpServerNameMcpError =
  | UnprocessableEntity
  | LitellmOpError;
/** Oauth Protected Resource Mcp OAuth protected resource discovery endpoint using LiteLLM legacy URL pattern. Legacy pattern: /{server_name}/mcp Discovery path: /.well-known/oauth-protected-resource/{server_name}/mcp This endpoint is kept for backward compatibility. New integrations should use the standard MCP pattern (/mcp/{server_name}) instead. */
export const getOauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpServerNameMcp: API.OperationMethod<
  GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpServerNameMcpRequest,
  GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpServerNameMcpResponse,
  GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpServerNameMcpError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input:
    GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpServerNameMcpRequest,
  output:
    GetOauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpServerNameMcpResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));
