// AUTO-GENERATED by scripts/generate.ts from .generated-specs (pinned litellm-openapi @ 1.100.0 — see README). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
import * as T from "../traits.ts";
import {
  LitellmProtocol,
  type LitellmOpError,
  type LitellmOpContext,
} from "../protocol.ts";
import * as Retry from "../retry.ts";

export type { LitellmOpError, LitellmOpContext };

export class UnprocessableEntity
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<UnprocessableEntity>()("UnprocessableEntity", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 422 }],
  ) {}

export interface GetVideoContentV1VideosVideoIdContentRequest {
  video_id: string;
}
export const GetVideoContentV1VideosVideoIdContentRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      video_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/v1/videos/{video_id}/content",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "GetVideoContentV1VideosVideoIdContentRequest",
  }) as any as S.Schema<GetVideoContentV1VideosVideoIdContentRequest>;

export interface GetVideoContentV1VideosVideoIdContentResponse {}
export const GetVideoContentV1VideosVideoIdContentResponse =
  /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
    identifier: "GetVideoContentV1VideosVideoIdContentResponse",
  }) as any as S.Schema<GetVideoContentV1VideosVideoIdContentResponse>;

export interface GetVideoContentVideosVideoIdContentRequest {
  video_id: string;
}
export const GetVideoContentVideosVideoIdContentRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      video_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({ method: "GET", uri: "/videos/{video_id}/content", code: 200 }),
    ),
  ).annotate({
    identifier: "GetVideoContentVideosVideoIdContentRequest",
  }) as any as S.Schema<GetVideoContentVideosVideoIdContentRequest>;

export interface GetVideoContentVideosVideoIdContentResponse {}
export const GetVideoContentVideosVideoIdContentResponse =
  /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
    identifier: "GetVideoContentVideosVideoIdContentResponse",
  }) as any as S.Schema<GetVideoContentVideosVideoIdContentResponse>;

export interface GetVideoStatusV1VideosVideoIdRequest {
  video_id: string;
}
export const GetVideoStatusV1VideosVideoIdRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      video_id: S.String.pipe(T.Label()),
    }).pipe(T.Http({ method: "GET", uri: "/v1/videos/{video_id}", code: 200 })),
).annotate({
  identifier: "GetVideoStatusV1VideosVideoIdRequest",
}) as any as S.Schema<GetVideoStatusV1VideosVideoIdRequest>;

export interface GetVideoStatusV1VideosVideoIdResponse {
  body: unknown;
}
export const GetVideoStatusV1VideosVideoIdResponse = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      body: S.Unknown,
    }),
).annotate({
  identifier: "GetVideoStatusV1VideosVideoIdResponse",
}) as any as S.Schema<GetVideoStatusV1VideosVideoIdResponse>;

export interface GetVideoStatusVideosVideoIdRequest {
  video_id: string;
}
export const GetVideoStatusVideosVideoIdRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    video_id: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "GET", uri: "/videos/{video_id}", code: 200 })),
).annotate({
  identifier: "GetVideoStatusVideosVideoIdRequest",
}) as any as S.Schema<GetVideoStatusVideosVideoIdRequest>;

export interface GetVideoStatusVideosVideoIdResponse {
  body: unknown;
}
export const GetVideoStatusVideosVideoIdResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    body: S.Unknown,
  }),
).annotate({
  identifier: "GetVideoStatusVideosVideoIdResponse",
}) as any as S.Schema<GetVideoStatusVideosVideoIdResponse>;

export interface PostVideoExtensionV1VideosExtensionRequest {}
export const PostVideoExtensionV1VideosExtensionRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({}).pipe(
      T.Http({ method: "POST", uri: "/v1/videos/extensions", code: 200 }),
    ),
  ).annotate({
    identifier: "PostVideoExtensionV1VideosExtensionRequest",
  }) as any as S.Schema<PostVideoExtensionV1VideosExtensionRequest>;

export interface PostVideoExtensionV1VideosExtensionResponse {
  body: unknown;
}
export const PostVideoExtensionV1VideosExtensionResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "PostVideoExtensionV1VideosExtensionResponse",
  }) as any as S.Schema<PostVideoExtensionV1VideosExtensionResponse>;

export interface PostVideoExtensionVideosExtensionRequest {}
export const PostVideoExtensionVideosExtensionRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({}).pipe(
      T.Http({ method: "POST", uri: "/videos/extensions", code: 200 }),
    ),
).annotate({
  identifier: "PostVideoExtensionVideosExtensionRequest",
}) as any as S.Schema<PostVideoExtensionVideosExtensionRequest>;

export interface PostVideoExtensionVideosExtensionResponse {
  body: unknown;
}
export const PostVideoExtensionVideosExtensionResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "PostVideoExtensionVideosExtensionResponse",
  }) as any as S.Schema<PostVideoExtensionVideosExtensionResponse>;

export interface PostVideoGenerationV1VideosRequest {
  input_reference?: string | null;
}
export const PostVideoGenerationV1VideosRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    input_reference: S.optional(S.NullOr(S.String)),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/v1/videos",
      code: 200,
      contentType: "multipart",
    }),
  ),
).annotate({
  identifier: "PostVideoGenerationV1VideosRequest",
}) as any as S.Schema<PostVideoGenerationV1VideosRequest>;

export interface PostVideoGenerationV1VideosResponse {
  body: unknown;
}
export const PostVideoGenerationV1VideosResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    body: S.Unknown,
  }),
).annotate({
  identifier: "PostVideoGenerationV1VideosResponse",
}) as any as S.Schema<PostVideoGenerationV1VideosResponse>;

export interface PostVideoGenerationVideosRequest {
  input_reference?: string | null;
}
export const PostVideoGenerationVideosRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    input_reference: S.optional(S.NullOr(S.String)),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/videos",
      code: 200,
      contentType: "multipart",
    }),
  ),
).annotate({
  identifier: "PostVideoGenerationVideosRequest",
}) as any as S.Schema<PostVideoGenerationVideosRequest>;

export interface PostVideoGenerationVideosResponse {
  body: unknown;
}
export const PostVideoGenerationVideosResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    body: S.Unknown,
  }),
).annotate({
  identifier: "PostVideoGenerationVideosResponse",
}) as any as S.Schema<PostVideoGenerationVideosResponse>;

export interface PostVideoRemixV1VideosVideoIdRemixRequest {
  video_id: string;
}
export const PostVideoRemixV1VideosVideoIdRemixRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      video_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({ method: "POST", uri: "/v1/videos/{video_id}/remix", code: 200 }),
    ),
  ).annotate({
    identifier: "PostVideoRemixV1VideosVideoIdRemixRequest",
  }) as any as S.Schema<PostVideoRemixV1VideosVideoIdRemixRequest>;

export interface PostVideoRemixV1VideosVideoIdRemixResponse {
  body: unknown;
}
export const PostVideoRemixV1VideosVideoIdRemixResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "PostVideoRemixV1VideosVideoIdRemixResponse",
  }) as any as S.Schema<PostVideoRemixV1VideosVideoIdRemixResponse>;

export interface PostVideoRemixVideosVideoIdRemixRequest {
  video_id: string;
}
export const PostVideoRemixVideosVideoIdRemixRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      video_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({ method: "POST", uri: "/videos/{video_id}/remix", code: 200 }),
    ),
).annotate({
  identifier: "PostVideoRemixVideosVideoIdRemixRequest",
}) as any as S.Schema<PostVideoRemixVideosVideoIdRemixRequest>;

export interface PostVideoRemixVideosVideoIdRemixResponse {
  body: unknown;
}
export const PostVideoRemixVideosVideoIdRemixResponse = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      body: S.Unknown,
    }),
).annotate({
  identifier: "PostVideoRemixVideosVideoIdRemixResponse",
}) as any as S.Schema<PostVideoRemixVideosVideoIdRemixResponse>;

export interface VideoCreateCharacterV1VideosCharactersPostRequest {
  name: string;
  video: string;
}
export const VideoCreateCharacterV1VideosCharactersPostRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      name: S.String,
      video: S.String,
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/v1/videos/characters",
        code: 200,
        contentType: "multipart",
      }),
    ),
  ).annotate({
    identifier: "VideoCreateCharacterV1VideosCharactersPostRequest",
  }) as any as S.Schema<VideoCreateCharacterV1VideosCharactersPostRequest>;

export interface VideoCreateCharacterV1VideosCharactersPostResponse {
  body: unknown;
}
export const VideoCreateCharacterV1VideosCharactersPostResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "VideoCreateCharacterV1VideosCharactersPostResponse",
  }) as any as S.Schema<VideoCreateCharacterV1VideosCharactersPostResponse>;

export interface VideoCreateCharacterVideosCharactersPostRequest {
  name: string;
  video: string;
}
export const VideoCreateCharacterVideosCharactersPostRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      name: S.String,
      video: S.String,
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/videos/characters",
        code: 200,
        contentType: "multipart",
      }),
    ),
  ).annotate({
    identifier: "VideoCreateCharacterVideosCharactersPostRequest",
  }) as any as S.Schema<VideoCreateCharacterVideosCharactersPostRequest>;

export interface VideoCreateCharacterVideosCharactersPostResponse {
  body: unknown;
}
export const VideoCreateCharacterVideosCharactersPostResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "VideoCreateCharacterVideosCharactersPostResponse",
  }) as any as S.Schema<VideoCreateCharacterVideosCharactersPostResponse>;

export interface VideoEditV1VideosEditsPostRequest {}
export const VideoEditV1VideosEditsPostRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(
    T.Http({ method: "POST", uri: "/v1/videos/edits", code: 200 }),
  ),
).annotate({
  identifier: "VideoEditV1VideosEditsPostRequest",
}) as any as S.Schema<VideoEditV1VideosEditsPostRequest>;

export interface VideoEditV1VideosEditsPostResponse {
  body: unknown;
}
export const VideoEditV1VideosEditsPostResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    body: S.Unknown,
  }),
).annotate({
  identifier: "VideoEditV1VideosEditsPostResponse",
}) as any as S.Schema<VideoEditV1VideosEditsPostResponse>;

export interface VideoEditVideosEditsPostRequest {}
export const VideoEditVideosEditsPostRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(
    T.Http({ method: "POST", uri: "/videos/edits", code: 200 }),
  ),
).annotate({
  identifier: "VideoEditVideosEditsPostRequest",
}) as any as S.Schema<VideoEditVideosEditsPostRequest>;

export interface VideoEditVideosEditsPostResponse {
  body: unknown;
}
export const VideoEditVideosEditsPostResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    body: S.Unknown,
  }),
).annotate({
  identifier: "VideoEditVideosEditsPostResponse",
}) as any as S.Schema<VideoEditVideosEditsPostResponse>;

export interface VideoGetCharacterV1VideosCharactersCharacterIdGetRequest {
  character_id: string;
}
export const VideoGetCharacterV1VideosCharactersCharacterIdGetRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      character_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/v1/videos/characters/{character_id}",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "VideoGetCharacterV1VideosCharactersCharacterIdGetRequest",
  }) as any as S.Schema<VideoGetCharacterV1VideosCharactersCharacterIdGetRequest>;

export interface VideoGetCharacterV1VideosCharactersCharacterIdGetResponse {
  body: unknown;
}
export const VideoGetCharacterV1VideosCharactersCharacterIdGetResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "VideoGetCharacterV1VideosCharactersCharacterIdGetResponse",
  }) as any as S.Schema<VideoGetCharacterV1VideosCharactersCharacterIdGetResponse>;

export interface VideoGetCharacterVideosCharactersCharacterIdGetRequest {
  character_id: string;
}
export const VideoGetCharacterVideosCharactersCharacterIdGetRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      character_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/videos/characters/{character_id}",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "VideoGetCharacterVideosCharactersCharacterIdGetRequest",
  }) as any as S.Schema<VideoGetCharacterVideosCharactersCharacterIdGetRequest>;

export interface VideoGetCharacterVideosCharactersCharacterIdGetResponse {
  body: unknown;
}
export const VideoGetCharacterVideosCharactersCharacterIdGetResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      body: S.Unknown,
    }),
  ).annotate({
    identifier: "VideoGetCharacterVideosCharactersCharacterIdGetResponse",
  }) as any as S.Schema<VideoGetCharacterVideosCharactersCharacterIdGetResponse>;

export interface VideoListV1VideosGetRequest {}
export const VideoListV1VideosGetRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/v1/videos", code: 200 })),
).annotate({
  identifier: "VideoListV1VideosGetRequest",
}) as any as S.Schema<VideoListV1VideosGetRequest>;

export interface VideoListV1VideosGetResponse {
  body: unknown;
}
export const VideoListV1VideosGetResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    body: S.Unknown,
  }),
).annotate({
  identifier: "VideoListV1VideosGetResponse",
}) as any as S.Schema<VideoListV1VideosGetResponse>;

export interface VideoListVideosGetRequest {}
export const VideoListVideosGetRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/videos", code: 200 })),
).annotate({
  identifier: "VideoListVideosGetRequest",
}) as any as S.Schema<VideoListVideosGetRequest>;

export interface VideoListVideosGetResponse {
  body: unknown;
}
export const VideoListVideosGetResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    body: S.Unknown,
  }),
).annotate({
  identifier: "VideoListVideosGetResponse",
}) as any as S.Schema<VideoListVideosGetResponse>;

export type GetVideoContentV1VideosVideoIdContentError =
  | UnprocessableEntity
  | LitellmOpError;
/** Video Content Video content endpoint for downloading video content. Follows the OpenAI Videos API spec: https://platform.openai.com/docs/api-reference/videos Example: ```bash curl -X GET "http://localhost:4000/v1/videos/{video_id}/content" -H "Authorization: Bearer sk-1234" --output video.mp4 ``` */
export const getVideoContentV1VideosVideoIdContent: API.OperationMethod<
  GetVideoContentV1VideosVideoIdContentRequest,
  GetVideoContentV1VideosVideoIdContentResponse,
  GetVideoContentV1VideosVideoIdContentError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetVideoContentV1VideosVideoIdContentRequest,
  output: GetVideoContentV1VideosVideoIdContentResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetVideoContentVideosVideoIdContentError =
  | UnprocessableEntity
  | LitellmOpError;
/** Video Content Video content endpoint for downloading video content. Follows the OpenAI Videos API spec: https://platform.openai.com/docs/api-reference/videos Example: ```bash curl -X GET "http://localhost:4000/v1/videos/{video_id}/content" -H "Authorization: Bearer sk-1234" --output video.mp4 ``` */
export const getVideoContentVideosVideoIdContent: API.OperationMethod<
  GetVideoContentVideosVideoIdContentRequest,
  GetVideoContentVideosVideoIdContentResponse,
  GetVideoContentVideosVideoIdContentError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetVideoContentVideosVideoIdContentRequest,
  output: GetVideoContentVideosVideoIdContentResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetVideoStatusV1VideosVideoIdError =
  | UnprocessableEntity
  | LitellmOpError;
/** Video Status Video status endpoint for retrieving video status and metadata. Follows the OpenAI Videos API spec: https://platform.openai.com/docs/api-reference/videos Example: ```bash curl -X GET "http://localhost:4000/v1/videos/video_123" -H "Authorization: Bearer sk-1234" ``` */
export const getVideoStatusV1VideosVideoId: API.OperationMethod<
  GetVideoStatusV1VideosVideoIdRequest,
  GetVideoStatusV1VideosVideoIdResponse,
  GetVideoStatusV1VideosVideoIdError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetVideoStatusV1VideosVideoIdRequest,
  output: GetVideoStatusV1VideosVideoIdResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type GetVideoStatusVideosVideoIdError =
  | UnprocessableEntity
  | LitellmOpError;
/** Video Status Video status endpoint for retrieving video status and metadata. Follows the OpenAI Videos API spec: https://platform.openai.com/docs/api-reference/videos Example: ```bash curl -X GET "http://localhost:4000/v1/videos/video_123" -H "Authorization: Bearer sk-1234" ``` */
export const getVideoStatusVideosVideoId: API.OperationMethod<
  GetVideoStatusVideosVideoIdRequest,
  GetVideoStatusVideosVideoIdResponse,
  GetVideoStatusVideosVideoIdError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetVideoStatusVideosVideoIdRequest,
  output: GetVideoStatusVideosVideoIdResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type PostVideoExtensionV1VideosExtensionError = LitellmOpError;
/** Video Extension Create a video extension. Follows the OpenAI Videos API spec: https://platform.openai.com/docs/api-reference/videos/create-extension Example: ```bash curl -X POST "http://localhost:4000/v1/videos/extensions" -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" -d '{"prompt": "Continue the scene", "seconds": "5", "video": {"id": "video_123"}}' ``` */
export const postVideoExtensionV1VideosExtension: API.OperationMethod<
  PostVideoExtensionV1VideosExtensionRequest,
  PostVideoExtensionV1VideosExtensionResponse,
  PostVideoExtensionV1VideosExtensionError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PostVideoExtensionV1VideosExtensionRequest,
  output: PostVideoExtensionV1VideosExtensionResponse,
  errors: [],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type PostVideoExtensionVideosExtensionError = LitellmOpError;
/** Video Extension Create a video extension. Follows the OpenAI Videos API spec: https://platform.openai.com/docs/api-reference/videos/create-extension Example: ```bash curl -X POST "http://localhost:4000/v1/videos/extensions" -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" -d '{"prompt": "Continue the scene", "seconds": "5", "video": {"id": "video_123"}}' ``` */
export const postVideoExtensionVideosExtension: API.OperationMethod<
  PostVideoExtensionVideosExtensionRequest,
  PostVideoExtensionVideosExtensionResponse,
  PostVideoExtensionVideosExtensionError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PostVideoExtensionVideosExtensionRequest,
  output: PostVideoExtensionVideosExtensionResponse,
  errors: [],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type PostVideoGenerationV1VideosError =
  | UnprocessableEntity
  | LitellmOpError;
/** Video Generation Video generation endpoint for creating videos from text prompts. Follows the OpenAI Videos API spec: https://platform.openai.com/docs/api-reference/videos Example: ```bash curl -X POST "http://localhost:4000/v1/videos" -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" -d '{ "model": "sora-2", "prompt": "A beautiful sunset over the ocean" }' ``` */
export const postVideoGenerationV1Videos: API.OperationMethod<
  PostVideoGenerationV1VideosRequest,
  PostVideoGenerationV1VideosResponse,
  PostVideoGenerationV1VideosError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PostVideoGenerationV1VideosRequest,
  output: PostVideoGenerationV1VideosResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type PostVideoGenerationVideosError =
  | UnprocessableEntity
  | LitellmOpError;
/** Video Generation Video generation endpoint for creating videos from text prompts. Follows the OpenAI Videos API spec: https://platform.openai.com/docs/api-reference/videos Example: ```bash curl -X POST "http://localhost:4000/v1/videos" -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" -d '{ "model": "sora-2", "prompt": "A beautiful sunset over the ocean" }' ``` */
export const postVideoGenerationVideos: API.OperationMethod<
  PostVideoGenerationVideosRequest,
  PostVideoGenerationVideosResponse,
  PostVideoGenerationVideosError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PostVideoGenerationVideosRequest,
  output: PostVideoGenerationVideosResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type PostVideoRemixV1VideosVideoIdRemixError =
  | UnprocessableEntity
  | LitellmOpError;
/** Video Remix Video remix endpoint for remixing existing videos with new prompts. Follows the OpenAI Videos API spec: https://platform.openai.com/docs/api-reference/videos Example: ```bash curl -X POST "http://localhost:4000/v1/videos/video_123/remix" -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" -d '{ "prompt": "A new version with different colors" }' ``` */
export const postVideoRemixV1VideosVideoIdRemix: API.OperationMethod<
  PostVideoRemixV1VideosVideoIdRemixRequest,
  PostVideoRemixV1VideosVideoIdRemixResponse,
  PostVideoRemixV1VideosVideoIdRemixError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PostVideoRemixV1VideosVideoIdRemixRequest,
  output: PostVideoRemixV1VideosVideoIdRemixResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type PostVideoRemixVideosVideoIdRemixError =
  | UnprocessableEntity
  | LitellmOpError;
/** Video Remix Video remix endpoint for remixing existing videos with new prompts. Follows the OpenAI Videos API spec: https://platform.openai.com/docs/api-reference/videos Example: ```bash curl -X POST "http://localhost:4000/v1/videos/video_123/remix" -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" -d '{ "prompt": "A new version with different colors" }' ``` */
export const postVideoRemixVideosVideoIdRemix: API.OperationMethod<
  PostVideoRemixVideosVideoIdRemixRequest,
  PostVideoRemixVideosVideoIdRemixResponse,
  PostVideoRemixVideosVideoIdRemixError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PostVideoRemixVideosVideoIdRemixRequest,
  output: PostVideoRemixVideosVideoIdRemixResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type VideoCreateCharacterV1VideosCharactersPostError =
  | UnprocessableEntity
  | LitellmOpError;
/** Video Create Character Create a character from an uploaded video file. Follows the OpenAI Videos API spec: https://platform.openai.com/docs/api-reference/videos/create-character Example: ```bash curl -X POST "http://localhost:4000/v1/videos/characters" -H "Authorization: Bearer sk-1234" -F "video=@character_video.mp4" -F "name=my_character" ``` */
export const videoCreateCharacterV1VideosCharactersPost: API.OperationMethod<
  VideoCreateCharacterV1VideosCharactersPostRequest,
  VideoCreateCharacterV1VideosCharactersPostResponse,
  VideoCreateCharacterV1VideosCharactersPostError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VideoCreateCharacterV1VideosCharactersPostRequest,
  output: VideoCreateCharacterV1VideosCharactersPostResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type VideoCreateCharacterVideosCharactersPostError =
  | UnprocessableEntity
  | LitellmOpError;
/** Video Create Character Create a character from an uploaded video file. Follows the OpenAI Videos API spec: https://platform.openai.com/docs/api-reference/videos/create-character Example: ```bash curl -X POST "http://localhost:4000/v1/videos/characters" -H "Authorization: Bearer sk-1234" -F "video=@character_video.mp4" -F "name=my_character" ``` */
export const videoCreateCharacterVideosCharactersPost: API.OperationMethod<
  VideoCreateCharacterVideosCharactersPostRequest,
  VideoCreateCharacterVideosCharactersPostResponse,
  VideoCreateCharacterVideosCharactersPostError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VideoCreateCharacterVideosCharactersPostRequest,
  output: VideoCreateCharacterVideosCharactersPostResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type VideoEditV1VideosEditsPostError = LitellmOpError;
/** Video Edit Create a video edit job. Follows the OpenAI Videos API spec: https://platform.openai.com/docs/api-reference/videos/create-edit Example: ```bash curl -X POST "http://localhost:4000/v1/videos/edits" -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" -d '{"prompt": "Make it brighter", "video": {"id": "video_123"}}' ``` */
export const videoEditV1VideosEditsPost: API.OperationMethod<
  VideoEditV1VideosEditsPostRequest,
  VideoEditV1VideosEditsPostResponse,
  VideoEditV1VideosEditsPostError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VideoEditV1VideosEditsPostRequest,
  output: VideoEditV1VideosEditsPostResponse,
  errors: [],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type VideoEditVideosEditsPostError = LitellmOpError;
/** Video Edit Create a video edit job. Follows the OpenAI Videos API spec: https://platform.openai.com/docs/api-reference/videos/create-edit Example: ```bash curl -X POST "http://localhost:4000/v1/videos/edits" -H "Authorization: Bearer sk-1234" -H "Content-Type: application/json" -d '{"prompt": "Make it brighter", "video": {"id": "video_123"}}' ``` */
export const videoEditVideosEditsPost: API.OperationMethod<
  VideoEditVideosEditsPostRequest,
  VideoEditVideosEditsPostResponse,
  VideoEditVideosEditsPostError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VideoEditVideosEditsPostRequest,
  output: VideoEditVideosEditsPostResponse,
  errors: [],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type VideoGetCharacterV1VideosCharactersCharacterIdGetError =
  | UnprocessableEntity
  | LitellmOpError;
/** Video Get Character Retrieve a character by ID. Follows the OpenAI Videos API spec: https://platform.openai.com/docs/api-reference/videos/get-character Example: ```bash curl -X GET "http://localhost:4000/v1/videos/characters/char_123" -H "Authorization: Bearer sk-1234" ``` */
export const videoGetCharacterV1VideosCharactersCharacterIdGet: API.OperationMethod<
  VideoGetCharacterV1VideosCharactersCharacterIdGetRequest,
  VideoGetCharacterV1VideosCharactersCharacterIdGetResponse,
  VideoGetCharacterV1VideosCharactersCharacterIdGetError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VideoGetCharacterV1VideosCharactersCharacterIdGetRequest,
  output: VideoGetCharacterV1VideosCharactersCharacterIdGetResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type VideoGetCharacterVideosCharactersCharacterIdGetError =
  | UnprocessableEntity
  | LitellmOpError;
/** Video Get Character Retrieve a character by ID. Follows the OpenAI Videos API spec: https://platform.openai.com/docs/api-reference/videos/get-character Example: ```bash curl -X GET "http://localhost:4000/v1/videos/characters/char_123" -H "Authorization: Bearer sk-1234" ``` */
export const videoGetCharacterVideosCharactersCharacterIdGet: API.OperationMethod<
  VideoGetCharacterVideosCharactersCharacterIdGetRequest,
  VideoGetCharacterVideosCharactersCharacterIdGetResponse,
  VideoGetCharacterVideosCharactersCharacterIdGetError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VideoGetCharacterVideosCharactersCharacterIdGetRequest,
  output: VideoGetCharacterVideosCharactersCharacterIdGetResponse,
  errors: [UnprocessableEntity],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type VideoListV1VideosGetError = LitellmOpError;
/** Video List Video list endpoint for retrieving a list of videos. Follows the OpenAI Videos API spec: https://platform.openai.com/docs/api-reference/videos Example: ```bash curl -X GET "http://localhost:4000/v1/videos" -H "Authorization: Bearer sk-1234" ``` */
export const videoListV1VideosGet: API.OperationMethod<
  VideoListV1VideosGetRequest,
  VideoListV1VideosGetResponse,
  VideoListV1VideosGetError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VideoListV1VideosGetRequest,
  output: VideoListV1VideosGetResponse,
  errors: [],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));

export type VideoListVideosGetError = LitellmOpError;
/** Video List Video list endpoint for retrieving a list of videos. Follows the OpenAI Videos API spec: https://platform.openai.com/docs/api-reference/videos Example: ```bash curl -X GET "http://localhost:4000/v1/videos" -H "Authorization: Bearer sk-1234" ``` */
export const videoListVideosGet: API.OperationMethod<
  VideoListVideosGetRequest,
  VideoListVideosGetResponse,
  VideoListVideosGetError,
  LitellmOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VideoListVideosGetRequest,
  output: VideoListVideosGetResponse,
  errors: [],
  protocol: LitellmProtocol,
  retry: Retry.Retry,
}));
