/**
 * `docs/netbox-coverage.md` — what this package can write in NetBox, and what it cannot.
 *
 * ★ THE OWNER COLUMN IS DERIVED, NOT HAND-KEPT, AND THAT IS THE DIFFERENCE FROM THE PROXMOX
 *   REPORT. `docs/api-coverage.md` gets its owner column from a hand-written ledger
 *   (`scripts/proxmox-ownership-*.ts`) that is checked in one direction only, so an unlisted
 *   write understates coverage silently. Here the owner is the file that NAMES the endpoint key,
 *   found by the same scan the generator uses — a write with no declared key cannot happen,
 *   because `constraintsFor` would have no table and the guard refuses.
 *
 * ⛔ TWO COVERAGE PIPELINES NOW EXIST IN THIS REPO AND THEY ARE NOT UNIFIED. `scripts/api-coverage.ts`
 *   reads `schemas/manifest.json` under `HF_SCHEMA_CACHE`; this reads `codegen/manifest.json`
 *   under `HOMEFLARE_SCHEMA_CACHE`. That duplication predates NetBox and is recorded here rather
 *   than papered over — merging them is its own change with its own diff.
 */
import type { CoverageInput, CoverageRow } from './netbox-render.ts';

const pct = (part: number, whole: number): string =>
  whole === 0 ? '0%' : `${((part / whole) * 100).toFixed(1)}%`;

const rowLine = (row: CoverageRow): string =>
  `| \`${row.key}\` | ${row.params} | ${row.enforced} | ${row.recordedOnly} | \`${row.source}\` |`;

const appLine = (app: { readonly app: string; readonly endpoints: number }): string =>
  `| \`${app.app}\` | ${app.endpoints} |`;

export const renderCoverage = (input: CoverageInput): string => {
  const { entry, rows, writeEndpoints, writePaths, apps } = input;
  const tabled = rows.length;
  const params = rows.reduce((n, r) => n + r.params, 0);
  const enforced = rows.reduce((n, r) => n + r.enforced, 0);
  const recorded = rows.reduce((n, r) => n + r.recordedOnly, 0);
  return `# NetBox API coverage

<!-- GENERATED by codegen/netbox.ts — DO NOT EDIT BY HAND.
     Regenerate: bun codegen/netbox.ts   ·   Verify: bun codegen/netbox.ts --check -->

Generated from the vendor document recorded in
[\`codegen/manifest.json\`](../codegen/manifest.json):

- **${entry.product}** \`${entry.version}\` — sha256 \`${entry.sha256.slice(0, 16)}…\`
- ${entry.sourceRole}
- \`${entry.sourcePath}\`

Every row below is a fact about _that_ document. A different NetBox version is a different
report — refresh the manifest and regenerate rather than reading this one as timeless.

## The headline

| | count |
| --- | ---: |
| write endpoints NetBox publishes (POST/PUT/PATCH/DELETE) | ${writeEndpoints} |
| distinct write paths | ${writePaths} |
| endpoints tabled here | ${tabled} (${pct(tabled, writeEndpoints)}) |
| body parameters in those tables | ${params} |
| …enforced at plan time | ${enforced} |
| …recorded but NOT enforced | ${recorded} |

⛔ **${writeEndpoints - tabled} write endpoints are untabled and therefore unchecked at plan
time.** That is a gap, not a secret: it shrinks by one \`endpoint\` declaration in a Resource and
one regeneration. A scaffold's job is the pipeline, not the surface area.

⚠️ **A recorded-but-unenforced parameter is a rule the vendor states and nothing here checks.**
It is a \`format\` name NetBox validates server-side, or a pattern whose Python \`\\w\` is Unicode
where JavaScript's is ASCII (\`codegen/py-pattern.ts\`). Enforcing a narrowed copy would refuse
declarations NetBox accepts — worse than the 400 this table exists to replace.

## Tabled endpoints

| endpoint | body params | enforced | recorded only | declared in |
| --- | ---: | ---: | ---: | --- |
${rows.map(rowLine).join('\n')}

## The write surface, by NetBox app

The apps this package does not touch at all. Each is reachable the moment a Resource declares an
\`endpoint\` key inside it and the generator is rerun.

| app | write endpoints |
| --- | ---: |
${apps.map(appLine).join('\n')}

## What this report does NOT tell you

- **Whether NetBox is reachable.** The document is the vendor's own, pinned to a release tag; it
  is not a live probe. See the manifest's \`note\` for what was and was not verified live.
- **Whether a tabled rule is sufficient.** The table carries what the schema states. NetBox also
  enforces uniqueness, VRF containment and custom-field validators that no schema expresses, and
  those still arrive as a server-side 400.
- **Whether a GET is safe.** Reads are excluded on purpose: a read cannot be refused by a
  constraint that was dropped.

Merged table digest: \`${input.digest}\`.
`;
};
