// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-unifi-network/specs/openapi.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as T from "../traits.ts";
import {
  UnifiNetworkProtocol,
  type UnifiNetworkOpError,
  type UnifiNetworkOpContext,
} from "../protocol.ts";
import { UnknownUnifiNetworkError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { UnifiNetworkOpError, UnifiNetworkOpContext };

export interface GetInfoRequest {}
export const GetInfoRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/v1/info", code: 200 })),
).annotate({ identifier: "GetInfoRequest" }) as any as S.Schema<GetInfoRequest>;

export interface ApplicationInfo {
  applicationVersion: string;
}
export const ApplicationInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    applicationVersion: S.String,
  }),
).annotate({
  identifier: "ApplicationInfo",
}) as any as S.Schema<ApplicationInfo>;

export type GetInfoError = UnifiNetworkOpError;
/** Get Application Info Retrieve general information about the UniFi Network application. */
export const getInfo: API.OperationMethod<
  GetInfoRequest,
  ApplicationInfo,
  GetInfoError,
  UnifiNetworkOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetInfoRequest,
  output: ApplicationInfo,
  errors: [UnknownUnifiNetworkError],
  protocol: UnifiNetworkProtocol,
  retry: Retry.Retry,
}));
