// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-paperless-ngx/specs/openapi.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
import * as T from "../traits.ts";
import {
  PaperlessNgxProtocol,
  type PaperlessNgxOpError,
  type PaperlessNgxOpContext,
} from "../protocol.ts";
import { UnknownPaperlessNgxError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { PaperlessNgxOpError, PaperlessNgxOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export interface GetOauthCallbackRequest {}
export const GetOauthCallbackRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(
    T.Http({ method: "GET", uri: "/api/oauth/callback/", code: 200 }),
  ),
).annotate({
  identifier: "GetOauthCallbackRequest",
}) as any as S.Schema<GetOauthCallbackRequest>;

export interface GetOauthCallbackResponse {}
export const GetOauthCallbackResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "GetOauthCallbackResponse",
}) as any as S.Schema<GetOauthCallbackResponse>;

export type GetOauthCallbackError = BadRequest | PaperlessNgxOpError;
/** Callback view for OAuth2 authentication */
export const getOauthCallback: API.OperationMethod<
  GetOauthCallbackRequest,
  GetOauthCallbackResponse,
  GetOauthCallbackError,
  PaperlessNgxOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetOauthCallbackRequest,
  output: GetOauthCallbackResponse,
  errors: [BadRequest, UnknownPaperlessNgxError],
  protocol: PaperlessNgxProtocol,
  retry: Retry.Retry,
}));
