// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-paperless-ngx/specs/openapi.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
import * as T from "../traits.ts";
import {
  PaperlessNgxProtocol,
  type PaperlessNgxOpError,
  type PaperlessNgxOpContext,
} from "../protocol.ts";
import { UnknownPaperlessNgxError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { PaperlessNgxOpError, PaperlessNgxOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class Forbidden
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withAuthError),
    [{ status: 403 }],
  ) {}

export interface GetStatusRequest {}
export const GetStatusRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/status/", code: 200 })),
).annotate({
  identifier: "GetStatusRequest",
}) as any as S.Schema<GetStatusRequest>;

export interface Storage {
  total: number;
  available: number;
}
export const Storage = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    total: S.Number,
    available: S.Number,
  }),
).annotate({ identifier: "Storage" }) as any as S.Schema<Storage>;

export type MigrationStatusUnappliedMigrationsList = Array<string>;
export const MigrationStatusUnappliedMigrationsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<MigrationStatusUnappliedMigrationsList>;

export interface MigrationStatus {
  latest_migration: string;
  unapplied_migrations: MigrationStatusUnappliedMigrationsList;
}
export const MigrationStatus = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    latest_migration: S.String,
    unapplied_migrations: MigrationStatusUnappliedMigrationsList,
  }),
).annotate({
  identifier: "MigrationStatus",
}) as any as S.Schema<MigrationStatus>;

export interface Database {
  type: string;
  url: string;
  status: string;
  error: string;
  migration_status: MigrationStatus;
}
export const Database = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.String,
    url: S.String,
    status: S.String,
    error: S.String,
    migration_status: MigrationStatus,
  }),
).annotate({ identifier: "Database" }) as any as S.Schema<Database>;

export interface TasksSummaryOverview {
  days: number;
  total_count: number;
  pending_count: number;
  success_count: number;
  failure_count: number;
}
export const TasksSummaryOverview = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    days: S.Number,
    total_count: S.Number,
    pending_count: S.Number,
    success_count: S.Number,
    failure_count: S.Number,
  }),
).annotate({
  identifier: "TasksSummaryOverview",
}) as any as S.Schema<TasksSummaryOverview>;

export interface Tasks {
  redis_url: string;
  redis_status: string;
  redis_error: string;
  celery_status: string;
  summary: TasksSummaryOverview;
}
export const Tasks = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    redis_url: S.String,
    redis_status: S.String,
    redis_error: S.String,
    celery_status: S.String,
    summary: TasksSummaryOverview,
  }),
).annotate({ identifier: "Tasks" }) as any as S.Schema<Tasks>;

export interface Index {
  status: string;
  error: string;
  last_modified: string;
}
export const Index = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    status: S.String,
    error: S.String,
    last_modified: S.String,
  }),
).annotate({ identifier: "Index" }) as any as S.Schema<Index>;

export interface Classifier {
  status: string;
  error: string;
  last_trained: string;
}
export const Classifier = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    status: S.String,
    error: S.String,
    last_trained: S.String,
  }),
).annotate({ identifier: "Classifier" }) as any as S.Schema<Classifier>;

export interface SanityCheck {
  status: string;
  error: string;
  last_run: string;
}
export const SanityCheck = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    status: S.String,
    error: S.String,
    last_run: S.String,
  }),
).annotate({ identifier: "SanityCheck" }) as any as S.Schema<SanityCheck>;

export interface SystemStatus {
  pngx_version: string;
  server_os: string;
  install_type: string;
  storage: Storage;
  database: Database;
  tasks: Tasks;
  index: Index;
  classifier: Classifier;
  sanity_check: SanityCheck;
}
export const SystemStatus = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    pngx_version: S.String,
    server_os: S.String,
    install_type: S.String,
    storage: Storage,
    database: Database,
    tasks: Tasks,
    index: Index,
    classifier: Classifier,
    sanity_check: SanityCheck,
  }),
).annotate({ identifier: "SystemStatus" }) as any as S.Schema<SystemStatus>;

export type GetStatusError = BadRequest | Forbidden | PaperlessNgxOpError;
/** Get the current system status of the Paperless-NGX server */
export const getStatus: API.OperationMethod<
  GetStatusRequest,
  SystemStatus,
  GetStatusError,
  PaperlessNgxOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetStatusRequest,
  output: SystemStatus,
  errors: [BadRequest, Forbidden, UnknownPaperlessNgxError],
  protocol: PaperlessNgxProtocol,
  retry: Retry.Retry,
}));
