// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-paperless-ngx/specs/openapi.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
import * as T from "../traits.ts";
import {
  PaperlessNgxProtocol,
  type PaperlessNgxOpError,
  type PaperlessNgxOpContext,
} from "../protocol.ts";
import { paginatePageNumber } from "../pagination.ts";
import { UnknownPaperlessNgxError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { PaperlessNgxOpError, PaperlessNgxOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class Forbidden
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withAuthError),
    [{ status: 403 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

export type AcknowledgeTasksRequestTasksList = Array<number>;
export const AcknowledgeTasksRequestTasksList = /*@__PURE__*/ S.Array(
  S.Number,
) as any as S.Schema<AcknowledgeTasksRequestTasksList>;

export interface AcknowledgeTasksRequest {
  tasks?: AcknowledgeTasksRequestTasksList;
  all?: boolean;
}
export const AcknowledgeTasksRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    tasks: S.optional(AcknowledgeTasksRequestTasksList),
    all: S.optional(S.Boolean),
  }).pipe(
    T.Http({ method: "POST", uri: "/api/tasks/acknowledge/", code: 200 }),
  ),
).annotate({
  identifier: "AcknowledgeTasksRequest",
}) as any as S.Schema<AcknowledgeTasksRequest>;

export interface AcknowledgeTasks {
  result: number;
}
export const AcknowledgeTasks = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    result: S.Number,
  }),
).annotate({
  identifier: "AcknowledgeTasks",
}) as any as S.Schema<AcknowledgeTasks>;

export interface GetTaskRequest {
  /** A unique integer value identifying this Task. */
  id: number;
}
export const GetTaskRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.Number.pipe(T.Label()),
  }).pipe(T.Http({ method: "GET", uri: "/api/tasks/{id}/", code: 200 })),
).annotate({ identifier: "GetTaskRequest" }) as any as S.Schema<GetTaskRequest>;

/** * `consume_file` - Consume File * `train_classifier` - Train Classifier * `sanity_check` - Sanity Check * `index_optimize` - Index Optimize * `mail_fetch` - Mail Fetch * `llm_index` - LLM Index * `empty_trash` - Empty Trash * `check_workflows` - Check Workflows * `bulk_update` - Bulk Update * `reprocess_document` - Reprocess Document * `build_share_link` - Build Share Link * `bulk_delete` - Bulk Delete * `apply_ai_suggestions` - Apply AI Suggestions */
export type TaskTypeEnum =
  | "consume_file"
  | "train_classifier"
  | "sanity_check"
  | "index_optimize"
  | "mail_fetch"
  | "llm_index"
  | "empty_trash"
  | "check_workflows"
  | "bulk_update"
  | "reprocess_document"
  | "build_share_link"
  | "bulk_delete"
  | "apply_ai_suggestions";
export const TaskTypeEnum = S.String;

/** * `scheduled` - Scheduled * `web_ui` - Web UI * `api_upload` - API Upload * `folder_consume` - Folder Consume * `email_consume` - Email Consume * `system` - System * `manual` - Manual */
export type TriggerSourceEnum =
  | "scheduled"
  | "web_ui"
  | "api_upload"
  | "folder_consume"
  | "email_consume"
  | "system"
  | "manual";
export const TriggerSourceEnum = S.String;

/** * `pending` - Pending * `started` - Started * `success` - Success * `failure` - Failure * `revoked` - Revoked */
export type TaskSerializerV10StatusEnum =
  | "pending"
  | "started"
  | "success"
  | "failure"
  | "revoked";
export const TaskSerializerV10StatusEnum = S.String;

export type TaskSerializerV10RelatedDocumentIdsList = Array<number>;
export const TaskSerializerV10RelatedDocumentIdsList = /*@__PURE__*/ S.Array(
  S.Number,
) as any as S.Schema<TaskSerializerV10RelatedDocumentIdsList>;

/** Task serializer for API v10+ using new field names. */
export interface TaskSerializerV10 {
  id: number;
  /** Celery task ID */
  task_id: string;
  /** The kind of work being performed * `consume_file` - Consume File * `train_classifier` - Train Classifier * `sanity_check` - Sanity Check * `index_optimize` - Index Optimize * `mail_fetch` - Mail Fetch * `llm_index` - LLM Index * `empty_trash` - Empty Trash * `check_workflows` - Check Workflows * `bulk_update` - Bulk Update * `reprocess_document` - Reprocess Document * `build_share_link` - Build Share Link * `bulk_delete` - Bulk Delete * `apply_ai_suggestions` - Apply AI Suggestions */
  task_type: TaskTypeEnum;
  task_type_display: string;
  /** What initiated this task * `scheduled` - Scheduled * `web_ui` - Web UI * `api_upload` - API Upload * `folder_consume` - Folder Consume * `email_consume` - Email Consume * `system` - System * `manual` - Manual */
  trigger_source: TriggerSourceEnum;
  trigger_source_display: string;
  status: TaskSerializerV10StatusEnum;
  status_display: string;
  date_created: string;
  date_started: string | null;
  date_done: string | null;
  /** Elapsed time from start to completion */
  duration_seconds: number | null;
  /** Time from task creation to worker pickup */
  wait_time_seconds: number | null;
  /** Structured input parameters for the task */
  input_data: unknown;
  /** Structured result data from task execution */
  result_data: unknown | null;
  related_document_ids: TaskSerializerV10RelatedDocumentIdsList;
  acknowledged: boolean;
  owner: number | null;
}
export const TaskSerializerV10 = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.Number,
    task_id: S.String,
    task_type: TaskTypeEnum,
    task_type_display: S.String,
    trigger_source: TriggerSourceEnum,
    trigger_source_display: S.String,
    status: TaskSerializerV10StatusEnum,
    status_display: S.String,
    date_created: S.String,
    date_started: S.NullOr(S.String),
    date_done: S.NullOr(S.String),
    duration_seconds: S.NullOr(S.Number),
    wait_time_seconds: S.NullOr(S.Number),
    input_data: S.Unknown,
    result_data: S.NullOr(S.Unknown),
    related_document_ids: TaskSerializerV10RelatedDocumentIdsList,
    acknowledged: S.Boolean,
    owner: S.NullOr(S.Number),
  }),
).annotate({
  identifier: "TaskSerializerV10",
}) as any as S.Schema<TaskSerializerV10>;

export interface GetTasksStatusCountRequest {}
export const GetTasksStatusCountRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(
    T.Http({ method: "GET", uri: "/api/tasks/status_counts/", code: 200 }),
  ),
).annotate({
  identifier: "GetTasksStatusCountRequest",
}) as any as S.Schema<GetTasksStatusCountRequest>;

export interface TaskStatusCounts {
  all: number;
  needs_attention: number;
  in_progress: number;
  completed: number;
}
export const TaskStatusCounts = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    all: S.Number,
    needs_attention: S.Number,
    in_progress: S.Number,
    completed: S.Number,
  }),
).annotate({
  identifier: "TaskStatusCounts",
}) as any as S.Schema<TaskStatusCounts>;

export type ListTasksRequestStatusItem =
  | "failure"
  | "pending"
  | "revoked"
  | "started"
  | "success";
export const ListTasksRequestStatusItem = S.String;

export type ListTasksRequestStatusList = Array<
  ListTasksRequestStatusItem | (string & {})
>;
export const ListTasksRequestStatusList = /*@__PURE__*/ S.Array(
  ListTasksRequestStatusItem,
) as any as S.Schema<ListTasksRequestStatusList>;

export type ListTasksRequestTaskTypeItem =
  | "apply_ai_suggestions"
  | "build_share_link"
  | "bulk_delete"
  | "bulk_update"
  | "check_workflows"
  | "consume_file"
  | "empty_trash"
  | "index_optimize"
  | "llm_index"
  | "mail_fetch"
  | "reprocess_document"
  | "sanity_check"
  | "train_classifier";
export const ListTasksRequestTaskTypeItem = S.String;

export type ListTasksRequestTaskTypeList = Array<
  ListTasksRequestTaskTypeItem | (string & {})
>;
export const ListTasksRequestTaskTypeList = /*@__PURE__*/ S.Array(
  ListTasksRequestTaskTypeItem,
) as any as S.Schema<ListTasksRequestTaskTypeList>;

export type ListTasksRequestTriggerSourceItem =
  | "api_upload"
  | "email_consume"
  | "folder_consume"
  | "manual"
  | "scheduled"
  | "system"
  | "web_ui";
export const ListTasksRequestTriggerSourceItem = S.String;

export type ListTasksRequestTriggerSourceList = Array<
  ListTasksRequestTriggerSourceItem | (string & {})
>;
export const ListTasksRequestTriggerSourceList = /*@__PURE__*/ S.Array(
  ListTasksRequestTriggerSourceItem,
) as any as S.Schema<ListTasksRequestTriggerSourceList>;

export interface ListTasksRequest {
  /** Acknowledged */
  acknowledged?: boolean;
  /** Created After */
  date_created_after?: string;
  /** Created Before */
  date_created_before?: string;
  /** Is Complete */
  is_complete?: boolean;
  /** Name */
  name?: string;
  /** Which field to use when ordering the results. */
  ordering?: string;
  owner?: number;
  /** A page number within the paginated result set. */
  page?: number;
  /** Number of results to return per page. */
  page_size?: number;
  /** Result */
  result?: string;
  /** Status * `pending` - Pending * `started` - Started * `success` - Success * `failure` - Failure * `revoked` - Revoked */
  status?: ListTasksRequestStatusList;
  /** Filter tasks by Celery UUID */
  task_id?: string;
  /** Task Type * `consume_file` - Consume File * `train_classifier` - Train Classifier * `sanity_check` - Sanity Check * `index_optimize` - Index Optimize * `mail_fetch` - Mail Fetch * `llm_index` - LLM Index * `empty_trash` - Empty Trash * `check_workflows` - Check Workflows * `bulk_update` - Bulk Update * `reprocess_document` - Reprocess Document * `build_share_link` - Build Share Link * `bulk_delete` - Bulk Delete * `apply_ai_suggestions` - Apply AI Suggestions */
  task_type?: ListTasksRequestTaskTypeList;
  /** Trigger Source * `scheduled` - Scheduled * `web_ui` - Web UI * `api_upload` - API Upload * `folder_consume` - Folder Consume * `email_consume` - Email Consume * `system` - System * `manual` - Manual */
  trigger_source?: ListTasksRequestTriggerSourceList;
}
export const ListTasksRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    acknowledged: S.optional(S.Boolean.pipe(T.Query())),
    date_created_after: S.optional(S.String.pipe(T.Query())),
    date_created_before: S.optional(S.String.pipe(T.Query())),
    is_complete: S.optional(S.Boolean.pipe(T.Query())),
    name: S.optional(S.String.pipe(T.Query())),
    ordering: S.optional(S.String.pipe(T.Query())),
    owner: S.optional(S.Number.pipe(T.Query())),
    page: S.optional(S.Number.pipe(T.Query())),
    page_size: S.optional(S.Number.pipe(T.Query())),
    result: S.optional(S.String.pipe(T.Query())),
    status: S.optional(ListTasksRequestStatusList.pipe(T.Query())),
    task_id: S.optional(S.String.pipe(T.Query())),
    task_type: S.optional(ListTasksRequestTaskTypeList.pipe(T.Query())),
    trigger_source: S.optional(
      ListTasksRequestTriggerSourceList.pipe(T.Query()),
    ),
  }).pipe(T.Http({ method: "GET", uri: "/api/tasks/", code: 200 })),
).annotate({
  identifier: "ListTasksRequest",
}) as any as S.Schema<ListTasksRequest>;

export type PaginatedTaskSerializerV10ListResultsList =
  Array<TaskSerializerV10>;
export const PaginatedTaskSerializerV10ListResultsList = /*@__PURE__*/ S.Array(
  TaskSerializerV10,
) as any as S.Schema<PaginatedTaskSerializerV10ListResultsList>;

export interface PaginatedTaskSerializerV10List {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: PaginatedTaskSerializerV10ListResultsList;
}
export const PaginatedTaskSerializerV10List = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.Number,
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    results: PaginatedTaskSerializerV10ListResultsList,
  }),
).annotate({
  identifier: "PaginatedTaskSerializerV10List",
}) as any as S.Schema<PaginatedTaskSerializerV10List>;

export type ListTasksActiveRequestStatusItem =
  | "failure"
  | "pending"
  | "revoked"
  | "started"
  | "success";
export const ListTasksActiveRequestStatusItem = S.String;

export type ListTasksActiveRequestStatusList = Array<
  ListTasksActiveRequestStatusItem | (string & {})
>;
export const ListTasksActiveRequestStatusList = /*@__PURE__*/ S.Array(
  ListTasksActiveRequestStatusItem,
) as any as S.Schema<ListTasksActiveRequestStatusList>;

export type ListTasksActiveRequestTaskTypeItem =
  | "apply_ai_suggestions"
  | "build_share_link"
  | "bulk_delete"
  | "bulk_update"
  | "check_workflows"
  | "consume_file"
  | "empty_trash"
  | "index_optimize"
  | "llm_index"
  | "mail_fetch"
  | "reprocess_document"
  | "sanity_check"
  | "train_classifier";
export const ListTasksActiveRequestTaskTypeItem = S.String;

export type ListTasksActiveRequestTaskTypeList = Array<
  ListTasksActiveRequestTaskTypeItem | (string & {})
>;
export const ListTasksActiveRequestTaskTypeList = /*@__PURE__*/ S.Array(
  ListTasksActiveRequestTaskTypeItem,
) as any as S.Schema<ListTasksActiveRequestTaskTypeList>;

export type ListTasksActiveRequestTriggerSourceItem =
  | "api_upload"
  | "email_consume"
  | "folder_consume"
  | "manual"
  | "scheduled"
  | "system"
  | "web_ui";
export const ListTasksActiveRequestTriggerSourceItem = S.String;

export type ListTasksActiveRequestTriggerSourceList = Array<
  ListTasksActiveRequestTriggerSourceItem | (string & {})
>;
export const ListTasksActiveRequestTriggerSourceList = /*@__PURE__*/ S.Array(
  ListTasksActiveRequestTriggerSourceItem,
) as any as S.Schema<ListTasksActiveRequestTriggerSourceList>;

export interface ListTasksActiveRequest {
  /** Acknowledged */
  acknowledged?: boolean;
  /** Created After */
  date_created_after?: string;
  /** Created Before */
  date_created_before?: string;
  /** Is Complete */
  is_complete?: boolean;
  /** Name */
  name?: string;
  /** Which field to use when ordering the results. */
  ordering?: string;
  owner?: number;
  /** Result */
  result?: string;
  /** Status * `pending` - Pending * `started` - Started * `success` - Success * `failure` - Failure * `revoked` - Revoked */
  status?: ListTasksActiveRequestStatusList;
  /** Task Type * `consume_file` - Consume File * `train_classifier` - Train Classifier * `sanity_check` - Sanity Check * `index_optimize` - Index Optimize * `mail_fetch` - Mail Fetch * `llm_index` - LLM Index * `empty_trash` - Empty Trash * `check_workflows` - Check Workflows * `bulk_update` - Bulk Update * `reprocess_document` - Reprocess Document * `build_share_link` - Build Share Link * `bulk_delete` - Bulk Delete * `apply_ai_suggestions` - Apply AI Suggestions */
  task_type?: ListTasksActiveRequestTaskTypeList;
  /** Trigger Source * `scheduled` - Scheduled * `web_ui` - Web UI * `api_upload` - API Upload * `folder_consume` - Folder Consume * `email_consume` - Email Consume * `system` - System * `manual` - Manual */
  trigger_source?: ListTasksActiveRequestTriggerSourceList;
}
export const ListTasksActiveRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    acknowledged: S.optional(S.Boolean.pipe(T.Query())),
    date_created_after: S.optional(S.String.pipe(T.Query())),
    date_created_before: S.optional(S.String.pipe(T.Query())),
    is_complete: S.optional(S.Boolean.pipe(T.Query())),
    name: S.optional(S.String.pipe(T.Query())),
    ordering: S.optional(S.String.pipe(T.Query())),
    owner: S.optional(S.Number.pipe(T.Query())),
    result: S.optional(S.String.pipe(T.Query())),
    status: S.optional(ListTasksActiveRequestStatusList.pipe(T.Query())),
    task_type: S.optional(ListTasksActiveRequestTaskTypeList.pipe(T.Query())),
    trigger_source: S.optional(
      ListTasksActiveRequestTriggerSourceList.pipe(T.Query()),
    ),
  }).pipe(T.Http({ method: "GET", uri: "/api/tasks/active/", code: 200 })),
).annotate({
  identifier: "ListTasksActiveRequest",
}) as any as S.Schema<ListTasksActiveRequest>;

export type ListTasksActiveResponseBodyList = Array<TaskSerializerV10>;
export const ListTasksActiveResponseBodyList = /*@__PURE__*/ S.Array(
  TaskSerializerV10,
) as any as S.Schema<ListTasksActiveResponseBodyList>;

export type ListTasksActiveResponse = ListTasksActiveResponseBodyList;
export const ListTasksActiveResponse = /*@__PURE__*/ S.suspend(() =>
  ListTasksActiveResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ListTasksActiveResponse",
}) as any as S.Schema<ListTasksActiveResponse>;

export type ListTasksSummaryRequestStatusItem =
  | "failure"
  | "pending"
  | "revoked"
  | "started"
  | "success";
export const ListTasksSummaryRequestStatusItem = S.String;

export type ListTasksSummaryRequestStatusList = Array<
  ListTasksSummaryRequestStatusItem | (string & {})
>;
export const ListTasksSummaryRequestStatusList = /*@__PURE__*/ S.Array(
  ListTasksSummaryRequestStatusItem,
) as any as S.Schema<ListTasksSummaryRequestStatusList>;

export type ListTasksSummaryRequestTaskTypeItem =
  | "apply_ai_suggestions"
  | "build_share_link"
  | "bulk_delete"
  | "bulk_update"
  | "check_workflows"
  | "consume_file"
  | "empty_trash"
  | "index_optimize"
  | "llm_index"
  | "mail_fetch"
  | "reprocess_document"
  | "sanity_check"
  | "train_classifier";
export const ListTasksSummaryRequestTaskTypeItem = S.String;

export type ListTasksSummaryRequestTaskTypeList = Array<
  ListTasksSummaryRequestTaskTypeItem | (string & {})
>;
export const ListTasksSummaryRequestTaskTypeList = /*@__PURE__*/ S.Array(
  ListTasksSummaryRequestTaskTypeItem,
) as any as S.Schema<ListTasksSummaryRequestTaskTypeList>;

export type ListTasksSummaryRequestTriggerSourceItem =
  | "api_upload"
  | "email_consume"
  | "folder_consume"
  | "manual"
  | "scheduled"
  | "system"
  | "web_ui";
export const ListTasksSummaryRequestTriggerSourceItem = S.String;

export type ListTasksSummaryRequestTriggerSourceList = Array<
  ListTasksSummaryRequestTriggerSourceItem | (string & {})
>;
export const ListTasksSummaryRequestTriggerSourceList = /*@__PURE__*/ S.Array(
  ListTasksSummaryRequestTriggerSourceItem,
) as any as S.Schema<ListTasksSummaryRequestTriggerSourceList>;

export interface ListTasksSummaryRequest {
  /** Acknowledged */
  acknowledged?: boolean;
  /** Created After */
  date_created_after?: string;
  /** Created Before */
  date_created_before?: string;
  /** Number of days to include in aggregation (default 30, min 1, max 365) */
  days?: number;
  /** Is Complete */
  is_complete?: boolean;
  /** Name */
  name?: string;
  /** Which field to use when ordering the results. */
  ordering?: string;
  owner?: number;
  /** Result */
  result?: string;
  /** Status * `pending` - Pending * `started` - Started * `success` - Success * `failure` - Failure * `revoked` - Revoked */
  status?: ListTasksSummaryRequestStatusList;
  /** Task Type * `consume_file` - Consume File * `train_classifier` - Train Classifier * `sanity_check` - Sanity Check * `index_optimize` - Index Optimize * `mail_fetch` - Mail Fetch * `llm_index` - LLM Index * `empty_trash` - Empty Trash * `check_workflows` - Check Workflows * `bulk_update` - Bulk Update * `reprocess_document` - Reprocess Document * `build_share_link` - Build Share Link * `bulk_delete` - Bulk Delete * `apply_ai_suggestions` - Apply AI Suggestions */
  task_type?: ListTasksSummaryRequestTaskTypeList;
  /** Trigger Source * `scheduled` - Scheduled * `web_ui` - Web UI * `api_upload` - API Upload * `folder_consume` - Folder Consume * `email_consume` - Email Consume * `system` - System * `manual` - Manual */
  trigger_source?: ListTasksSummaryRequestTriggerSourceList;
}
export const ListTasksSummaryRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    acknowledged: S.optional(S.Boolean.pipe(T.Query())),
    date_created_after: S.optional(S.String.pipe(T.Query())),
    date_created_before: S.optional(S.String.pipe(T.Query())),
    days: S.optional(S.Number.pipe(T.Query())),
    is_complete: S.optional(S.Boolean.pipe(T.Query())),
    name: S.optional(S.String.pipe(T.Query())),
    ordering: S.optional(S.String.pipe(T.Query())),
    owner: S.optional(S.Number.pipe(T.Query())),
    result: S.optional(S.String.pipe(T.Query())),
    status: S.optional(ListTasksSummaryRequestStatusList.pipe(T.Query())),
    task_type: S.optional(ListTasksSummaryRequestTaskTypeList.pipe(T.Query())),
    trigger_source: S.optional(
      ListTasksSummaryRequestTriggerSourceList.pipe(T.Query()),
    ),
  }).pipe(T.Http({ method: "GET", uri: "/api/tasks/summary/", code: 200 })),
).annotate({
  identifier: "ListTasksSummaryRequest",
}) as any as S.Schema<ListTasksSummaryRequest>;

export interface TaskSummary {
  task_type: string;
  total_count: number;
  pending_count: number;
  success_count: number;
  failure_count: number;
  avg_duration_seconds: number | null;
  avg_wait_time_seconds: number | null;
  last_run: string | null;
  last_success: string | null;
  last_failure: string | null;
}
export const TaskSummary = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    task_type: S.String,
    total_count: S.Number,
    pending_count: S.Number,
    success_count: S.Number,
    failure_count: S.Number,
    avg_duration_seconds: S.NullOr(S.Number),
    avg_wait_time_seconds: S.NullOr(S.Number),
    last_run: S.NullOr(S.String),
    last_success: S.NullOr(S.String),
    last_failure: S.NullOr(S.String),
  }),
).annotate({ identifier: "TaskSummary" }) as any as S.Schema<TaskSummary>;

export type ListTasksSummaryResponseBodyList = Array<TaskSummary>;
export const ListTasksSummaryResponseBodyList = /*@__PURE__*/ S.Array(
  TaskSummary,
) as any as S.Schema<ListTasksSummaryResponseBodyList>;

export type ListTasksSummaryResponse = ListTasksSummaryResponseBodyList;
export const ListTasksSummaryResponse = /*@__PURE__*/ S.suspend(() =>
  ListTasksSummaryResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ListTasksSummaryResponse",
}) as any as S.Schema<ListTasksSummaryResponse>;

export interface RunTaskRequest {
  task_type: TaskTypeEnum | (string & {});
}
export const RunTaskRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    task_type: TaskTypeEnum,
  }).pipe(T.Http({ method: "POST", uri: "/api/tasks/run/", code: 200 })),
).annotate({ identifier: "RunTaskRequest" }) as any as S.Schema<RunTaskRequest>;

export interface RunTask {
  task_id: string;
}
export const RunTask = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    task_id: S.String,
  }),
).annotate({ identifier: "RunTask" }) as any as S.Schema<RunTask>;

export type AcknowledgeTasks2Error =
  | BadRequest
  | Forbidden
  | PaperlessNgxOpError;
/** Acknowledge a list of tasks, or all visible unacknowledged tasks */
export const acknowledgeTasks2: API.OperationMethod<
  AcknowledgeTasksRequest,
  AcknowledgeTasks,
  AcknowledgeTasks2Error,
  PaperlessNgxOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AcknowledgeTasksRequest,
  output: AcknowledgeTasks,
  errors: [BadRequest, Forbidden, UnknownPaperlessNgxError],
  protocol: PaperlessNgxProtocol,
  retry: Retry.Retry,
}));

export type GetTaskError = Forbidden | NotFound | PaperlessNgxOpError;
export const getTask: API.OperationMethod<
  GetTaskRequest,
  TaskSerializerV10,
  GetTaskError,
  PaperlessNgxOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetTaskRequest,
  output: TaskSerializerV10,
  errors: [Forbidden, NotFound, UnknownPaperlessNgxError],
  protocol: PaperlessNgxProtocol,
  retry: Retry.Retry,
}));

export type GetTasksStatusCountError =
  | BadRequest
  | Forbidden
  | PaperlessNgxOpError;
/** Aggregated task counts for task UI sections. */
export const getTasksStatusCount: API.OperationMethod<
  GetTasksStatusCountRequest,
  TaskStatusCounts,
  GetTasksStatusCountError,
  PaperlessNgxOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetTasksStatusCountRequest,
  output: TaskStatusCounts,
  errors: [BadRequest, Forbidden, UnknownPaperlessNgxError],
  protocol: PaperlessNgxProtocol,
  retry: Retry.Retry,
}));

export type ListTasksError =
  | BadRequest
  | Forbidden
  | NotFound
  | PaperlessNgxOpError;
export const listTasks: API.PaginatedOperationMethod<
  ListTasksRequest,
  PaginatedTaskSerializerV10List,
  ListTasksError,
  PaperlessNgxOpContext,
  TaskSerializerV10
> = /*@__PURE__*/ API.makePaginated(
  () => ({
    input: ListTasksRequest,
    output: PaginatedTaskSerializerV10List,
    errors: [BadRequest, Forbidden, NotFound, UnknownPaperlessNgxError],
    protocol: PaperlessNgxProtocol,
    retry: Retry.Retry,
    pagination: {
      mode: "page",
      inputToken: "page",
      outputToken: "next",
      items: "results",
    } as const,
  }),
  paginatePageNumber,
) as any;

export type ListTasksActiveError = BadRequest | Forbidden | PaperlessNgxOpError;
/** Currently pending and running tasks (capped at 50). */
export const listTasksActive: API.OperationMethod<
  ListTasksActiveRequest,
  ListTasksActiveResponse,
  ListTasksActiveError,
  PaperlessNgxOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListTasksActiveRequest,
  output: ListTasksActiveResponse,
  errors: [BadRequest, Forbidden, UnknownPaperlessNgxError],
  protocol: PaperlessNgxProtocol,
  retry: Retry.Retry,
}));

export type ListTasksSummaryError =
  | BadRequest
  | Forbidden
  | PaperlessNgxOpError;
/** Aggregated task statistics per task_type over the last N days (default 30). */
export const listTasksSummary: API.OperationMethod<
  ListTasksSummaryRequest,
  ListTasksSummaryResponse,
  ListTasksSummaryError,
  PaperlessNgxOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListTasksSummaryRequest,
  output: ListTasksSummaryResponse,
  errors: [BadRequest, Forbidden, UnknownPaperlessNgxError],
  protocol: PaperlessNgxProtocol,
  retry: Retry.Retry,
}));

export type RunTask2Error = BadRequest | Forbidden | PaperlessNgxOpError;
/** Manually dispatch a background task. Superuser only. */
export const runTask2: API.OperationMethod<
  RunTaskRequest,
  RunTask,
  RunTask2Error,
  PaperlessNgxOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: RunTaskRequest,
  output: RunTask,
  errors: [BadRequest, Forbidden, UnknownPaperlessNgxError],
  protocol: PaperlessNgxProtocol,
  retry: Retry.Retry,
}));
