/**
 * Render the coverage model as the markdown a human reads. The JSON beside it is the complete
 * record; this file is the summary, and it says so rather than trying to print 517 rows.
 */
import type { Coverage, Row, SystemCoverage } from './api-coverage-model.ts';
import { OWNERSHIP } from './proxmox-ownership.ts';

const pct = (n: number, of: number): string => (of === 0 ? '—' : `${((n / of) * 100).toFixed(1)}%`);

/** `/cluster/sdn/vnets/{vnet}/subnets` -> `/cluster/sdn`. Two segments is the useful grain. */
const area = (path: string): string => `/${path.split('/').filter(Boolean).slice(0, 2).join('/')}`;

const uncoveredAreas = (sys: SystemCoverage, limit: number): string[] => {
  const counts = new Map<string, number>();
  for (const r of sys.rows) {
    if (r.owner !== null) continue;
    counts.set(area(r.path), (counts.get(area(r.path)) ?? 0) + 1);
  }
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, limit)
    .map(([a, n]) => `| \`${a}\` | ${String(n)} |`);
};

const perResource = (coverage: Coverage): string[] => {
  const rows = new Map<string, Row[]>();
  for (const sys of coverage.systems) {
    for (const r of sys.rows) {
      if (r.owner === null) continue;
      for (const owner of r.owner.split(', ')) {
        rows.set(owner, [...(rows.get(owner) ?? []), r]);
      }
    }
  }
  return OWNERSHIP.map((o) => {
    const mine = rows.get(o.resource) ?? [];
    const unenforced = mine.reduce((n, r) => n + r.unenforced.length, 0);
    return `| \`${o.resource}\` | ${o.system.toUpperCase()} | ${String(mine.length)} | ${String(unenforced)} | \`${o.file}\` |`;
  });
};

const totalsRow = (s: SystemCoverage): string => {
  const t = s.totals;
  return (
    `| ${s.system.toUpperCase()} | ${s.version} | \`${s.sha256Short}…\` | ` +
    `${String(t.writeEndpoints)} | ${String(t.ownedWriteEndpoints)} (${pct(t.ownedWriteEndpoints, t.writeEndpoints)}) | ` +
    `${String(t.writePaths)} | ${String(t.ownedWritePaths)} | ` +
    `${String(t.unenforcedParams)} | ${String(t.ownedUnenforcedParams)} |`
  );
};

export const renderMarkdown = (coverage: Coverage): string => {
  const [pve, pbs] = coverage.systems;
  if (pve === undefined || pbs === undefined) throw new Error('coverage: both systems required');
  const lines = [
    '# Proxmox API coverage',
    '',
    '<!-- GENERATED by scripts/api-coverage.ts — DO NOT EDIT BY HAND.',
    '     Regenerate: bun run api:coverage   ·   Verify: bun run api:coverage --check -->',
    '',
    `Generated by \`${coverage.generator.script}\` v${coverage.generator.version} from the vendor`,
    'schemas recorded in [`schemas/manifest.json`](../schemas/manifest.json):',
    '',
    ...coverage.systems.map(
      (s) => `- **${s.product}** \`${s.version}\` — sha256 \`${s.sha256Short}…\``,
    ),
    '',
    'Every row below is a fact about *those* documents. A different cluster version is a different',
    'report — refresh the manifest and regenerate rather than reading this one as timeless.',
    '',
    '## What this answers',
    '',
    'For every endpoint that can CREATE, UPDATE or DELETE state, which `@homeflare/alchemy` Resource',
    'owns it — or nothing. `GET` is excluded: a read cannot be refused by a constraint we dropped.',
    '',
    '⚠️ **Unenforced parameters** carry a `maxLength`, `minLength`, `minimum`, `maximum`, `pattern`',
    'or `format` in the vendor schema that nothing local checks. Two kinds are subtracted, because',
    'something does check them. `enum` never counted: the generated types keep `type`, `enum` and',
    '`optional`, so an `enum` is already a string-literal union. And since 2026-09-22 the generated',
    'constraint tables (`packages/alchemy/src/proxmox/generated/constraints/`) enforce `maxLength`,',
    '`minLength`, `minimum`, `maximum` and translated `pattern` rules at PLAN time for the endpoints',
    'they cover — this report subtracts exactly those, per parameter and per rule kind.',
    '',
    '⛔ A `format` IS NEVER SUBTRACTED. The tables record the name and check nothing: `pve-node` and',
    '`pve-calendar-event` are validators the vendor implements server-side and publishes nothing',
    'about. The **owned** column is therefore the surface where a declaration the vendor will refuse',
    'still plans clean — and for PVE it is now almost entirely format names and property strings.',
    '',
    '⛔ **The endpoint list and the counts are derived from the schema. The owner column is not.** It',
    'comes from a hand-written ledger (`scripts/proxmox-ownership-*.ts`) that',
    '`tests/api-coverage.test.ts` checks against the schema in one direction only: every endpoint a',
    'Resource claims must exist. A write this package makes and the ledger fails to mention would',
    'understate coverage and nothing would fail — so treat `none` as "not recorded here", not as',
    'proof.',
    '',
    '| system | version | sha256 | write endpoints | owned | write paths | owned paths | unenforced params | owned unenforced |',
    '| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |',
    totalsRow(pve),
    totalsRow(pbs),
    '',
    '## Owned endpoints, by Resource',
    '',
    '| resource | system | write endpoints | unenforced params | source |',
    '| --- | --- | ---: | ---: | --- |',
    ...perResource(coverage),
    '',
  ];

  if (coverage.broken.length > 0) {
    lines.push(
      '## Endpoints a Resource calls that the vendor does not implement',
      '',
      '⛔ These are defects, found by checking the ledger against the schema. Each one is a call that',
      'can only fail at apply time.',
      '',
      '| resource | call | why | source |',
      '| --- | --- | --- | --- |',
      ...coverage.broken.map(
        (f) => `| \`${f.resource}\` | \`${f.method} ${f.path}\` | ${f.why} | \`${f.file}\` |`,
      ),
      '',
    );
  }

  lines.push(
    '## Deliberately unreachable, and confirmed absent',
    '',
    'Paths the source documents as not implemented by the vendor. The schema agrees, and a test',
    'fails if Proxmox ever adds one — which would make the comment that calls it unreachable wrong.',
    '',
    '| resource | call | why |',
    '| --- | --- | --- |',
    ...coverage.refuted.map((f) => `| \`${f.resource}\` | \`${f.method} ${f.path}\` | ${f.why} |`),
    '',
    '## Where the uncovered write surface is',
    '',
    'Write endpoints with no Resource, by area. This replaces hand-counted gap lists: it is derived,',
    'so it cannot drift from the schema it was generated against.',
    '',
    '### PVE',
    '',
    '| area | uncovered write endpoints |',
    '| --- | ---: |',
    ...uncoveredAreas(pve, 12),
    '',
    '### PBS',
    '',
    '| area | uncovered write endpoints |',
    '| --- | ---: |',
    ...uncoveredAreas(pbs, 12),
    '',
  );

  if (coverage.availableUnused.length > 0) {
    lines.push(
      '## Schemas in hand with nothing generated from them',
      '',
      'Recorded in the manifest so a gap list can stop guessing about them. No provider family',
      'exists for these yet; they are available, not adopted.',
      '',
      '| id | product | version |',
      '| --- | --- | --- |',
      ...coverage.availableUnused.map((u) => `| \`${u.id}\` | ${u.product} | \`${u.version}\` |`),
      '',
    );
  }

  lines.push(
    '## The complete record',
    '',
    '[`api-coverage.json`](./api-coverage.json) carries every write endpoint with its owner and its',
    'unenforced parameter names. This page is the summary; that file is the authority.',
    '',
  );
  return lines.join('\n');
};
