/**
 * Copy each workspace package's version from its package.json into its src/version.ts.
 *
 * ★ ONE SCRIPT FOR THE WHOLE WORKSPACE, DISCOVERED RATHER THAN LISTED. It reads the
 *   root `workspaces` globs, so adding packages/foo needs no edit here. A hardcoded list
 *   is the thing that goes stale silently: the new package simply never gets synced, and
 *   ships a VERSION literal of '0.0.0' that nothing contradicts.
 *
 * ★ WHY A GENERATED FILE RATHER THAN READING package.json AT RUNTIME. A Worker bundle has
 *   no package.json beside it — `import pkg from '../package.json'` either inlines the
 *   whole manifest or fails to resolve, depending on the bundler. A generated one-line
 *   module is the only form that survives every consumer.
 *
 * ⛔ src/version.ts IS GENERATED in every package. Never hand-edit one; changesets owns
 *   the number and this script owns the file. Runs from `bun run version` (the changesets
 *   bump) so a release can never ship a stale literal.
 */
import { Glob } from 'bun';

const root = new URL('..', import.meta.url);
const rootPkg = await Bun.file(new URL('package.json', root)).json();
const patterns: readonly string[] = rootPkg.workspaces ?? [];

let synced = 0;

for (const pattern of patterns) {
  // `packages/*` -> each directory holding a package.json.
  const glob = new Glob(`${pattern}/package.json`);

  // ⚠️ oxlint flags the awaits below as sequential. That is deliberate: this runs over a
  //   handful of packages during a release, and a Promise.all would trade readable
  //   output ordering for nothing measurable.
  // oxlint-disable no-await-in-loop
  for await (const relative of glob.scan({ cwd: root.pathname })) {
    const manifestUrl = new URL(relative, root);
    const manifest = await Bun.file(manifestUrl).json();

    // ⚠️ Private packages have no published version to carry; skip rather than writing
    //   a literal that means nothing.
    if (manifest.private === true) continue;

    const versionUrl = new URL('src/version.ts', new URL('./', manifestUrl));
    if (!(await Bun.file(versionUrl).exists())) continue;

    await Bun.write(
      versionUrl,
      `// ⛔ GENERATED by scripts/sync-versions.ts — do not edit. Source: package.json.\n` +
        `export const VERSION: string = '${manifest.version}';\n`,
    );

    console.log(`${manifest.name} -> ${manifest.version}`);
    synced += 1;
  }
  // oxlint-enable no-await-in-loop
}

if (synced === 0) {
  // ⚠️ Zero is never correct here and must not pass silently: it means the globs matched
  //   nothing, which would let a release ship every package claiming 0.0.0.
  console.error('sync-versions: matched no packages — check the root workspaces globs');
  process.exit(1);
}
