/**
 * Copy each workspace package's version from its package.json into its src/version.ts.
 *
 * ★ ONE SCRIPT FOR THE WHOLE WORKSPACE, DISCOVERED RATHER THAN LISTED. It reads the
 *   root `workspaces` globs, so adding packages/foo needs no edit here. A hardcoded list
 *   is the thing that goes stale silently: the new package simply never gets synced, and
 *   ships a VERSION literal of '0.0.0' that nothing contradicts.
 *
 * ★ WHY A GENERATED FILE RATHER THAN READING package.json AT RUNTIME. A Worker bundle has
 *   no package.json beside it — `import pkg from '../package.json'` either inlines the
 *   whole manifest or fails to resolve, depending on the bundler. A generated one-line
 *   module is the only form that survives every consumer.
 *
 * ⛔ src/version.ts IS GENERATED in every package. Never hand-edit one; changesets owns
 *   the number and this script owns the file. Runs from `bun run version` (the changesets
 *   bump) so a release can never ship a stale literal.
 *
 * ⛔ A package's `site.example.json` carries the version too, as `deriveVersion`.
 *   @homeflare/site refuses any site whose `deriveVersion` differs from the installed
 *   package, so an example left one version behind would refuse to load the moment a
 *   consumer copied it — and its own test fails the Version Packages PR.
 */
import { Glob } from 'bun';

/**
 * Rewrite `"deriveVersion": "…"` in place. ★ A regex, not parse-and-stringify: the file is
 *   formatted for people, and re-serialising it would reflow every line of the example.
 */
async function syncExample(exampleUrl: URL, version: string): Promise<boolean> {
  const file = Bun.file(exampleUrl);
  if (!(await file.exists())) return false;
  const pattern = /("deriveVersion"\s*:\s*")[^"]*(")/g;
  const text = await file.text();
  const matches = text.match(pattern)?.length ?? 0;
  if (matches !== 1) {
    // ⚠️ Zero or two means the file changed shape; guessing which to rewrite is worse
    //   than stopping the release here.
    throw new Error(`${exampleUrl.pathname}: expected one "deriveVersion", found ${matches}`);
  }
  await Bun.write(exampleUrl, text.replace(pattern, `$1${version}$2`));
  return true;
}

const root = new URL('..', import.meta.url);
const rootPkg = await Bun.file(new URL('package.json', root)).json();
const patterns: readonly string[] = rootPkg.workspaces ?? [];

let synced = 0;

for (const pattern of patterns) {
  // `packages/*` -> each directory holding a package.json.
  const glob = new Glob(`${pattern}/package.json`);

  // ⚠️ oxlint flags the awaits below as sequential. That is deliberate: this runs over a
  //   handful of packages during a release, and a Promise.all would trade readable
  //   output ordering for nothing measurable.
  // oxlint-disable no-await-in-loop
  for await (const relative of glob.scan({ cwd: root.pathname })) {
    const manifestUrl = new URL(relative, root);
    const manifest = await Bun.file(manifestUrl).json();

    // ⚠️ Private packages have no published version to carry; skip rather than writing
    //   a literal that means nothing.
    if (manifest.private === true) continue;

    const versionUrl = new URL('src/version.ts', new URL('./', manifestUrl));
    if (!(await Bun.file(versionUrl).exists())) continue;

    await Bun.write(
      versionUrl,
      `// ⛔ GENERATED by scripts/sync-versions.ts — do not edit. Source: package.json.\n` +
        `export const VERSION: string = '${manifest.version}';\n`,
    );

    const example = new URL('site.example.json', new URL('./', manifestUrl));
    const withExample = (await syncExample(example, manifest.version))
      ? ' (+ site.example.json)'
      : '';

    console.log(`${manifest.name} -> ${manifest.version}${withExample}`);
    synced += 1;
  }
  // oxlint-enable no-await-in-loop
}

if (synced === 0) {
  // ⚠️ Zero is never correct here and must not pass silently: it means the globs matched
  //   nothing, which would let a release ship every package claiming 0.0.0.
  console.error('sync-versions: matched no packages — check the root workspaces globs');
  process.exit(1);
}
