// AUTO-GENERATED by scripts/generate.ts from .generated-specs (apidoc.js, via scripts/apidoc.ts — see its header). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as T from "../traits.ts";
import {
  ProxmoxBackupProtocol,
  type ProxmoxBackupOpError,
  type ProxmoxBackupOpContext,
} from "../protocol.ts";
import * as Retry from "../retry.ts";

export type { ProxmoxBackupOpError, ProxmoxBackupOpContext };

export type CreatePushRequestGroupFilterList = Array<string>;
export const CreatePushRequestGroupFilterList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<CreatePushRequestGroupFilterList>;

export interface CreatePushRequest {
  /** Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...). */
  burst_in?: string;
  /** Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...). */
  burst_out?: string;
  /** Only synchronize encrypted backup snapshots, exclude others. */
  encrypted_only?: string;
  /** ID to uniquely identify encryption/decription key */
  encryption_key?: string;
  /** List of group filters. */
  group_filter?: CreatePushRequestGroupFilterList;
  /** How many levels of namespaces should be operated on (0 == no recursion, empty == automatic full recursion, namespace depths reduce maximum allowed value) */
  max_depth?: string;
  /** Namespace. */
  ns?: string;
  /** Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...). */
  rate_in?: string;
  /** Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...). */
  rate_out?: string;
  /** Remote ID. */
  remote: string;
  /** Namespace. */
  remote_ns?: string;
  /** Datastore name. */
  remote_store: string;
  /** Delete vanished backups. This removes the local copy if the remote backup was deleted. */
  remove_vanished?: string;
  /** Datastore name. */
  store: string;
  /** Limit transfer to last N snapshots (per group), skipping others */
  transfer_last?: string;
  /** Only synchronize verified backup snapshots, exclude others. */
  verified_only?: string;
  /** The number of worker threads to process groups in parallel. */
  worker_threads?: string;
}
export const CreatePushRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    burst_in: S.optional(S.String.pipe(T.Body("burst-in"))),
    burst_out: S.optional(S.String.pipe(T.Body("burst-out"))),
    encrypted_only: S.optional(S.String.pipe(T.Body("encrypted-only"))),
    encryption_key: S.optional(S.String.pipe(T.Body("encryption-key"))),
    group_filter: S.optional(
      CreatePushRequestGroupFilterList.pipe(T.Body("group-filter")),
    ),
    max_depth: S.optional(S.String.pipe(T.Body("max-depth"))),
    ns: S.optional(S.String),
    rate_in: S.optional(S.String.pipe(T.Body("rate-in"))),
    rate_out: S.optional(S.String.pipe(T.Body("rate-out"))),
    remote: S.String,
    remote_ns: S.optional(S.String.pipe(T.Body("remote-ns"))),
    remote_store: S.String.pipe(T.Body("remote-store")),
    remove_vanished: S.optional(S.String.pipe(T.Body("remove-vanished"))),
    store: S.String,
    transfer_last: S.optional(S.String.pipe(T.Body("transfer-last"))),
    verified_only: S.optional(S.String.pipe(T.Body("verified-only"))),
    worker_threads: S.optional(S.String.pipe(T.Body("worker-threads"))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/push",
      code: 200,
      contentType: "form-urlencoded",
    }),
  ),
).annotate({
  identifier: "CreatePushRequest",
}) as any as S.Schema<CreatePushRequest>;

export interface CreatePushResponse {}
export const CreatePushResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "CreatePushResponse",
}) as any as S.Schema<CreatePushResponse>;

export type CreatePushError = ProxmoxBackupOpError;
/** Push store to other repository */
export const createPush: API.OperationMethod<
  CreatePushRequest,
  CreatePushResponse,
  CreatePushError,
  ProxmoxBackupOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreatePushRequest,
  output: CreatePushResponse,
  errors: [],
  protocol: ProxmoxBackupProtocol,
  retry: Retry.Retry,
}));
