/**
 * The two smaller rendered files: actionlint's config and the changeset config.
 * (Dependabot was the third; it grew a group and a schedule rule, so it is `dependabot.ts`.)
 *
 * ★ EACH ONE WAS MEASURED BEFORE IT WAS RENDERED (2026-09-22, across 13 repositories):
 *     · `.changeset/config.json` — byte-identical apart from the repository name in 11 of
 *       13. The three that differed did so by accident: two pinned an older `$schema`
 *       (3.1.4 against 4.0.1) and one used `@changesets/cli/changelog` instead of the
 *       GitHub changelog everyone else had, which silently drops PR links from releases.
 *     · `.github/actionlint.yaml` — 12 of 13 had it, with three wordings of one comment.
 *       The one without it is the one repository still on `ubuntu-latest`, which is the
 *       only case where it is genuinely not needed. That is an input, not an exception.
 */
import type { RepoShape } from './shape.ts';

/**
 * ⚠️ PINNED, NOT `latest`. `unpkg.com/@changesets/config@latest/schema.json` would change
 *   what editors validate against without a commit, and the two repositories that drifted
 *   here drifted by being pinned to different versions — not by being pinned.
 */
const CHANGESET_SCHEMA = '4.0.1';

/**
 * `.changeset/config.json`.
 *
 * ⛔ `privatePackages` IS WRITTEN ONLY FOR A REPOSITORY THAT DOES NOT PUBLISH, AND BOTH
 *   OF ITS FIELDS ARE REQUIRED. `@changesets/cli` silently versions nothing when
 *   `version` is absent, so a private repository without this key opens a Version
 *   Packages PR that changes no version and tags no release — a release pipeline that
 *   reports success and ships nothing.
 */
export function renderChangesetConfig(shape: RepoShape): string {
  const config = {
    $schema: `https://unpkg.com/@changesets/config@${CHANGESET_SCHEMA}/schema.json`,
    // ★ `@changesets/changelog-github` over the built-in: it writes the pull request and
    //   author into CHANGELOG.md, which is the difference between a changelog you can
    //   audit and a list of sentences.
    changelog: ['@changesets/changelog-github', { repo: `${shape.owner}/${shape.repository}` }],
    commit: false,
    fixed: [] as string[],
    linked: [] as string[],
    access: shape.publishes ? 'public' : 'restricted',
    baseBranch: 'main',
    updateInternalDependencies: 'patch',
    ignore: [] as string[],
    ...(shape.publishes ? {} : { privatePackages: { version: true, tag: false } }),
  };
  return `${JSON.stringify(config, undefined, 2)}\n`;
}

/**
 * `.github/actionlint.yaml` — rendered only for a self-hosted runner.
 *
 * ★ DECLARED, NOT SUPPRESSED. actionlint's `runner-label` rule stays on, so a typo'd
 *   label (`homeflare-mnii`) still fails the `workflow lint` job rather than silently
 *   queueing a job no runner ever claims. Measured 2026-09-22 with actionlint 1.7.12: an
 *   undeclared `homeflare-mini` is an error, not a warning, so this file is the reason
 *   twelve repositories are green rather than a nicety.
 */
export function renderActionlintConfig(shape: RepoShape): string | undefined {
  if (shape.runner !== 'mini') return undefined;
  return `# actionlint's list of self-hosted runner labels (its \`runner-label\` check).
#
# 🤖 RENDERED BY @homeflare/config — DO NOT EDIT THIS FILE BY HAND.
#    Refresh with \`bun run repo-shape:refresh\`.
#
# ★ DECLARED, NOT SUPPRESSED: the rule stays on, so a typo'd label (\`homeflare-mnii\`)
#   still fails the \`workflow lint\` job rather than queueing a job no runner claims.
#   \`homeflare-mini\` is the interim runner on the Mac mini (homeflare-mini's
#   docs/ci-runner.md); setting this repository's shape to \`runner: 'github'\` removes
#   this file with the \`runs-on\` that needed it.
self-hosted-runner:
  labels:
    - homeflare-mini
`;
}
