/**
 * `.github/dependabot.yml`, rendered.
 *
 * ★ MEASURED BEFORE IT WAS RENDERED (2026-09-22): 1 of 14 repositories had a Dependabot
 *   config. Twelve took no dependency or Action updates at all, and nothing said so.
 *
 * ⛔ `@homeflare/*` IS IGNORED HERE, NOT GROUPED (retired 2026-09-23, kit auto-bumper
 *   design, Tim). A `homeflare` group and a rendered `dependabot-automerge.yml`
 *   used to carry kit releases into a consumer; both are gone. `homeflare-bumper` does
 *   that job now, over `workflow_dispatch` from this repo's own release, with a schedule
 *   backstop — a Dependabot bump running at the same time would open a SECOND, competing
 *   pull request for the same version bump. The `ignore` entry below is what stops that:
 *   Dependabot never proposes `@homeflare/*` at all, so there is only ever one bump PR.
 *
 * Every Dependabot claim below was read from GitHub's docs or dependabot-core's source on
 * 2026-09-22 (dependabot-core v0.397.0); `docs/repo-shape-dependabot.md` has the citations.
 */
import type { RepoShape } from './shape.ts';

/** The first-party scope. Every package the kit publishes is under it. */
export const HOMEFLARE_PATTERN = '@homeflare/*';

/**
 * ★ SEVEN DAYS. A third-party release is proposed once it is a week old rather than on
 *   Dependabot's undocumented-but-real 3-day default — that is also the supply-chain
 *   half, since a compromised release is usually yanked within days.
 */
export const THIRD_PARTY_COOLDOWN_DAYS = 7;

/** `.github/dependabot.yml`. */
export function renderDependabot(shape: RepoShape): string {
  // ⚠️ `directories`, not `directory`, for bun: a workspace keeps a dependency in the
  //   package that declares it, so pointing only at `/` leaves every `packages/*`
  //   manifest unwatched — and the symptom is silence, not an error.
  const bunDirs = shape.publishes ? ['/', '/packages/*'] : ['/'];
  return `# Dependabot for ${shape.repository}.
#
# 🤖 RENDERED BY @homeflare/config — DO NOT EDIT THIS FILE BY HAND.
#    Refresh with \`bun run repo-shape:refresh\`.
#
# ⛔ THIS FILE LIVES AT .github/dependabot.yml, NOT IN .github/workflows/. Dependabot is a
#   platform feature, not an Action — a config placed among the workflows is silently
#   ignored, and the symptom is simply that no pull requests ever arrive. Measured
#   2026-09-22: 13 of 14 HomeFlare repositories had no dependabot config at all, so their
#   Actions and their toolchain went stale invisibly, which is exactly how nothing fails.
#
# ★ WHY GROUPED RATHER THAN ONE PR PER DEPENDENCY. The default opens a pull request per
#   outdated package; that is a trickle nobody reviews properly. Each group below is a set
#   that is either safe to take together or needs deciding together.
#
# ★ THE BILLING LOCK DOES NOT STOP THIS FILE. Dependabot runs as a GitHub-hosted "dynamic"
#   workflow that GitHub's docs say "does not count towards your included GitHub Actions
#   minutes"; measured 2026-09-22, a private estate repository's Dependabot job got a hosted
#   runner 86 minutes after that account's ordinary hosted jobs were refused for billing.
#   It cannot use the mini anyway: a self-hosted Dependabot runner must be Linux x64 with
#   Docker, and the mini's runners are arm64 containers with no Docker socket.
version: 2

updates:
  # ── The toolchain (bun.lock) ────────────────────────────────────────────────
  # ⚠️ STILL BLOCKED UPSTREAM, 2026-09-22 — unrelated to the ignore below. bun 1.4 writes
  #   bun.lock \`lockfileVersion\` 2 and Dependabot's updater bundles bun 1.3.14, which reads
  #   up to 1, so this whole block fails in every estate repository with "Unsupported
  #   bun.lock 'lockfileVersion' 2" before it reads a single manifest. The fix is
  #   dependabot/dependabot-core pull request 16071. The github-actions block is unaffected.
  - package-ecosystem: bun
    directories:
${bunDirs.map((dir) => `      - ${dir}`).join('\n')}
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: America/New_York
    cooldown:
      default-days: ${THIRD_PARTY_COOLDOWN_DAYS}
    # ⛔ NEVER PROPOSED HERE. \`homeflare-bumper\` opens the one pull request that bumps
    #   \`@homeflare/*\` (kit auto-bumper design, Tim 2026-09-23) — a Dependabot
    #   update for the same package would race it and, on the weeks they disagree, leave
    #   two open pull requests fighting over the same \`package.json\` line.
    ignore:
      - dependency-name: '${HOMEFLARE_PATTERN}'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: scope
    labels: [dependencies]
    groups:
      # oxfmt and oxlint move together and only affect style. Minor and patch bumps are
      # noise unless they fail CI, which is what CI is for.
      lint-and-format:
        patterns: ['oxfmt', 'oxlint']
        update-types: [minor, patch]

      # ⚠️ MAJORS EXCLUDED DELIBERATELY. TypeScript majors change what typechecks;
      #   changesets majors have renamed inputs and dropped compatibility (the action's v2
      #   did both). These want reading, not merging on green.
      build-tooling:
        patterns: ['typescript', '@changesets/*', '@types/bun']
        update-types: [minor, patch]

  # ── The workflows themselves ────────────────────────────────────────────────
  # ★ Actions go stale invisibly: nothing fails, they just keep running old code. The
  #   estate's first workflows pinned checkout@v5 (current: v7) and changesets/action@v1
  #   (current: v2, with every input renamed) — measured 2026-09-15.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: America/New_York
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'ci'
    labels: [dependencies, github-actions]
    groups:
      actions:
        patterns: ['*']
        update-types: [minor, patch]
`;
}
