/**
 * `.github/dependabot.yml`, rendered — and the one group that carries kit releases.
 *
 * ★ MEASURED BEFORE IT WAS RENDERED (2026-09-22): 1 of 14 repositories had a Dependabot
 *   config. Twelve took no dependency or Action updates at all, and nothing said so.
 *
 * ★ THE `homeflare` GROUP IS HOW A KIT RELEASE REACHES A CONSUMER (Tim, 2026-09-23:
 *   "Dependabot, grouped", checked daily, merged on green). Measured the same day, the
 *   leg nobody automated had drifted: proxmox and mini pinned `@homeflare/alchemy` 0.13.0
 *   while the kit had published 0.19.1. `automerge.ts` renders the workflow that arms
 *   auto-merge on this group's pull request and on nothing else.
 *
 * Every Dependabot claim below was read from GitHub's docs or dependabot-core's source on
 * 2026-09-22 (dependabot-core v0.397.0); `docs/repo-shape-dependabot.md` has the citations.
 */
import type { RepoShape } from './shape.ts';

/**
 * The group's identifier. ⛔ IT IS ALSO HALF OF A BRANCH NAME the auto-merge workflow
 *   matches — dependabot-core names a group's branch `dependabot/bun/<group>-<10 hex>`
 *   (branch_namer/dependency_group_strategy.rb) — so it is exported, not retyped there.
 *   Dependabot requires an identifier that starts and ends with a letter.
 */
export const HOMEFLARE_GROUP = 'homeflare';

/** The first-party scope. Every package the kit publishes is under it. */
export const HOMEFLARE_PATTERN = '@homeflare/*';

/**
 * ★ SEVEN DAYS FOR THIRD-PARTY VERSIONS. The bun block has to run daily for the kit's sake
 *   (see below), so the weekly pace the estate had for everything else is kept by age
 *   instead of by calendar: a third-party release is proposed once it is a week old. That
 *   is also the supply-chain half — a compromised release is usually yanked within days.
 */
export const THIRD_PARTY_COOLDOWN_DAYS = 7;

/** `.github/dependabot.yml`. */
export function renderDependabot(shape: RepoShape): string {
  // ⚠️ `directories`, not `directory`, for bun: a workspace keeps a dependency in the
  //   package that declares it, so pointing only at `/` leaves every `packages/*`
  //   manifest unwatched — and the symptom is silence, not an error.
  const bunDirs = shape.publishes ? ['/', '/packages/*'] : ['/'];
  return `# Dependabot for ${shape.repository}.
#
# 🤖 RENDERED BY @homeflare/config — DO NOT EDIT THIS FILE BY HAND.
#    Refresh with \`bun run repo-shape:refresh\`.
#
# ⛔ THIS FILE LIVES AT .github/dependabot.yml, NOT IN .github/workflows/. Dependabot is a
#   platform feature, not an Action — a config placed among the workflows is silently
#   ignored, and the symptom is simply that no pull requests ever arrive. Measured
#   2026-09-22: 13 of 14 HomeFlare repositories had no dependabot config at all, so their
#   Actions and their toolchain went stale invisibly, which is exactly how nothing fails.
#
# ★ WHY GROUPED RATHER THAN ONE PR PER DEPENDENCY. The default opens a pull request per
#   outdated package; that is a trickle nobody reviews properly. Each group below is a set
#   that is either safe to take together or needs deciding together.
#
# ★ THE BILLING LOCK DOES NOT STOP THIS FILE. Dependabot runs as a GitHub-hosted "dynamic"
#   workflow that GitHub's docs say "does not count towards your included GitHub Actions
#   minutes"; measured 2026-09-22, a private estate repository's Dependabot job got a hosted
#   runner 86 minutes after that account's ordinary hosted jobs were refused for billing.
#   It cannot use the mini anyway: a self-hosted Dependabot runner must be Linux x64 with
#   Docker, and the mini's runners are arm64 containers with no Docker socket.
version: 2

updates:
  # ── The toolchain (bun.lock) ────────────────────────────────────────────────
  # ⚠️ BLOCKED UPSTREAM, 2026-09-22: bun 1.4 writes bun.lock \`lockfileVersion\` 2 and
  #   Dependabot's updater bundles bun 1.3.14, which reads up to 1, so this block fails in
  #   every estate repository with "Unsupported bun.lock 'lockfileVersion' 2". The fix is
  #   dependabot/dependabot-core pull request 16071. The github-actions block is unaffected.
  # ⛔ ONE BUN BLOCK, SO ONE SCHEDULE. Dependabot refuses two blocks for one ecosystem and
  #   target branch whose directories overlap, so the \`homeflare\` group cannot be daily
  #   while the rest stays weekly. The block is daily; \`cooldown\` slows the rest.
  - package-ecosystem: bun
    directories:
${bunDirs.map((dir) => `      - ${dir}`).join('\n')}
    schedule:
      # ⚠️ Dependabot's \`daily\` is Monday to Friday; a weekend kit release lands on Monday.
      interval: daily
      time: '09:00'
      timezone: America/New_York
    # ⛔ THE EXCLUDE IS NOT OPTIONAL. Dependabot applies a 3-day cooldown to every version
    #   update even when this key is absent, so without it a kit release would wait three
    #   days before its bump opened — and "daily" would quietly mean "three days late".
    cooldown:
      default-days: ${THIRD_PARTY_COOLDOWN_DAYS}
      exclude: ['${HOMEFLARE_PATTERN}']
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: scope
    labels: [dependencies]
    groups:
      # ★ FIRST, AND EVERY UPDATE TYPE. A kit release is one set of packages built to work
      #   together, so they move as one pull request; \`bun run check\` is what reads it, and
      #   .github/workflows/dependabot-automerge.yml merges it when that is green.
      #   ⚠️ A release that changes what @homeflare/config renders fails the drift test here
      #   by design; \`bun run repo-shape:refresh\` on the branch is the one-command fix.
      ${HOMEFLARE_GROUP}:
        patterns: ['${HOMEFLARE_PATTERN}']

      # oxfmt and oxlint move together and only affect style. Minor and patch bumps are
      # noise unless they fail CI, which is what CI is for.
      lint-and-format:
        patterns: ['oxfmt', 'oxlint']
        update-types: [minor, patch]

      # ⚠️ MAJORS EXCLUDED DELIBERATELY. TypeScript majors change what typechecks;
      #   changesets majors have renamed inputs and dropped compatibility (the action's v2
      #   did both). These want reading, not merging on green.
      build-tooling:
        patterns: ['typescript', '@changesets/*', '@types/bun']
        update-types: [minor, patch]

  # ── The workflows themselves ────────────────────────────────────────────────
  # ★ Actions go stale invisibly: nothing fails, they just keep running old code. The
  #   estate's first workflows pinned checkout@v5 (current: v7) and changesets/action@v1
  #   (current: v2, with every input renamed) — measured 2026-09-15.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: America/New_York
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'ci'
    labels: [dependencies, github-actions]
    groups:
      actions:
        patterns: ['*']
        update-types: [minor, patch]
`;
}
